// GENERATED BY DBBINDING TREADLE - Do not edit

use crate::db::Result;
use crate::media::Media;
use crossbeam_channel::Sender as OneshotSender;

/// DbCommand variants for Media operations
#[derive(Debug)]
pub enum MediaCommand {
  InsertMedia {
    url: String,
    title: Option<String>,
    notes: Option<String>,
    content_hash: Option<String>,
    respond: oneshot::Sender<Result<i64>>,
  },
  GetMediaById {
    id: i64,
    respond: oneshot::Sender<Result<Option<Media>>>,
  },
  GetMediaByUrl {
    url: String,
    respond: oneshot::Sender<Result<Option<Media>>>,
  },
  ListMedias {
    limit: Option<usize>,
    offset: Option<usize>,
    respond: oneshot::Sender<Result<Vec<Media>>>,
  },
  UpdateMedia {
    id: i64,
    title: Option<String>,
    notes: Option<String>,
    respond: oneshot::Sender<Result<bool>>,
  },
  DeleteMedia {
    id: i64,
    respond: oneshot::Sender<Result<bool>>,
  },
  DeleteMediaByUrl {
    url: String,
    respond: oneshot::Sender<Result<bool>>,
  },
}

// Re-export as part of DbCommand enum
// impl DbActor {
//   fn handle_media_command(&self, cmd: MediaCommand) { ... }
// }
