// GENERATED BY DBBINDING TREADLE - Do not edit

use crate::db::Result;
use crate::person::Person;
use crossbeam_channel::Sender as OneshotSender;

/// DbCommand variants for Person operations
#[derive(Debug)]
pub enum PersonCommand {
  InsertPerson {
    url: String,
    title: Option<String>,
    notes: Option<String>,
    content_hash: Option<String>,
    respond: oneshot::Sender<Result<i64>>,
  },
  GetPersonById {
    id: i64,
    respond: oneshot::Sender<Result<Option<Person>>>,
  },
  GetPersonByUrl {
    url: String,
    respond: oneshot::Sender<Result<Option<Person>>>,
  },
  ListPersons {
    limit: Option<usize>,
    offset: Option<usize>,
    respond: oneshot::Sender<Result<Vec<Person>>>,
  },
  UpdatePerson {
    id: i64,
    title: Option<String>,
    notes: Option<String>,
    respond: oneshot::Sender<Result<bool>>,
  },
  DeletePerson {
    id: i64,
    respond: oneshot::Sender<Result<bool>>,
  },
  DeletePersonByUrl {
    url: String,
    respond: oneshot::Sender<Result<bool>>,
  },
}

// Re-export as part of DbCommand enum
// impl DbActor {
//   fn handle_person_command(&self, cmd: PersonCommand) { ... }
// }
