// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: node_modules/@o19/spire-loom/machinery/bobbin/ddd/adaptor-selector.ts.ejs
// Template file: adaptor-selector.ts.ejs
// To override: Copy this template to loom/bobbin/ddd/adaptor-selector.ts.ejs
// 
// To modify the generated output, edit the template file above.
/**
 * Adaptor Selector
 * 
 * Manual composition of adaptors and services.
 * This is the ONE manual file that wires everything together.
 * 
 * Usage:
 *   const services = createServices(db, invoke);
 *   const bookmarkService = services.bookmark;
 * 
 * @generated by ddd-services treadle
 * @manual-update Add domain-specific logic here
 */

import type { Kysely } from 'kysely';
import type { DB } from './db/types.js';
import { BookmarkService } from './services/gen/bookmark.service.gen.js';
import type { BookmarkPort } from './ports/gen/bookmark.port.gen.js';
import {
  BookmarkKyselyAdaptor,
  BookmarkTauriAdaptor
} from './adaptors/gen/bookmark.adaptor.gen.js';
import { ConversationService } from './services/gen/conversation.service.gen.js';
import type { ConversationPort } from './ports/gen/conversation.port.gen.js';
import {
  ConversationKyselyAdaptor,
  ConversationTauriAdaptor
} from './adaptors/gen/conversation.adaptor.gen.js';
import { MediaService } from './services/gen/media.service.gen.js';
import type { MediaPort } from './ports/gen/media.port.gen.js';
import {
  MediaKyselyAdaptor,
  MediaTauriAdaptor
} from './adaptors/gen/media.adaptor.gen.js';
import { PersonService } from './services/gen/person.service.gen.js';
import type { PersonPort } from './ports/gen/person.port.gen.js';
import {
  PersonKyselyAdaptor,
  PersonTauriAdaptor
} from './adaptors/gen/person.adaptor.gen.js';
import { PostService } from './services/gen/post.service.gen.js';
import type { PostPort } from './ports/gen/post.port.gen.js';
import {
  PostKyselyAdaptor,
  PostTauriAdaptor
} from './adaptors/gen/post.adaptor.gen.js';

/**
 * Container for all domain services
 */
export interface Services {
  bookmark: BookmarkPort;
  conversation: ConversationPort;
  media: MediaPort;
  person: PersonPort;
  post: PostPort;
}

/**
 * Create all services with their adaptors
 * 
 * @param db - Kysely database instance for read operations
 * @param invoke - Tauri invoke function for write operations
 */
export function createServices(
  db: Kysely<DB>,
  invoke: <T>(cmd: string, args?: Record<string, unknown>) => Promise<T>
): Services {
  const bookmarkReadAdaptor = new BookmarkKyselyAdaptor(db);
  const bookmarkWriteAdaptor = new BookmarkTauriAdaptor(invoke);
  const conversationReadAdaptor = new ConversationKyselyAdaptor(db);
  const conversationWriteAdaptor = new ConversationTauriAdaptor(invoke);
  const mediaReadAdaptor = new MediaKyselyAdaptor(db);
  const mediaWriteAdaptor = new MediaTauriAdaptor(invoke);
  const personReadAdaptor = new PersonKyselyAdaptor(db);
  const personWriteAdaptor = new PersonTauriAdaptor(invoke);
  const postReadAdaptor = new PostKyselyAdaptor(db);
  const postWriteAdaptor = new PostTauriAdaptor(invoke);

  return {
    bookmark: new BookmarkService(
      bookmarkReadAdaptor,
      bookmarkWriteAdaptor
    ),
    conversation: new ConversationService(
      conversationReadAdaptor,
      conversationWriteAdaptor
    ),
    media: new MediaService(
      mediaReadAdaptor,
      mediaWriteAdaptor
    ),
    person: new PersonService(
      personReadAdaptor,
      personWriteAdaptor
    ),
    post: new PostService(
      postReadAdaptor,
      postWriteAdaptor
    ),
  };
}

/**
 * Singleton services instance (initialized once)
 */
let servicesInstance: Services | null = null;

/**
 * Initialize services (call once at app startup)
 */
export function initializeServices(
  db: Kysely<DB>,
  invoke: <T>(cmd: string, args?: Record<string, unknown>) => Promise<T>
): Services {
  if (!servicesInstance) {
    servicesInstance = createServices(db, invoke);
  }
  return servicesInstance;
}

/**
 * Get services instance (must call initializeServices first)
 */
export function getServices(): Services {
  if (!servicesInstance) {
    throw new Error('Services not initialized. Call initializeServices() first.');
  }
  return servicesInstance;
}
