// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: node_modules/@o19/spire-loom/machinery/bobbin/typescript/ports.ts.ejs
// Template file: ports.ts.ejs
// To override: Copy this template to loom/bobbin/typescript/ports.ts.ejs
// 
// To modify the generated output, edit the template file above.
// GENERATED BY typescript-ddd-generator - Do not edit

/**
 * BookmarkMgmt.addBookmark
 */
export interface add_bookmarkPort {
  add_bookmark([object Object],[object Object],[object Object]): Promise<void>;
}

/**
 * BookmarkMgmt.getBookmarkByUrl
 */
export interface get_bookmark_by_urlPort {
  get_bookmark_by_url([object Object]): Promise<void>;
}

/**
 * BookmarkMgmt.listBookmarks
 */
export interface list_bookmarksPort {
  list_bookmarks([object Object]): Promise<void>;
}

/**
 * BookmarkMgmt.deleteBookmark
 */
export interface delete_bookmarkPort {
  delete_bookmark([object Object]): Promise<void>;
}

/**
 * ConversationMgmt.addConversation
 */
export interface add_conversationPort {
  add_conversation([object Object],[object Object],[object Object]): Promise<void>;
}

/**
 * ConversationMgmt.getConversation
 */
export interface get_conversationPort {
  get_conversation([object Object]): Promise<void>;
}

/**
 * ConversationMgmt.listConversations
 */
export interface list_conversationsPort {
  list_conversations(): Promise<void>;
}

/**
 * ConversationMgmt.updateConversation
 */
export interface update_conversationPort {
  update_conversation([object Object],[object Object],[object Object]): Promise<void>;
}

/**
 * ConversationMgmt.deleteConversation
 */
export interface delete_conversationPort {
  delete_conversation([object Object]): Promise<void>;
}

/**
 * ConversationMgmt.addParticipant
 */
export interface add_participantPort {
  add_participant([object Object],[object Object],[object Object]): Promise<void>;
}

/**
 * ConversationMgmt.removeParticipant
 */
export interface remove_participantPort {
  remove_participant([object Object],[object Object]): Promise<void>;
}

/**
 * ConversationMgmt.listParticipants
 */
export interface list_participantsPort {
  list_participants([object Object]): Promise<void>;
}

/**
 * ConversationMgmt.addConversationMedia
 */
export interface add_conversation_mediaPort {
  add_conversation_media([object Object],[object Object],[object Object]): Promise<void>;
}

/**
 * ConversationMgmt.removeConversationMedia
 */
export interface remove_conversation_mediaPort {
  remove_conversation_media([object Object],[object Object]): Promise<void>;
}

/**
 * ConversationMgmt.listConversationMedia
 */
export interface list_conversation_mediaPort {
  list_conversation_media([object Object]): Promise<void>;
}

/**
 * MediaMgmt.addMediaLink
 */
export interface add_media_linkPort {
  add_media_link([object Object],[object Object],[object Object],[object Object]): Promise<void>;
}

/**
 * MediaMgmt.addMediaFile
 */
export interface add_media_filePort {
  add_media_file([object Object],[object Object]): Promise<void>;
}

/**
 * MediaMgmt.getMediaByUrl
 */
export interface get_media_by_urlPort {
  get_media_by_url([object Object]): Promise<void>;
}

/**
 * MediaMgmt.listMedia
 */
export interface list_mediaPort {
  list_media([object Object]): Promise<void>;
}

/**
 * MediaMgmt.deleteMedia
 */
export interface delete_mediaPort {
  delete_media([object Object]): Promise<void>;
}

/**
 * PersonMgmt.addPerson
 */
export interface add_personPort {
  add_person([object Object],[object Object],[object Object]): Promise<void>;
}

/**
 * PersonMgmt.getPersonByHandle
 */
export interface get_person_by_handlePort {
  get_person_by_handle([object Object]): Promise<void>;
}

/**
 * PersonMgmt.listPeople
 */
export interface list_peoplePort {
  list_people(): Promise<void>;
}

/**
 * PersonMgmt.updatePerson
 */
export interface update_personPort {
  update_person([object Object],[object Object],[object Object]): Promise<void>;
}

/**
 * PersonMgmt.deletePerson
 */
export interface delete_personPort {
  delete_person([object Object]): Promise<void>;
}

/**
 * PostMgmt.addPost
 */
export interface add_postPort {
  add_post([object Object],[object Object],[object Object]): Promise<void>;
}

/**
 * PostMgmt.getPostByUrl
 */
export interface get_post_by_urlPort {
  get_post_by_url([object Object]): Promise<void>;
}

/**
 * PostMgmt.listPosts
 */
export interface list_postsPort {
  list_posts([object Object]): Promise<void>;
}

/**
 * PostMgmt.updatePost
 */
export interface update_postPort {
  update_post([object Object],[object Object],[object Object]): Promise<void>;
}

/**
 * PostMgmt.deletePost
 */
export interface delete_postPort {
  delete_post([object Object]): Promise<void>;
}

