//! Example: Using the FoundframeRadicleClient from @o19/foundframe-tauri
//!
//! This shows how the tauri-plugin should consume the android
//! crate to connect to the singleton service.

use android::{BpFoundframeRadicle, FoundframeRadicleClient};
use rsbinder::*;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Initialize Binder (required in each process)
    ProcessState::init_default();

    // Get service from ServiceManager
    // This is the client-side proxy generated by rsbinder from AIDL
    let service = match hub::get_service("foundframe.radicle")? {
        Some(binder) => BpFoundframeRadicle::new(binder)?,
        None => {
            println!("Service not running - need to start it from Kotlin side");
            return Ok(());
        }
    };

    // Call methods on the service
    println!("Node running: {}", service.isNodeRunning()?);
    
    if let Ok(node_id) = service.getNodeId() {
        println!("Node ID: {}", node_id);
    }
    
    println!("Node alias: {}", service.getNodeAlias()?);

    // Subscribe to events (callback would be implemented via IEventCallback)
    // service.subscribeEvents(...)?;

    Ok(())
}
