// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/packages/spire-loom/machinery/bobbin/tauri/commands.ts.ejs
// Template file: commands.ts.ejs
// To override: Copy this template to loom/bobbin/tauri/commands.ts.ejs
// 
// To modify the generated output, edit the template file above.
// GENERATED BY tauri-adaptor Treadle - Do not edit
// Tauri command handlers for Bookmark

import { invoke } from '@tauri-apps/api/core';
import type { Bookmark, CreateBookmark, UpdateBookmark } from '@o19/foundframe-front/domain';

/**
 * Create a new bookmark
 */
export async function createBookmark(data: CreateBookmark): Promise<Bookmark> {
  return await invoke<Bookmark>('plugin:o19-foundframe-tauri|create_bookmark', { data });
}

/**
 * Get bookmark by ID
 */
export async function getBookmarkById(id: number): Promise<Bookmark | null> {
  return await invoke<Bookmark | null>('plugin:o19-foundframe-tauri|get_bookmark_by_id', { id });
}

/**
 * Update bookmark
 */
export async function updateBookmark(id: number, data: UpdateBookmark): Promise<void> {
  return await invoke<void>('plugin:o19-foundframe-tauri|update_bookmark', { id, data });
}

/**
 * Delete bookmark
 */
export async function deleteBookmark(id: number): Promise<void> {
  return await invoke<void>('plugin:o19-foundframe-tauri|delete_bookmark', { id });
}

/**
 * List all bookmarks
 */
export async function listBookmarks(): Promise<Bookmark[]> {
  return await invoke<Bookmark[]>('plugin:o19-foundframe-tauri|list_bookmarks');
}

