// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/packages/spire-loom/machinery/bobbin/tauri/commands.ts.ejs
// Template file: commands.ts.ejs
// To override: Copy this template to loom/bobbin/tauri/commands.ts.ejs
// 
// To modify the generated output, edit the template file above.
// GENERATED BY tauri-adaptor Treadle - Do not edit
// Tauri command handlers for MediaSource

import { invoke } from '@tauri-apps/api/core';
import type { MediaSource, CreateMediaSource, UpdateMediaSource } from '@o19/foundframe-front/domain';

/**
 * Create a new mediaSource
 */
export async function createMediaSource(data: CreateMediaSource): Promise<MediaSource> {
  return await invoke<MediaSource>('plugin:o19-foundframe-tauri|create_mediaSource', { data });
}

/**
 * Get mediaSource by ID
 */
export async function getMediaSourceById(id: number): Promise<MediaSource | null> {
  return await invoke<MediaSource | null>('plugin:o19-foundframe-tauri|get_mediaSource_by_id', { id });
}

/**
 * Update mediaSource
 */
export async function updateMediaSource(id: number, data: UpdateMediaSource): Promise<void> {
  return await invoke<void>('plugin:o19-foundframe-tauri|update_mediaSource', { id, data });
}

/**
 * Delete mediaSource
 */
export async function deleteMediaSource(id: number): Promise<void> {
  return await invoke<void>('plugin:o19-foundframe-tauri|delete_mediaSource', { id });
}

/**
 * List all mediaSources
 */
export async function listMediaSources(): Promise<MediaSource[]> {
  return await invoke<MediaSource[]>('plugin:o19-foundframe-tauri|list_mediaSources');
}

