// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/packages/spire-loom/machinery/bobbin/tauri/commands.ts.ejs
// Template file: commands.ts.ejs
// To override: Copy this template to loom/bobbin/tauri/commands.ts.ejs
// 
// To modify the generated output, edit the template file above.
// GENERATED BY tauri-adaptor Treadle - Do not edit
// Tauri command handlers for Person

import { invoke } from '@tauri-apps/api/core';
import type { Person, CreatePerson, UpdatePerson } from '@o19/foundframe-front/domain';

/**
 * Create a new person
 */
export async function createPerson(data: CreatePerson): Promise<Person> {
  return await invoke<Person>('plugin:o19-foundframe-tauri|create_person', { data });
}

/**
 * Get person by ID
 */
export async function getPersonById(id: number): Promise<Person | null> {
  return await invoke<Person | null>('plugin:o19-foundframe-tauri|get_person_by_id', { id });
}

/**
 * Update person
 */
export async function updatePerson(id: number, data: UpdatePerson): Promise<void> {
  return await invoke<void>('plugin:o19-foundframe-tauri|update_person', { id, data });
}

/**
 * Delete person
 */
export async function deletePerson(id: number): Promise<void> {
  return await invoke<void>('plugin:o19-foundframe-tauri|delete_person', { id });
}

/**
 * List all persons
 */
export async function listPersons(): Promise<Person[]> {
  return await invoke<Person[]>('plugin:o19-foundframe-tauri|list_persons');
}

