// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/packages/spire-loom/machinery/bobbin/tauri/commands.ts.mejs
// Template file: commands.ts.mejs
// To override: Copy this template to loom/bobbin/tauri/commands.ts.mejs
// 
// To modify the generated output, edit the template file above.
// GENERATED BY tauri-adaptor Treadle - Do not edit
// Tauri command handlers for 

import { invoke } from '@tauri-apps/api/core';
import type { , Create,
Update } from '@o19/foundframe-front/domain';

/**
 * Create a new 
 */
export async function create(data: Create): Promise<> {
  return await invoke<>('plugin:o19-foundframe-tauri|create_', { data });
}

/**
 * Get  by ID
 */
export async function getById(id: number):
Promise< | null> {
  return await invoke< | null>('plugin:o19-foundframe-tauri|get__by_id', { id });
}

/**
 * Update 
 */
export async function update(id: number, data:
Update): Promise<void> {
  return await invoke<void>('plugin:o19-foundframe-tauri|update_', { id, data });
}

/**
 * Delete 
 */
export async function delete(id: number): Promise<void> {
  return await invoke<void>('plugin:o19-foundframe-tauri|delete_', { id });
}

/**
 * List all s
 */
export async function lists(): Promise<[]> {
  return await invoke<[]>('plugin:o19-foundframe-tauri|list_s');
}

