//! Tauri Commands - GENERATED by spire-loom
//!
//! These commands expose foundframe operations to the frontend.
//! Each command delegates to the SpireFoundframePlatformTrait trait implementation.
//!
//! Generated from Management definitions with @reach('Local') | @reach('Global')

use crate::spire::{SpireFoundframeExt, Result};
use crate::spire::models::*;
use tauri::{AppHandle, Manager, Runtime};

/// BookmarkMgmt.bookmark_addBookmark
#[tauri::command]
pub(crate) async fn bookmark_addBookmark<R: Runtime>(
  app: AppHandle<R>,
    url: String,
    title: Option<String>,
    notes: Option<String>
  
) -> Result<()> {
  app.spireFoundframePlatform().bookmark_addBookmark(url, title, notes)
}

/// BookmarkMgmt.bookmark_getBookmarkByUrl
#[tauri::command]
pub(crate) async fn bookmark_getBookmarkByUrl<R: Runtime>(
  app: AppHandle<R>,
    pkbUrl: String
  
) -> Result<String> {
  app.spireFoundframePlatform().bookmark_getBookmarkByUrl(pkbUrl)
}

/// BookmarkMgmt.bookmark_listBookmarks
#[tauri::command]
pub(crate) async fn bookmark_listBookmarks<R: Runtime>(
  app: AppHandle<R>,
    directory: Option<String>
  
) -> Result<Vec<String>> {
  app.spireFoundframePlatform().bookmark_listBookmarks(directory)
}

/// BookmarkMgmt.bookmark_deleteBookmark
#[tauri::command]
pub(crate) async fn bookmark_deleteBookmark<R: Runtime>(
  app: AppHandle<R>,
    pkbUrl: String
  
) -> Result<bool> {
  app.spireFoundframePlatform().bookmark_deleteBookmark(pkbUrl)
}

/// DeviceMgmt.device_generatePairingCode
#[tauri::command]
pub(crate) async fn device_generatePairingCode<R: Runtime>(
  app: AppHandle<R>,
  
) -> Result<String> {
  app.spireFoundframePlatform().device_generatePairingCode()
}

/// DeviceMgmt.device_confirmPairing
#[tauri::command]
pub(crate) async fn device_confirmPairing<R: Runtime>(
  app: AppHandle<R>,
    deviceId: String,
    code: String
  
) -> Result<bool> {
  app.spireFoundframePlatform().device_confirmPairing(deviceId, code)
}

/// DeviceMgmt.device_unpairDevice
#[tauri::command]
pub(crate) async fn device_unpairDevice<R: Runtime>(
  app: AppHandle<R>,
    deviceId: String
  
) -> Result<()> {
  app.spireFoundframePlatform().device_unpairDevice(deviceId)
}

/// DeviceMgmt.device_listPairedDevices
#[tauri::command]
pub(crate) async fn device_listPairedDevices<R: Runtime>(
  app: AppHandle<R>,
  
) -> Result<String> {
  app.spireFoundframePlatform().device_listPairedDevices()
}

/// DeviceMgmt.device_followDevice
#[tauri::command]
pub(crate) async fn device_followDevice<R: Runtime>(
  app: AppHandle<R>,
    deviceId: String
  
) -> Result<bool> {
  app.spireFoundframePlatform().device_followDevice(deviceId)
}

/// DeviceMgmt.device_unfollowDevice
#[tauri::command]
pub(crate) async fn device_unfollowDevice<R: Runtime>(
  app: AppHandle<R>,
    deviceId: String
  
) -> Result<()> {
  app.spireFoundframePlatform().device_unfollowDevice(deviceId)
}

/// DeviceMgmt.device_listFollowers
#[tauri::command]
pub(crate) async fn device_listFollowers<R: Runtime>(
  app: AppHandle<R>,
  
) -> Result<String> {
  app.spireFoundframePlatform().device_listFollowers()
}

/// DeviceMgmt.device_isFollowing
#[tauri::command]
pub(crate) async fn device_isFollowing<R: Runtime>(
  app: AppHandle<R>,
    deviceId: String
  
) -> Result<bool> {
  app.spireFoundframePlatform().device_isFollowing(deviceId)
}

