//! Tauri Commands - GENERATED by spire-loom
//!
//! These commands expose foundframe operations to the frontend.
//! Each command delegates to the SpireFoundframePlatformTrait trait implementation.
//!
//! Generated from Management definitions with @reach('Local') | @reach('Global')

use crate::spire::{SpireFoundframeExt, Result};
use crate::spire::models::*;
use tauri::{AppHandle, Manager, Runtime};

/// BookmarkMgmt.addBookmark
#[tauri::command]
pub(crate) async fn add_bookmark<R: Runtime>(
  app: AppHandle<R>,
    url: String,
    title: Option<String>,
    notes: Option<String>
  
) -> Result<String> {
  app.spireFoundframePlatform().add_bookmark(url, title, notes)
}

/// BookmarkMgmt.getBookmark
#[tauri::command]
pub(crate) async fn get_bookmark<R: Runtime>(
  app: AppHandle<R>,
    pkbUrl: String
  
) -> Result<String> {
  app.spireFoundframePlatform().get_bookmark(pkbUrl)
}

/// BookmarkMgmt.listBookmarks
#[tauri::command]
pub(crate) async fn list_bookmarks<R: Runtime>(
  app: AppHandle<R>,
    directory: Option<String>
  
) -> Result<Vec<String>> {
  app.spireFoundframePlatform().list_bookmarks(directory)
}

/// BookmarkMgmt.deleteBookmark
#[tauri::command]
pub(crate) async fn delete_bookmark<R: Runtime>(
  app: AppHandle<R>,
    pkbUrl: String
  
) -> Result<bool> {
  app.spireFoundframePlatform().delete_bookmark(pkbUrl)
}

/// DeviceMgmt.generatePairingCode
#[tauri::command]
pub(crate) async fn generate_pairing_code<R: Runtime>(
  app: AppHandle<R>,
  
) -> Result<String> {
  app.spireFoundframePlatform().generate_pairing_code()
}

/// DeviceMgmt.confirmPairing
#[tauri::command]
pub(crate) async fn confirm_pairing<R: Runtime>(
  app: AppHandle<R>,
    deviceId: String,
    code: String
  
) -> Result<bool> {
  app.spireFoundframePlatform().confirm_pairing(deviceId, code)
}

/// DeviceMgmt.unpairDevice
#[tauri::command]
pub(crate) async fn unpair_device<R: Runtime>(
  app: AppHandle<R>,
    deviceId: String
  
) -> Result<()> {
  app.spireFoundframePlatform().unpair_device(deviceId)
}

/// DeviceMgmt.listPairedDevices
#[tauri::command]
pub(crate) async fn list_paired_devices<R: Runtime>(
  app: AppHandle<R>,
  
) -> Result<Vec<String>> {
  app.spireFoundframePlatform().list_paired_devices()
}

/// DeviceMgmt.followDevice
#[tauri::command]
pub(crate) async fn follow_device<R: Runtime>(
  app: AppHandle<R>,
    deviceId: String
  
) -> Result<bool> {
  app.spireFoundframePlatform().follow_device(deviceId)
}

/// DeviceMgmt.unfollowDevice
#[tauri::command]
pub(crate) async fn unfollow_device<R: Runtime>(
  app: AppHandle<R>,
    deviceId: String
  
) -> Result<()> {
  app.spireFoundframePlatform().unfollow_device(deviceId)
}

/// DeviceMgmt.listFollowers
#[tauri::command]
pub(crate) async fn list_followers<R: Runtime>(
  app: AppHandle<R>,
  
) -> Result<Vec<String>> {
  app.spireFoundframePlatform().list_followers()
}

/// DeviceMgmt.isFollowing
#[tauri::command]
pub(crate) async fn is_following<R: Runtime>(
  app: AppHandle<R>,
    deviceId: String
  
) -> Result<bool> {
  app.spireFoundframePlatform().is_following(deviceId)
}

/// EventMgmt.subscribeEvents
#[tauri::command]
pub(crate) async fn subscribe_events<R: Runtime>(
  app: AppHandle<R>,
    callback: String
  
) -> Result<()> {
  app.spireFoundframePlatform().subscribe_events(callback)
}

/// EventMgmt.unsubscribeEvents
#[tauri::command]
pub(crate) async fn unsubscribe_events<R: Runtime>(
  app: AppHandle<R>,
    callback: String
  
) -> Result<()> {
  app.spireFoundframePlatform().unsubscribe_events(callback)
}

/// EventMgmt.supportsEvents
#[tauri::command]
pub(crate) async fn supports_events<R: Runtime>(
  app: AppHandle<R>,
  
) -> Result<bool> {
  app.spireFoundframePlatform().supports_events()
}

