// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/packages/spire-loom/machinery/bobbin/tauri/commands.rs.ejs
// Template file: commands.rs.ejs
// To override: Copy this template to loom/bobbin/tauri/commands.rs.ejs
// 
// To modify the generated output, edit the template file above.
//! Tauri Commands - GENERATED by spire-loom
//!
//! These commands expose foundframe operations to the frontend.
//! Each command delegates to the SpireFoundframePlatformTrait trait implementation.
//!
//! Generated from Management definitions with @reach('Local') | @reach('Global')

use crate::spire::{SpireFoundframeExt, Result};
use crate::spire::models::*;
use tauri::{AppHandle, Manager, Runtime};

/// BookmarkMgmt.bookmark_addBookmark
#[tauri::command]
pub(crate) async fn bookmark_add_bookmark<R: Runtime>(
  app: AppHandle<R>,
    url: String,
    title: Option<String>,
    notes: Option<String>
  
) -> () {
  app.spireFoundframePlatform().bookmark_add_bookmark(url, title, notes)
}

/// BookmarkMgmt.bookmark_getBookmark
#[tauri::command]
pub(crate) async fn bookmark_get_bookmark<R: Runtime>(
  app: AppHandle<R>,
    id: i64
  
) -> Bookmark {
  app.spireFoundframePlatform().bookmark_get_bookmark(id)
}

/// BookmarkMgmt.bookmark_getBookmarkByUri
#[tauri::command]
pub(crate) async fn bookmark_get_bookmark_by_uri<R: Runtime>(
  app: AppHandle<R>,
    uri: String
  
) -> Bookmark {
  app.spireFoundframePlatform().bookmark_get_bookmark_by_uri(uri)
}

/// BookmarkMgmt.bookmark_listBookmarks
#[tauri::command]
pub(crate) async fn bookmark_list_bookmarks<R: Runtime>(
  app: AppHandle<R>,
    limit: Option<i64>,
    offset: Option<i64>,
    filter: Option<BookmarkFilter>
  
) -> Vec<Bookmark[]> {
  app.spireFoundframePlatform().bookmark_list_bookmarks(limit, offset, filter)
}

/// BookmarkMgmt.bookmark_updateBookmark
#[tauri::command]
pub(crate) async fn bookmark_update_bookmark<R: Runtime>(
  app: AppHandle<R>,
    id: i64,
    title: Option<String>,
    notes: Option<String>
  
) -> bool {
  app.spireFoundframePlatform().bookmark_update_bookmark(id, title, notes)
}

/// BookmarkMgmt.bookmark_deleteBookmark
#[tauri::command]
pub(crate) async fn bookmark_delete_bookmark<R: Runtime>(
  app: AppHandle<R>,
    id: i64
  
) -> bool {
  app.spireFoundframePlatform().bookmark_delete_bookmark(id)
}

/// ConversationMgmt.conversation_addConversation
#[tauri::command]
pub(crate) async fn conversation_add_conversation<R: Runtime>(
  app: AppHandle<R>,
    content: ConversationEntry[],
    capture_time: Date,
    title: Option<String>,
    source_url: Option<String>
  
) -> () {
  app.spireFoundframePlatform().conversation_add_conversation(content, capture_time, title, source_url)
}

/// ConversationMgmt.conversation_getConversation
#[tauri::command]
pub(crate) async fn conversation_get_conversation<R: Runtime>(
  app: AppHandle<R>,
    id: i64
  
) -> Conversation {
  app.spireFoundframePlatform().conversation_get_conversation(id)
}

/// ConversationMgmt.conversation_listConversations
#[tauri::command]
pub(crate) async fn conversation_list_conversations<R: Runtime>(
  app: AppHandle<R>,
    limit: Option<i64>,
    offset: Option<i64>,
    filter: Option<ConversationFilter>
  
) -> Vec<Conversation[]> {
  app.spireFoundframePlatform().conversation_list_conversations(limit, offset, filter)
}

/// ConversationMgmt.conversation_updateConversation
#[tauri::command]
pub(crate) async fn conversation_update_conversation<R: Runtime>(
  app: AppHandle<R>,
    id: i64,
    title: Option<String>,
    content: Option<ConversationEntry[]>
  
) -> bool {
  app.spireFoundframePlatform().conversation_update_conversation(id, title, content)
}

/// ConversationMgmt.conversation_deleteConversation
#[tauri::command]
pub(crate) async fn conversation_delete_conversation<R: Runtime>(
  app: AppHandle<R>,
    id: i64
  
) -> bool {
  app.spireFoundframePlatform().conversation_delete_conversation(id)
}

/// ConversationMgmt.conversation_addParticipant
#[tauri::command]
pub(crate) async fn conversation_add_participant<R: Runtime>(
  app: AppHandle<R>,
    conversation_id: i64,
    person_id: i64,
    role: Option<String>
  
) -> bool {
  app.spireFoundframePlatform().conversation_add_participant(conversation_id, person_id, role)
}

/// ConversationMgmt.conversation_removeParticipant
#[tauri::command]
pub(crate) async fn conversation_remove_participant<R: Runtime>(
  app: AppHandle<R>,
    conversation_id: i64,
    person_id: i64
  
) -> bool {
  app.spireFoundframePlatform().conversation_remove_participant(conversation_id, person_id)
}

/// ConversationMgmt.conversation_listParticipants
#[tauri::command]
pub(crate) async fn conversation_list_participants<R: Runtime>(
  app: AppHandle<R>,
    conversation_id: i64
  
) -> Vec<number[]> {
  app.spireFoundframePlatform().conversation_list_participants(conversation_id)
}

/// ConversationMgmt.conversation_addConversationMedia
#[tauri::command]
pub(crate) async fn conversation_add_conversation_media<R: Runtime>(
  app: AppHandle<R>,
    conversation_id: i64,
    media_id: i64,
    context: Option<Record<string, unknown>>
  
) -> bool {
  app.spireFoundframePlatform().conversation_add_conversation_media(conversation_id, media_id, context)
}

/// ConversationMgmt.conversation_removeConversationMedia
#[tauri::command]
pub(crate) async fn conversation_remove_conversation_media<R: Runtime>(
  app: AppHandle<R>,
    conversation_id: i64,
    media_id: i64
  
) -> bool {
  app.spireFoundframePlatform().conversation_remove_conversation_media(conversation_id, media_id)
}

/// ConversationMgmt.conversation_listConversationMedia
#[tauri::command]
pub(crate) async fn conversation_list_conversation_media<R: Runtime>(
  app: AppHandle<R>,
    conversation_id: i64
  
) -> Vec<number[]> {
  app.spireFoundframePlatform().conversation_list_conversation_media(conversation_id)
}

/// DeviceMgmt.device_generatePairingCode
#[tauri::command]
pub(crate) async fn device_generate_pairing_code<R: Runtime>(
  app: AppHandle<R>,
  
) -> String {
  app.spireFoundframePlatform().device_generate_pairing_code()
}

/// DeviceMgmt.device_confirmPairing
#[tauri::command]
pub(crate) async fn device_confirm_pairing<R: Runtime>(
  app: AppHandle<R>,
    device_id: String,
    code: String
  
) -> bool {
  app.spireFoundframePlatform().device_confirm_pairing(device_id, code)
}

/// DeviceMgmt.device_unpairDevice
#[tauri::command]
pub(crate) async fn device_unpair_device<R: Runtime>(
  app: AppHandle<R>,
    device_id: String
  
) -> () {
  app.spireFoundframePlatform().device_unpair_device(device_id)
}

/// DeviceMgmt.device_listPairedDevices
#[tauri::command]
pub(crate) async fn device_list_paired_devices<R: Runtime>(
  app: AppHandle<R>,
  
) -> Vec<string[]> {
  app.spireFoundframePlatform().device_list_paired_devices()
}

/// DeviceMgmt.device_followDevice
#[tauri::command]
pub(crate) async fn device_follow_device<R: Runtime>(
  app: AppHandle<R>,
    device_id: String
  
) -> bool {
  app.spireFoundframePlatform().device_follow_device(device_id)
}

/// DeviceMgmt.device_unfollowDevice
#[tauri::command]
pub(crate) async fn device_unfollow_device<R: Runtime>(
  app: AppHandle<R>,
    device_id: String
  
) -> () {
  app.spireFoundframePlatform().device_unfollow_device(device_id)
}

/// DeviceMgmt.device_listFollowers
#[tauri::command]
pub(crate) async fn device_list_followers<R: Runtime>(
  app: AppHandle<R>,
  
) -> Vec<string[]> {
  app.spireFoundframePlatform().device_list_followers()
}

/// DeviceMgmt.device_isFollowing
#[tauri::command]
pub(crate) async fn device_is_following<R: Runtime>(
  app: AppHandle<R>,
    device_id: String
  
) -> bool {
  app.spireFoundframePlatform().device_is_following(device_id)
}

/// MediaMgmt.media_getMedia
#[tauri::command]
pub(crate) async fn media_get_media<R: Runtime>(
  app: AppHandle<R>,
    id: i64
  
) -> Media {
  app.spireFoundframePlatform().media_get_media(id)
}

/// MediaMgmt.media_getMediaByHash
#[tauri::command]
pub(crate) async fn media_get_media_by_hash<R: Runtime>(
  app: AppHandle<R>,
    content_hash: String
  
) -> Media {
  app.spireFoundframePlatform().media_get_media_by_hash(content_hash)
}

/// MediaMgmt.media_listMedia
#[tauri::command]
pub(crate) async fn media_list_media<R: Runtime>(
  app: AppHandle<R>,
    limit: Option<i64>,
    offset: Option<i64>,
    filter: Option<MediaFilter>
  
) -> Vec<Media[]> {
  app.spireFoundframePlatform().media_list_media(limit, offset, filter)
}

/// MediaMgmt.media_updateMedia
#[tauri::command]
pub(crate) async fn media_update_media<R: Runtime>(
  app: AppHandle<R>,
    id: i64,
    title: Option<String>
  
) -> bool {
  app.spireFoundframePlatform().media_update_media(id, title)
}

/// MediaMgmt.media_deleteMedia
#[tauri::command]
pub(crate) async fn media_delete_media<R: Runtime>(
  app: AppHandle<R>,
    id: i64
  
) -> bool {
  app.spireFoundframePlatform().media_delete_media(id)
}

/// MediaMgmt.media_addMediaLink
#[tauri::command]
pub(crate) async fn media_add_media_link<R: Runtime>(
  app: AppHandle<R>,
    uri: String,
    mime_type: String,
    title: Option<String>,
    directory: Option<String>
  
) -> () {
  app.spireFoundframePlatform().media_add_media_link(uri, mime_type, title, directory)
}

/// MediaMgmt.media_addMediaFile
#[tauri::command]
pub(crate) async fn media_add_media_file<R: Runtime>(
  app: AppHandle<R>,
    uri: String,
    title: Option<String>
  
) -> () {
  app.spireFoundframePlatform().media_add_media_file(uri, title)
}

/// MediaSourceMgmt.media_source_registerSource
#[tauri::command]
pub(crate) async fn media_source_register_source<R: Runtime>(
  app: AppHandle<R>,
    url: String,
    adapter_type: MediaAdapterType,
    capabilities: MediaSourceCapability[],
    config: Option<Record<string, unknown>>
  
) -> () {
  app.spireFoundframePlatform().media_source_register_source(url, adapter_type, capabilities, config)
}

/// MediaSourceMgmt.media_source_getSource
#[tauri::command]
pub(crate) async fn media_source_get_source<R: Runtime>(
  app: AppHandle<R>,
    id: i64
  
) -> MediaSource {
  app.spireFoundframePlatform().media_source_get_source(id)
}

/// MediaSourceMgmt.media_source_listSources
#[tauri::command]
pub(crate) async fn media_source_list_sources<R: Runtime>(
  app: AppHandle<R>,
    active_only: Option<bool>,
    adapter_type: Option<MediaAdapterType>
  
) -> Vec<MediaSource[]> {
  app.spireFoundframePlatform().media_source_list_sources(active_only, adapter_type)
}

/// MediaSourceMgmt.media_source_updateSource
#[tauri::command]
pub(crate) async fn media_source_update_source<R: Runtime>(
  app: AppHandle<R>,
    id: i64,
    config: Option<Record<string, unknown>>,
    is_active: Option<bool>
  
) -> bool {
  app.spireFoundframePlatform().media_source_update_source(id, config, is_active)
}

/// MediaSourceMgmt.media_source_unregisterSource
#[tauri::command]
pub(crate) async fn media_source_unregister_source<R: Runtime>(
  app: AppHandle<R>,
    id: i64
  
) -> bool {
  app.spireFoundframePlatform().media_source_unregister_source(id)
}

/// MediaSourceMgmt.media_source_pollSource
#[tauri::command]
pub(crate) async fn media_source_poll_source<R: Runtime>(
  app: AppHandle<R>,
    id: i64
  
) -> PollResult {
  app.spireFoundframePlatform().media_source_poll_source(id)
}

/// MediaSourceMgmt.media_source_getHealth
#[tauri::command]
pub(crate) async fn media_source_get_health<R: Runtime>(
  app: AppHandle<R>,
    id: i64
  
) -> MediaSourceHealth {
  app.spireFoundframePlatform().media_source_get_health(id)
}

/// MediaSourceMgmt.media_source_resetErrors
#[tauri::command]
pub(crate) async fn media_source_reset_errors<R: Runtime>(
  app: AppHandle<R>,
    id: i64
  
) -> bool {
  app.spireFoundframePlatform().media_source_reset_errors(id)
}

/// PersonMgmt.person_addPerson
#[tauri::command]
pub(crate) async fn person_add_person<R: Runtime>(
  app: AppHandle<R>,
    display_name: String,
    handle: Option<String>,
    metadata: Option<Record<string, unknown>>
  
) -> () {
  app.spireFoundframePlatform().person_add_person(display_name, handle, metadata)
}

/// PersonMgmt.person_getPerson
#[tauri::command]
pub(crate) async fn person_get_person<R: Runtime>(
  app: AppHandle<R>,
    id: i64
  
) -> Person {
  app.spireFoundframePlatform().person_get_person(id)
}

/// PersonMgmt.person_getPersonByHandle
#[tauri::command]
pub(crate) async fn person_get_person_by_handle<R: Runtime>(
  app: AppHandle<R>,
    handle: String
  
) -> Person {
  app.spireFoundframePlatform().person_get_person_by_handle(handle)
}

/// PersonMgmt.person_listPeople
#[tauri::command]
pub(crate) async fn person_list_people<R: Runtime>(
  app: AppHandle<R>,
    limit: Option<i64>,
    offset: Option<i64>,
    filter: Option<PersonFilter>
  
) -> Vec<Person[]> {
  app.spireFoundframePlatform().person_list_people(limit, offset, filter)
}

/// PersonMgmt.person_updatePerson
#[tauri::command]
pub(crate) async fn person_update_person<R: Runtime>(
  app: AppHandle<R>,
    id: i64,
    display_name: Option<String>,
    handle: Option<String>,
    metadata: Option<Record<string, unknown>>
  
) -> bool {
  app.spireFoundframePlatform().person_update_person(id, display_name, handle, metadata)
}

/// PersonMgmt.person_deletePerson
#[tauri::command]
pub(crate) async fn person_delete_person<R: Runtime>(
  app: AppHandle<R>,
    id: i64
  
) -> bool {
  app.spireFoundframePlatform().person_delete_person(id)
}

/// PostMgmt.post_addPost
#[tauri::command]
pub(crate) async fn post_add_post<R: Runtime>(
  app: AppHandle<R>,
    bits: AccumulableBit[]
  
) -> i64 {
  app.spireFoundframePlatform().post_add_post(bits)
}

/// PostMgmt.post_getPost
#[tauri::command]
pub(crate) async fn post_get_post<R: Runtime>(
  app: AppHandle<R>,
    id: i64
  
) -> Post {
  app.spireFoundframePlatform().post_get_post(id)
}

/// PostMgmt.post_listPosts
#[tauri::command]
pub(crate) async fn post_list_posts<R: Runtime>(
  app: AppHandle<R>,
    limit: Option<i64>,
    offset: Option<i64>,
    filter: Option<PostFilter>
  
) -> Vec<Post[]> {
  app.spireFoundframePlatform().post_list_posts(limit, offset, filter)
}

/// PostMgmt.post_updatePost
#[tauri::command]
pub(crate) async fn post_update_post<R: Runtime>(
  app: AppHandle<R>,
    id: i64,
    bits: Option<AccumulableBit[]>
  
) -> bool {
  app.spireFoundframePlatform().post_update_post(id, bits)
}

/// PostMgmt.post_deletePost
#[tauri::command]
pub(crate) async fn post_delete_post<R: Runtime>(
  app: AppHandle<R>,
    id: i64
  
) -> bool {
  app.spireFoundframePlatform().post_delete_post(id)
}

/// TheStreamMgmt.the_stream_getEntries
#[tauri::command]
pub(crate) async fn the_stream_get_entries<R: Runtime>(
  app: AppHandle<R>,
    limit: Option<i64>,
    offset: Option<i64>,
    filter: Option<TheStreamEntryFilter>
  
) -> Vec<TheStreamEntry[]> {
  app.spireFoundframePlatform().the_stream_get_entries(limit, offset, filter)
}

/// TheStreamMgmt.the_stream_getEntry
#[tauri::command]
pub(crate) async fn the_stream_get_entry<R: Runtime>(
  app: AppHandle<R>,
    id: i64
  
) -> TheStreamEntry {
  app.spireFoundframePlatform().the_stream_get_entry(id)
}

/// TheStreamMgmt.the_stream_deleteEntry
#[tauri::command]
pub(crate) async fn the_stream_delete_entry<R: Runtime>(
  app: AppHandle<R>,
    id: i64
  
) -> bool {
  app.spireFoundframePlatform().the_stream_delete_entry(id)
}

/// TheStreamMgmt.the_stream_getEntriesByKind
#[tauri::command]
pub(crate) async fn the_stream_get_entries_by_kind<R: Runtime>(
  app: AppHandle<R>,
    kind: 'media' | 'post' | 'bookmark' | 'person' | 'conversation',
    limit: Option<i64>,
    before: Option<i64>
  
) -> TheStreamEntry[] {
  app.spireFoundframePlatform().the_stream_get_entries_by_kind(kind, limit, before)
}

/// TheStreamMgmt.the_stream_search
#[tauri::command]
pub(crate) async fn the_stream_search<R: Runtime>(
  app: AppHandle<R>,
    query: String,
    kinds: Option<string[]>,
    limit: Option<i64>
  
) -> TheStreamEntry[] {
  app.spireFoundframePlatform().the_stream_search(query, kinds, limit)
}

/// TheStreamMgmt.the_stream_addBookmark
#[tauri::command]
pub(crate) async fn the_stream_add_bookmark<R: Runtime>(
  app: AppHandle<R>,
    bookmark_id: i64,
    seen_at: Option<i64>
  
) -> TheStreamEntry {
  app.spireFoundframePlatform().the_stream_add_bookmark(bookmark_id, seen_at)
}

/// TheStreamMgmt.the_stream_addPost
#[tauri::command]
pub(crate) async fn the_stream_add_post<R: Runtime>(
  app: AppHandle<R>,
    post_id: i64,
    seen_at: Option<i64>
  
) -> TheStreamEntry {
  app.spireFoundframePlatform().the_stream_add_post(post_id, seen_at)
}

/// TheStreamMgmt.the_stream_addMedia
#[tauri::command]
pub(crate) async fn the_stream_add_media<R: Runtime>(
  app: AppHandle<R>,
    media_id: i64,
    seen_at: Option<i64>
  
) -> TheStreamEntry {
  app.spireFoundframePlatform().the_stream_add_media(media_id, seen_at)
}

/// TheStreamMgmt.the_stream_addPerson
#[tauri::command]
pub(crate) async fn the_stream_add_person<R: Runtime>(
  app: AppHandle<R>,
    person_id: i64,
    seen_at: Option<i64>
  
) -> TheStreamEntry {
  app.spireFoundframePlatform().the_stream_add_person(person_id, seen_at)
}

/// TheStreamMgmt.the_stream_addConversation
#[tauri::command]
pub(crate) async fn the_stream_add_conversation<R: Runtime>(
  app: AppHandle<R>,
    conversation_id: i64,
    seen_at: Option<i64>
  
) -> TheStreamEntry {
  app.spireFoundframePlatform().the_stream_add_conversation(conversation_id, seen_at)
}

/// ViewMgmt.view_addView
#[tauri::command]
pub(crate) async fn view_add_view<R: Runtime>(
  app: AppHandle<R>,
    index: i64,
    badge: String,
    label: Option<String>
  
) -> () {
  app.spireFoundframePlatform().view_add_view(index, badge, label)
}

/// ViewMgmt.view_getView
#[tauri::command]
pub(crate) async fn view_get_view<R: Runtime>(
  app: AppHandle<R>,
    id: i64
  
) -> View {
  app.spireFoundframePlatform().view_get_view(id)
}

/// ViewMgmt.view_listViews
#[tauri::command]
pub(crate) async fn view_list_views<R: Runtime>(
  app: AppHandle<R>,
  
) -> Vec<()> {
  app.spireFoundframePlatform().view_list_views()
}

/// ViewMgmt.view_deleteView
#[tauri::command]
pub(crate) async fn view_delete_view<R: Runtime>(
  app: AppHandle<R>,
    id: i64
  
) -> bool {
  app.spireFoundframePlatform().view_delete_view(id)
}

