//! Desktop Platform Implementation - GENERATED by spire-loom
//!
//! On desktop, we initialize o19_foundframe directly and call into it.

use crate::spire::platform::SpireFoundframePlatformTrait;
use crate::spire::error::{Error, Result};
use crate::spire::models::*;
use serde::de::DeserializeOwned;
use tauri::{AppHandle, Manager, Runtime, plugin::PluginApi};

/// Initialize the desktop platform.
pub fn init<R: Runtime, C: DeserializeOwned>(
  app: &AppHandle<R>,
  _api: &PluginApi<R, C>,
) -> Result<DesktopPlatform<R>> {
  DesktopPlatform::new(app.clone())
}

/// Desktop platform implementation.
///
/// Holds the foundframe runtime and provides direct access to all operations.
pub struct DesktopPlatform<R: Runtime> {
  app_handle: AppHandle<R>,
}

impl<R: Runtime> DesktopPlatform<R> {
  fn new(app_handle: AppHandle<R>) -> Result<Self> {
    // TODO: Initialize o19_foundframe here
    Ok(Self { app_handle })
  }

  pub fn app_handle(&self) -> &AppHandle<R> {
    &self.app_handle
  }
}

impl<R: Runtime> SpireFoundframePlatformTrait for DesktopPlatform<R> {
  fn exit(&self, code: i32) {
    self.app_handle.exit(code);
  }

  fn request_permissions(&self) -> Result<NotificationPermissionStatus> {
    Ok(NotificationPermissionStatus {
      status: "granted".into(),
    })
  }

  fn shutdown(&self) -> Result<()> {
    // TODO: Shutdown o19_foundframe
    Ok(())
  }

  fn bookmark_addBookmark(
    &self,
        url: String,
        title: Option<String>,
        notes: Option<String>
    
  ) -> Result<()> {
    // TODO: Implement BookmarkMgmt.bookmark_addBookmark
    Err(Error::Other("Not implemented".into()))
  }

  fn bookmark_getBookmarkByUrl(
    &self,
        pkbUrl: String
    
  ) -> Result<String> {
    // TODO: Implement BookmarkMgmt.bookmark_getBookmarkByUrl
    Err(Error::Other("Not implemented".into()))
  }

  fn bookmark_listBookmarks(
    &self,
        directory: Option<String>
    
  ) -> Result<Vec<String>> {
    // TODO: Implement BookmarkMgmt.bookmark_listBookmarks
    Err(Error::Other("Not implemented".into()))
  }

  fn bookmark_deleteBookmark(
    &self,
        pkbUrl: String
    
  ) -> Result<bool> {
    // TODO: Implement BookmarkMgmt.bookmark_deleteBookmark
    Err(Error::Other("Not implemented".into()))
  }

  fn device_generatePairingCode(
    &self,
    
  ) -> Result<String> {
    // TODO: Implement DeviceMgmt.device_generatePairingCode
    Err(Error::Other("Not implemented".into()))
  }

  fn device_confirmPairing(
    &self,
        deviceId: String,
        code: String
    
  ) -> Result<bool> {
    // TODO: Implement DeviceMgmt.device_confirmPairing
    Err(Error::Other("Not implemented".into()))
  }

  fn device_unpairDevice(
    &self,
        deviceId: String
    
  ) -> Result<()> {
    // TODO: Implement DeviceMgmt.device_unpairDevice
    Err(Error::Other("Not implemented".into()))
  }

  fn device_listPairedDevices(
    &self,
    
  ) -> Result<String> {
    // TODO: Implement DeviceMgmt.device_listPairedDevices
    Err(Error::Other("Not implemented".into()))
  }

  fn device_followDevice(
    &self,
        deviceId: String
    
  ) -> Result<bool> {
    // TODO: Implement DeviceMgmt.device_followDevice
    Err(Error::Other("Not implemented".into()))
  }

  fn device_unfollowDevice(
    &self,
        deviceId: String
    
  ) -> Result<()> {
    // TODO: Implement DeviceMgmt.device_unfollowDevice
    Err(Error::Other("Not implemented".into()))
  }

  fn device_listFollowers(
    &self,
    
  ) -> Result<String> {
    // TODO: Implement DeviceMgmt.device_listFollowers
    Err(Error::Other("Not implemented".into()))
  }

  fn device_isFollowing(
    &self,
        deviceId: String
    
  ) -> Result<bool> {
    // TODO: Implement DeviceMgmt.device_isFollowing
    Err(Error::Other("Not implemented".into()))
  }

}
