// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: node_modules/@o19/spire-loom/machinery/bobbin/tauri/extension.rs.ejs
// Template file: extension.rs.ejs
// To override: Copy this template to loom/bobbin/tauri/extension.rs.ejs
// 
// To modify the generated output, edit the template file above.
//! AppHandle Extension - GENERATED by spire-loom
//!
//! Extension trait for accessing the RustExternalLayer platform from AppHandle.
//!
//! Generated from RustExternalLayer Management definitions.

use tauri::{Manager, Runtime};
use crate::spire::platform::SpireRustExternalLayerPlatformTrait;

/// Extension trait for accessing RustExternalLayer platform.
pub trait SpireRustExternalLayerExt<R: Runtime> {
  /// Access the RustExternalLayer platform implementation.
  fn spireRustExternalLayerPlatform<'a>(&'a self) -> &'a dyn SpireRustExternalLayerPlatformTrait;
}

impl<R: Runtime, T: Manager<R>> SpireRustExternalLayerExt<R> for T {
  fn spireRustExternalLayerPlatform<'a>(&'a self) -> &'a dyn SpireRustExternalLayerPlatformTrait {
    self.state::<crate::spire::SpireRustExternalLayerPlatform>().inner().platform()
  }
}
