//! AppHandle Extension - GENERATED by spire-loom
//!
//! Extension trait for accessing the foundframe platform from AppHandle.
//!
//! Generated from foundframe Management definitions.

use tauri::{Manager, Runtime};
use crate::spire::platform::SpireFoundframePlatformTrait;

/// Extension trait for accessing foundframe platform.
pub trait SpireFoundframeExt<R: Runtime> {
  /// Access the foundframe platform implementation.
  fn spireFoundframePlatform<'a>(&'a self) -> &'a dyn SpireFoundframePlatformTrait;
}

impl<R: Runtime, T: Manager<R>> SpireFoundframeExt<R> for T {
  fn spireFoundframePlatform<'a>(&'a self) -> &'a dyn SpireFoundframePlatformTrait {
    self.state::<crate::spire::SpireFoundframePlatform>().inner().platform()
  }
}
