// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: node_modules/@o19/spire-loom/machinery/bobbin/tauri/models.rs.ejs
// Template file: models.rs.ejs
// To override: Copy this template to loom/bobbin/tauri/models.rs.ejs
// 
// To modify the generated output, edit the template file above.
//! Models - GENERATED by spire-loom
//!
//! Type definitions for foundframe operations.

use serde::{Deserialize, Serialize};

/// Notification permission status.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NotificationPermissionStatus {
  pub status: String,
}

/// Result of adding an entry to the stream.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StreamEntryResult {
  pub id: Option<u64>,
  pub seen_at: u64,
  pub reference: String,
}

/// QR code response for device pairing.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PairingQrResponse {
  pub url: String,
  pub emoji_identity: String,
  pub node_id_hex: String,
}

/// Data from scanning a pairing QR code.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScannedPairingData {
  pub emoji_identity: String,
  pub device_name: String,
  pub node_id_hex: String,
  pub node_id: String,
}

/// Information about a paired device.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PairedDeviceInfo {
  pub node_id: String,
  pub alias: String,
  pub paired: bool,
}
