//! Platform trait - GENERATED by spire-loom
//!
//! This trait abstracts all foundframe operations across platforms.
//! Implementations:
//! - Desktop: Direct o19_foundframe calls
//! - Android: JNI calls to foundframe-android service
//! - iOS: Not implemented (stub)
//!
//! NOTE: This is the GENERATED platform trait. The user-defined Platform trait
//! in src/platform.rs is separate and can have custom methods.

use crate::spire::error::Result;
use crate::spire::models::*;

/// Platform trait abstracts all foundframe operations.
///
/// This is distinct from the user's Platform trait in src/platform.rs.
/// Generated code implements THIS trait, not the user's trait.
///
/// This allows the tauri-plugin to work on different platforms:
/// - Desktop: Direct foundframe integration
/// - Android: JNI calls to foreground service
/// - iOS: Not implemented (stub)
pub trait SpireFoundframePlatformTrait: Send + Sync {
  /// Exit the application cleanly.
  fn exit(&self, code: i32);

  /// Request permissions (notifications, etc).
  fn request_permissions(&self) -> Result<NotificationPermissionStatus>;

  /// Called when the app is shutting down.
  fn shutdown(&self) -> Result<()>;

  /// BookmarkMgmt.bookmark_addBookmark
  fn bookmark_addBookmark(
    &self,
        url: String,
        title: Option<String>,
        notes: Option<String>
    
  ) -> Result<()>;

  /// BookmarkMgmt.bookmark_getBookmarkByUrl
  fn bookmark_getBookmarkByUrl(
    &self,
        pkbUrl: String
    
  ) -> Result<String>;

  /// BookmarkMgmt.bookmark_listBookmarks
  fn bookmark_listBookmarks(
    &self,
        directory: Option<String>
    
  ) -> Result<Vec<String>>;

  /// BookmarkMgmt.bookmark_deleteBookmark
  fn bookmark_deleteBookmark(
    &self,
        pkbUrl: String
    
  ) -> Result<bool>;

  /// DeviceMgmt.device_generatePairingCode
  fn device_generatePairingCode(
    &self,
    
  ) -> Result<String>;

  /// DeviceMgmt.device_confirmPairing
  fn device_confirmPairing(
    &self,
        deviceId: String,
        code: String
    
  ) -> Result<bool>;

  /// DeviceMgmt.device_unpairDevice
  fn device_unpairDevice(
    &self,
        deviceId: String
    
  ) -> Result<()>;

  /// DeviceMgmt.device_listPairedDevices
  fn device_listPairedDevices(
    &self,
    
  ) -> Result<String>;

  /// DeviceMgmt.device_followDevice
  fn device_followDevice(
    &self,
        deviceId: String
    
  ) -> Result<bool>;

  /// DeviceMgmt.device_unfollowDevice
  fn device_unfollowDevice(
    &self,
        deviceId: String
    
  ) -> Result<()>;

  /// DeviceMgmt.device_listFollowers
  fn device_listFollowers(
    &self,
    
  ) -> Result<String>;

  /// DeviceMgmt.device_isFollowing
  fn device_isFollowing(
    &self,
        deviceId: String
    
  ) -> Result<bool>;

}
