//! Platform trait - GENERATED by spire-loom
//!
//! This trait abstracts all foundframe operations across platforms.
//! Implementations:
//! - Desktop: Direct o19_foundframe calls
//! - Android: JNI calls to foundframe-android service
//! - iOS: Not implemented (stub)
//!
//! NOTE: This is the GENERATED platform trait. The user-defined Platform trait
//! in src/platform.rs is separate and can have custom methods.

use crate::spire::error::Result;
use crate::spire::models::*;

/// Platform trait abstracts all foundframe operations.
///
/// This is distinct from the user's Platform trait in src/platform.rs.
/// Generated code implements THIS trait, not the user's trait.
///
/// This allows the tauri-plugin to work on different platforms:
/// - Desktop: Direct foundframe integration
/// - Android: JNI calls to foreground service
/// - iOS: Not implemented (stub)
pub trait SpireFoundframePlatformTrait: Send + Sync {
  /// Exit the application cleanly.
  fn exit(&self, code: i32);

  /// Request permissions (notifications, etc).
  fn request_permissions(&self) -> Result<NotificationPermissionStatus>;

  /// Called when the app is shutting down.
  fn shutdown(&self) -> Result<()>;

  /// BookmarkMgmt.addBookmark
  fn add_bookmark(
    &self,
        url: String,
        title: Option<String>,
        notes: Option<String>
    
  ) -> Result<String>;

  /// BookmarkMgmt.getBookmark
  fn get_bookmark(
    &self,
        pkbUrl: String
    
  ) -> Result<String>;

  /// BookmarkMgmt.listBookmarks
  fn list_bookmarks(
    &self,
        directory: Option<String>
    
  ) -> Result<Vec<String>>;

  /// BookmarkMgmt.deleteBookmark
  fn delete_bookmark(
    &self,
        pkbUrl: String
    
  ) -> Result<bool>;

  /// DeviceMgmt.generatePairingCode
  fn generate_pairing_code(
    &self,
    
  ) -> Result<String>;

  /// DeviceMgmt.confirmPairing
  fn confirm_pairing(
    &self,
        deviceId: String,
        code: String
    
  ) -> Result<bool>;

  /// DeviceMgmt.unpairDevice
  fn unpair_device(
    &self,
        deviceId: String
    
  ) -> Result<()>;

  /// DeviceMgmt.listPairedDevices
  fn list_paired_devices(
    &self,
    
  ) -> Result<Vec<String>>;

  /// DeviceMgmt.followDevice
  fn follow_device(
    &self,
        deviceId: String
    
  ) -> Result<bool>;

  /// DeviceMgmt.unfollowDevice
  fn unfollow_device(
    &self,
        deviceId: String
    
  ) -> Result<()>;

  /// DeviceMgmt.listFollowers
  fn list_followers(
    &self,
    
  ) -> Result<Vec<String>>;

  /// DeviceMgmt.isFollowing
  fn is_following(
    &self,
        deviceId: String
    
  ) -> Result<bool>;

  /// EventMgmt.subscribeEvents
  fn subscribe_events(
    &self,
        callback: String
    
  ) -> Result<()>;

  /// EventMgmt.unsubscribeEvents
  fn unsubscribe_events(
    &self,
        callback: String
    
  ) -> Result<()>;

  /// EventMgmt.supportsEvents
  fn supports_events(
    &self,
    
  ) -> Result<bool>;

}
