/**
 * The Refinement System
 *
 * "Rings are refined, not just defined."
 *
 * Refinements are modifiers attached to rings in WARP.ts.
 * They bridge software concepts (Prisma, ORMs) with the loom's weaving machinery.
 *
 * A refinement:
 * 1. Attaches to a ring via @loom.refine.* decorator
 * 2. Provides capabilities (autocomplete, SQL generation) to loom/*.ts
 * 3. Triggers compaction during weaving
 */

import type { Ring } from '../spiral/ring.js';

/** Context passed during weaving */
export interface WeavingContext {
  /** The workspace root */
  workspaceRoot: string;

  /** The midstage path for this refinement */
  midstagePath: string;

  /** The output path for generated files */
  outputPath: string;

  /** The parsed Drizzle schema */
  schema: any; // ParsedSchema

  /** Logger for refinement operations */
  log: (msg: string) => void;
}

/** Result of refinement during weaving */
export interface RefinementResult {
  /** Files generated by this refinement */
  generatedFiles: string[];

  /** Any errors that occurred */
  errors: string[];

  /** Warnings to report */
  warnings: string[];
}

/**
 * Refinement Provider Interface
 *
 * Implement this to create a new refinement (Prisma, Drizzle, etc.)
 */
export interface RefinementProvider<TConfig = unknown> {
  /** Unique name of this refinement */
  name: string;

  /** Configuration provided at definition time */
  config: TConfig;

  /** Called during loom dressing to set up the provider */
  initialize(): Promise<void>;

  /** Called during weaving to refine a ring */
  refine(ring: Ring, context: WeavingContext): Promise<RefinementResult>;

  /** Get the ORM client for autocomplete in loom files */
  getClient?(): Promise<unknown>;

  /** Capture SQL from a query execution */
  captureSQL?<T>(queryFn: (client: unknown) => Promise<T>): Promise<{
    sql: string;
    params: any[];
    result: T;
  }>;
}

/**
 * Metadata attached to a ring by a refinement decorator.
 */
export interface RefinementMetadata {
  /** The refinement provider instance */
  provider: RefinementProvider;

  /** When the refinement was attached */
  attachedAt: Date;
}

/**
 * Symbol for storing refinement metadata on rings.
 */
export const REFINEMENT_KEY = Symbol('loom:refinement');
