/**
 * Tauri Android Commands Treadle
 *
 * Generates Kotlin code for foundframe-tauri Android plugin integration.
 *
 * Strategy:
 * 1. Generate FoundframeRadicleClient.kt in spire/ (AIDL service client)
 * 2. Generate FoundframeCommandProvider.kt in spire/ (@Command handlers)
 * 3. Use declarative hookups (APP-006 KotlinHookup) to integrate with ApiPlugin.kt
 *
 * Matrix match: (TauriSpiraler, AndroidSpiraler) → Tauri Android bridge
 *
 * > *"The treadle bridges the surface to the spiral."*
 */

import {
  defineTreadle,
  generateFromTreadle,
  addAidlTypesToMethods
} from '@o19/spire-loom/machinery/treadle-kit';
import { addManagementPrefix } from '@o19/spire-loom/machinery/sley';


// ============================================================================
// Treadle Definition
// ============================================================================

export const tauriAndroidCommandsTreadle = defineTreadle({
  name: 'tauri-android-commands',

  // Tieup treadle - no matches needed, invoked directly via .tieup()
  // All configuration comes from warpData

  // Method filtering and transformation
  methods: {
    filter: 'platform',
    pipeline: [addManagementPrefix()]
  },

  // Add AIDL types for Kotlin type compatibility
  transformMethods: (methods) => {
    return addAidlTypesToMethods(methods);
  },

  // Template data - all from warpData, no context needed
  data: (context) => {
    const warpData = (context.config || {}) as {
      servicePackage?: string;
      serviceClient?: string;
      interfaceName?: string;
    };

    const tauriPackageName = warpData.servicePackage || 'ty.circulari.o19.ff';

    return {
      servicePackage: warpData.servicePackage || 'ty.circulari.o19',
      serviceClient: warpData.serviceClient || 'FoundframeRadicleClient',
      interfaceName: warpData.interfaceName || 'IFoundframeRadicle',
      packageName: tauriPackageName,
      packagePath: tauriPackageName.replace(/\./g, '/'),
      permission: `${tauriPackageName}.ACCESS_FOUNDFRAME`
    };
  },

  // Output files
  outputs: [
    // Service Client - binds to AIDL service
    {
      template: 'tauri/foundframe_radicle_client.kt.ejs',
      path: 'android/java/{packagePath}/service/{serviceClient}.kt',
      language: 'kotlin'
    },
    // Command Provider - contains all command handlers
    {
      template: 'tauri/foundframe_command_provider.kt.ejs',
      path: 'android/java/{packagePath}/FoundframeCommandProvider.kt',
      language: 'kotlin'
    }
  ],

  // Declarative Kotlin hookups (APP-006 style)
  // Type is inferred from .kt path suffix
  hookups: [
    {
      path: 'android/src/main/java/ApiPlugin.kt',

      // Import statements
      imports: ['import ty.circulari.o19.ff.FoundframeCommandProvider'],

      // Class modifications for ApiPlugin
      classes: {
        ApiPlugin: {
          // Add field for command provider
          fields: ['private var foundframeCommands: FoundframeCommandProvider? = null'],

          // Modify existing methods
          methods: {
            load: {
              append: [
                '// Initialize Foundframe commands (generated by spire-loom)',
                'foundframeCommands = FoundframeCommandProvider(activity)',
                'foundframeCommands?.initialize()'
              ]
            },
            onDestroy: {
              prepend: ['// Cleanup Foundframe commands', 'foundframeCommands?.cleanup()']
            }
          }
        }
      }
    }
  ]
});

// ============================================================================
// Exports
// ============================================================================

export type TauriAndroidGenerationOptions = {
  servicePackage: string;
  serviceClient: string;
};

export const generateTauriAndroidCommands = generateFromTreadle(tauriAndroidCommandsTreadle);
