package ty.circulari.o19.ff

import android.content.Context
import android.Manifest
import android.app.Activity
import android.content.pm.PackageManager
import android.os.Build
import androidx.core.app.ActivityCompat
import androidx.core.content.ContextCompat
import app.tauri.PermissionState
import app.tauri.annotation.ActivityCallback
import app.tauri.annotation.Command
import app.tauri.annotation.InvokeArg
import app.tauri.annotation.Permission
import app.tauri.annotation.PermissionCallback
import app.tauri.annotation.TauriPlugin
import app.tauri.plugin.Plugin
import app.tauri.plugin.Invoke
import app.tauri.plugin.JSObject
import ty.circulari.o19.CameraPlugin
import ty.circulari.o19.CameraMode
import ty.circulari.o19.service.FoundframeRadicleClient

import ty.circulari.o19.ff.FoundframeCommandProvider

@InvokeArg
class CameraOptions {
  var mode: String? = "preview"
  var cameraDirection: String? = "back"
}

@TauriPlugin(
  permissions = [
    Permission(strings = [Manifest.permission.CAMERA], alias = "camera")
  ]
)

  // We define this as an external function. 
  // It expects to find a C/Rust symbol named
  // Java_ty_circulari_o19_ffi_ApiPlugin_initRustlsPlatformVerifier
  external fun initRustlsPlatformVerifier(context: Context)

class ApiPlugin(private val activity: Activity) : Plugin(activity) {    private var foundframeCommands: FoundframeCommandProvider? = null

  
  private var cameraPlugin: CameraPlugin? = null
  
  override fun load(webView: android.webkit.WebView) {
    super.load(webView)
    
    // Start the FoundframeRadicle background service (runs in :foundframe process)
    // This must happen before Rust code tries to connect via binder
    android.util.Log.i("O19-ANDROID", "[ApiPlugin] Starting FoundframeRadicleService...")
    FoundframeRadicleClient(activity).ensureStarted("deardiary")
    
    // Initialize camera plugin with same activity and webview
    cameraPlugin = CameraPlugin(activity)
    cameraPlugin?.load(webView)
        // Initialize Foundframe commands (generated by spire-loom)
        foundframeCommands = FoundframeCommandProvider(activity)
        foundframeCommands?.initialize()
        // Initialize Foundframe commands (generated by spire-loom)
        foundframeCommands = FoundframeCommandProvider(activity)
        foundframeCommands?.initialize()
}
  
  // ============================================================================
  // Notification Permissions
  // ============================================================================
  
  @Command
  override fun requestPermissions(invoke: Invoke){
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.TIRAMISU) {
      val ret = JSObject()
      ret.put("status", getPermissionState("postNotification"))
      invoke.resolve(ret)
    }
    else {
      if (getPermissionState("postNotification") !== PermissionState.GRANTED) {
        requestPermissionForAlias("postNotification", invoke, "requestPermissionsCallback")
      }
    }
  }

  @PermissionCallback
  fun requestPermissionsCallback(invoke: Invoke){
    val ret = JSObject()
    ret.put("status", getPermissionState("postNotification"))
    invoke.resolve(ret)
  }
  
  // ============================================================================
  // Camera Commands
  // ============================================================================
  
  @Command
  fun startCamera(invoke: Invoke) {
    val args = invoke.parseArgs(CameraOptions::class.java)
    val mode = when (args.mode) {
      "qr" -> CameraMode.QR_SCAN
      "photo" -> CameraMode.PHOTO_CAPTURE
      else -> CameraMode.PREVIEW
    }
    
    cameraPlugin?.startCameraInternal(invoke, mode, args.cameraDirection ?: "back")
  }
  
  @Command
  fun stopCamera(invoke: Invoke) {
    cameraPlugin?.stopCameraInternal(invoke)
  }
  
  @Command
  fun setCameraMode(invoke: Invoke) {
    val args = invoke.parseArgs(CameraOptions::class.java)
    val mode = when (args.mode) {
      "qr" -> CameraMode.QR_SCAN
      "photo" -> CameraMode.PHOTO_CAPTURE
      else -> CameraMode.PREVIEW
    }
    
    cameraPlugin?.setCameraModeInternal(invoke, mode, args.cameraDirection ?: "back")
  }
  
  @Command
  fun capturePhoto(invoke: Invoke) {
    cameraPlugin?.capturePhotoInternal(invoke)
  }
  
  @Command
  fun isCameraActive(invoke: Invoke) {
    cameraPlugin?.isCameraActiveInternal(invoke)
  }
  
  // ============================================================================
  // Camera Permissions (handled directly by ApiPlugin since it's a Tauri Plugin)
  // ============================================================================
  
  private val CAMERA_PERMISSION_REQUEST_CODE = 1001
  private var pendingCameraPermissionInvoke: Invoke? = null

  @Command
  fun requestCameraPermissions(invoke: Invoke) {
    android.util.Log.d("O19-ANDROID", "Requesting camera permission...")
    
    when {
      ContextCompat.checkSelfPermission(activity, Manifest.permission.CAMERA) == PackageManager.PERMISSION_GRANTED -> {
        android.util.Log.d("O19-ANDROID", "Camera permission already granted")
        val result = JSObject().apply {
          put("camera", "granted")
          put("granted", true)
        }
        invoke.resolve(result)
      }
      ActivityCompat.shouldShowRequestPermissionRationale(activity, Manifest.permission.CAMERA) -> {
        // User denied before but didn't check "Don't ask again"
        android.util.Log.d("O19-ANDROID", "Showing permission rationale, then requesting...")
        pendingCameraPermissionInvoke = invoke
        ActivityCompat.requestPermissions(activity, arrayOf(Manifest.permission.CAMERA), CAMERA_PERMISSION_REQUEST_CODE)
      }
      else -> {
        // First time request
        android.util.Log.d("O19-ANDROID", "First time camera permission request...")
        pendingCameraPermissionInvoke = invoke
        ActivityCompat.requestPermissions(activity, arrayOf(Manifest.permission.CAMERA), CAMERA_PERMISSION_REQUEST_CODE)
      }
    }
  }

  @Command
  fun checkCameraPermissions(invoke: Invoke) {
    val granted = ContextCompat.checkSelfPermission(activity, Manifest.permission.CAMERA) == PackageManager.PERMISSION_GRANTED
    android.util.Log.d("O19-ANDROID", "Camera permission check: granted=$granted")
    
    val result = JSObject().apply {
      put("camera", if (granted) "granted" else "prompt")
    }
    invoke.resolve(result)
  }

  // ============================================================================
  // Permission Result Handling
  // ============================================================================
  
  @Suppress("UNUSED_PARAMETER")
  @ActivityCallback
  fun onRequestPermissionsResult(requestCode: Int, permissions: Array<out String>, grantResults: IntArray) {
    android.util.Log.d("O19-ANDROID", "onRequestPermissionsResult: code=$requestCode")
    
    if (requestCode == CAMERA_PERMISSION_REQUEST_CODE) {
      val granted = grantResults.isNotEmpty() && grantResults[0] == PackageManager.PERMISSION_GRANTED
      android.util.Log.d("O19-ANDROID", "Camera permission result: granted=$granted")
      
      pendingCameraPermissionInvoke?.let { invoke ->
        val result = JSObject().apply {
          put("camera", if (granted) "granted" else "denied")
          put("granted", granted)
        }
        invoke.resolve(result)
        pendingCameraPermissionInvoke = null
      }
    }
  }
  
  // ============================================================================
  // Cleanup
  // ============================================================================
  
  override fun onDestroy() {        // Cleanup Foundframe commands
        foundframeCommands?.cleanup()
        // Cleanup Foundframe commands
        foundframeCommands?.cleanup()

    cameraPlugin?.onDestroy()
    super.onDestroy()
  }
}
