// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: tauri/commands.ts.ejs
// Template file: commands.ts.ejs
// This is a custom template in your workspace
// 
// To modify the generated output, edit the template file above.
// GENERATED BY tauri-adaptor Treadle - Do not edit
// Tauri command handlers for Conversation

import { invoke } from '@tauri-apps/api/core';
import type { Conversation, CreateConversation, UpdateConversation } from '../domain/entities/conversation.js';

/**
 * Create a new conversation
 */
export async function createConversation(data: CreateConversation): Promise<Conversation> {
  return await invoke<Conversation>('create_conversation', { data });
}

/**
 * Update conversation
 */
export async function updateConversation(id: number, data: UpdateConversation): Promise<void> {
  return await invoke<void>('update_conversation', { id, data });
}

/**
 * Delete conversation
 */
export async function deleteConversation(id: number): Promise<void> {
  return await invoke<void>('delete_conversation', { id });
}

