// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: tauri/commands.ts.ejs
// Template file: commands.ts.ejs
// This is a custom template in your workspace
// 
// To modify the generated output, edit the template file above.
// GENERATED BY tauri-adaptor Treadle - Do not edit
// Tauri command handlers for Person

import { invoke } from '@tauri-apps/api/core';
import type { Person, CreatePerson, UpdatePerson } from '../domain/entities/person.js';

/**
 * Create a new person
 */
export async function createPerson(data: CreatePerson): Promise<Person> {
  return await invoke<Person>('create_person', { data });
}

/**
 * Update person
 */
export async function updatePerson(id: number, data: UpdatePerson): Promise<void> {
  return await invoke<void>('update_person', { id, data });
}

/**
 * Delete person
 */
export async function deletePerson(id: number): Promise<void> {
  return await invoke<void>('delete_person', { id });
}

