// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: node_modules/@o19/spire-loom/machinery/bobbin/android/aidl_interface.aidl.ejs
// Template file: aidl_interface.aidl.ejs
// To override: Copy this template to loom/bobbin/android/aidl_interface.aidl.ejs
// 
// To modify the generated output, edit the template file above.
// IAndroidRadicle.aidl
// Generated AIDL interface for android service
//
// This interface defines the contract between the Android service (running in
// :foundframe process) and client applications (running in their own processes).
//
// The NDK aidl tool generates:
// - IAndroidRadicle.java (interface)
// - IAndroidRadicle.Stub (binder implementation base class)
// - IAndroidRadicle.Default (proxy for client-side)

package ty.circulari.o19;

import ty.circulari.o19.IEventCallback;

/**
 * IAndroidRadicle defines cross-process API for android.
 *
 * Methods are called via Binder IPC. All parameters are 'in' (client→service).
 * Return values are marshalled back via Binder.
 *
 * Security: Implementations should verify caller has:
 *   ty.circulari.o19.ACCESS_FOUNDFRAME permission (signature level)
 */
interface IAndroidRadicle {

    /**
     * BookmarkMgmt.bookmark_addBookmark
     * @param url url
     * @param title title
     * @param notes notes
     * @return void
     * @throws RemoteException if IPC fails
     */
    void bookmark_add_bookmark(in String url, in String title, in String notes);

    /**
     * BookmarkMgmt.bookmark_getBookmarkByUrl
     * @param pkbUrl pkbUrl
     * @return String
     * @throws RemoteException if IPC fails
     */
    String bookmark_get_bookmark_by_url(in String pkbUrl);

    /**
     * BookmarkMgmt.bookmark_listBookmarks
     * @param directory directory
     * @return String[]
     * @throws RemoteException if IPC fails
     */
    String[] bookmark_list_bookmarks(in String directory);

    /**
     * BookmarkMgmt.bookmark_deleteBookmark
     * @param pkbUrl pkbUrl
     * @return boolean
     * @throws RemoteException if IPC fails
     */
    boolean bookmark_delete_bookmark(in String pkbUrl);

    /**
     * ConversationMgmt.conversation_addConversation
     * @param conversationId conversationId
     * @param title title
     * @param participants participants
     * @return void
     * @throws RemoteException if IPC fails
     */
    void conversation_add_conversation(in String conversationId, in String title, in String participants);

    /**
     * ConversationMgmt.conversation_getConversation
     * @param conversationId conversationId
     * @return String
     * @throws RemoteException if IPC fails
     */
    String conversation_get_conversation(in String conversationId);

    /**
     * ConversationMgmt.conversation_listConversations
     * @return String[]
     * @throws RemoteException if IPC fails
     */
    String[] conversation_list_conversations();

    /**
     * ConversationMgmt.conversation_updateConversation
     * @param conversationId conversationId
     * @param title title
     * @param participants participants
     * @return boolean
     * @throws RemoteException if IPC fails
     */
    boolean conversation_update_conversation(in String conversationId, in String title, in String participants);

    /**
     * ConversationMgmt.conversation_deleteConversation
     * @param conversationId conversationId
     * @return boolean
     * @throws RemoteException if IPC fails
     */
    boolean conversation_delete_conversation(in String conversationId);

    /**
     * ConversationMgmt.conversation_addParticipant
     * @param conversationId conversationId
     * @param personHandle personHandle
     * @param role role
     * @return boolean
     * @throws RemoteException if IPC fails
     */
    boolean conversation_add_participant(in String conversationId, in String personHandle, in String role);

    /**
     * ConversationMgmt.conversation_removeParticipant
     * @param conversationId conversationId
     * @param personHandle personHandle
     * @return boolean
     * @throws RemoteException if IPC fails
     */
    boolean conversation_remove_participant(in String conversationId, in String personHandle);

    /**
     * ConversationMgmt.conversation_listParticipants
     * @param conversationId conversationId
     * @return String[]
     * @throws RemoteException if IPC fails
     */
    String[] conversation_list_participants(in String conversationId);

    /**
     * ConversationMgmt.conversation_addConversationMedia
     * @param conversationId conversationId
     * @param mediaUrl mediaUrl
     * @param context context
     * @return boolean
     * @throws RemoteException if IPC fails
     */
    boolean conversation_add_conversation_media(in String conversationId, in String mediaUrl, in String context);

    /**
     * ConversationMgmt.conversation_removeConversationMedia
     * @param conversationId conversationId
     * @param mediaUrl mediaUrl
     * @return boolean
     * @throws RemoteException if IPC fails
     */
    boolean conversation_remove_conversation_media(in String conversationId, in String mediaUrl);

    /**
     * ConversationMgmt.conversation_listConversationMedia
     * @param conversationId conversationId
     * @return String[]
     * @throws RemoteException if IPC fails
     */
    String[] conversation_list_conversation_media(in String conversationId);

    /**
     * DeviceMgmt.device_generatePairingCode
     * @return String
     * @throws RemoteException if IPC fails
     */
    String device_generate_pairing_code();

    /**
     * DeviceMgmt.device_confirmPairing
     * @param deviceId deviceId
     * @param code code
     * @return boolean
     * @throws RemoteException if IPC fails
     */
    boolean device_confirm_pairing(in String deviceId, in String code);

    /**
     * DeviceMgmt.device_unpairDevice
     * @param deviceId deviceId
     * @return void
     * @throws RemoteException if IPC fails
     */
    void device_unpair_device(in String deviceId);

    /**
     * DeviceMgmt.device_listPairedDevices
     * @return String[]
     * @throws RemoteException if IPC fails
     */
    String[] device_list_paired_devices();

    /**
     * DeviceMgmt.device_followDevice
     * @param deviceId deviceId
     * @return boolean
     * @throws RemoteException if IPC fails
     */
    boolean device_follow_device(in String deviceId);

    /**
     * DeviceMgmt.device_unfollowDevice
     * @param deviceId deviceId
     * @return void
     * @throws RemoteException if IPC fails
     */
    void device_unfollow_device(in String deviceId);

    /**
     * DeviceMgmt.device_listFollowers
     * @return String[]
     * @throws RemoteException if IPC fails
     */
    String[] device_list_followers();

    /**
     * DeviceMgmt.device_isFollowing
     * @param deviceId deviceId
     * @return boolean
     * @throws RemoteException if IPC fails
     */
    boolean device_is_following(in String deviceId);

    /**
     * MediaMgmt.media_addMediaLink
     * @param url url
     * @param title title
     * @param mimeType mimeType
     * @param directory directory
     * @return void
     * @throws RemoteException if IPC fails
     */
    void media_add_media_link(in String url, in String title, in String mimeType, in String directory);

    /**
     * MediaMgmt.media_addMediaFile
     * @param filePath filePath
     * @param title title
     * @return void
     * @throws RemoteException if IPC fails
     */
    void media_add_media_file(in String filePath, in String title);

    /**
     * MediaMgmt.media_getMediaByUrl
     * @param url url
     * @return String
     * @throws RemoteException if IPC fails
     */
    String media_get_media_by_url(in String url);

    /**
     * MediaMgmt.media_listMedia
     * @param directory directory
     * @return String[]
     * @throws RemoteException if IPC fails
     */
    String[] media_list_media(in String directory);

    /**
     * MediaMgmt.media_deleteMedia
     * @param pkbUrl pkbUrl
     * @return boolean
     * @throws RemoteException if IPC fails
     */
    boolean media_delete_media(in String pkbUrl);

    /**
     * PersonMgmt.person_addPerson
     * @param displayName displayName
     * @param handle handle
     * @param metadata metadata
     * @return void
     * @throws RemoteException if IPC fails
     */
    void person_add_person(in String displayName, in String handle, in String metadata);

    /**
     * PersonMgmt.person_getPersonByHandle
     * @param handle handle
     * @return String
     * @throws RemoteException if IPC fails
     */
    String person_get_person_by_handle(in String handle);

    /**
     * PersonMgmt.person_listPeople
     * @return String[]
     * @throws RemoteException if IPC fails
     */
    String[] person_list_people();

    /**
     * PersonMgmt.person_updatePerson
     * @param handle handle
     * @param displayName displayName
     * @param metadata metadata
     * @return boolean
     * @throws RemoteException if IPC fails
     */
    boolean person_update_person(in String handle, in String displayName, in String metadata);

    /**
     * PersonMgmt.person_deletePerson
     * @param handle handle
     * @return boolean
     * @throws RemoteException if IPC fails
     */
    boolean person_delete_person(in String handle);

    /**
     * PostMgmt.post_addPost
     * @param content content
     * @param title title
     * @param tags tags
     * @return void
     * @throws RemoteException if IPC fails
     */
    void post_add_post(in String content, in String title, in String tags);

    /**
     * PostMgmt.post_getPostByUrl
     * @param pkbUrl pkbUrl
     * @return String
     * @throws RemoteException if IPC fails
     */
    String post_get_post_by_url(in String pkbUrl);

    /**
     * PostMgmt.post_listPosts
     * @param directory directory
     * @return String[]
     * @throws RemoteException if IPC fails
     */
    String[] post_list_posts(in String directory);

    /**
     * PostMgmt.post_updatePost
     * @param pkbUrl pkbUrl
     * @param content content
     * @param title title
     * @return boolean
     * @throws RemoteException if IPC fails
     */
    boolean post_update_post(in String pkbUrl, in String content, in String title);

    /**
     * PostMgmt.post_deletePost
     * @param pkbUrl pkbUrl
     * @return boolean
     * @throws RemoteException if IPC fails
     */
    boolean post_delete_post(in String pkbUrl);

}
