// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/packages/spire-loom/machinery/bobbin/android/aidl_callback.aidl.mejs
// Template file: aidl_callback.aidl.mejs
// To override: Copy this template to loom/bobbin/android/aidl_callback.aidl.mejs
// 
// To modify the generated output, edit the template file above.
// IEventCallback.aidl
// Generated AIDL callback interface for foundframe service events
//
// This interface allows the service to push events to clients asynchronously.
// Clients implement this interface and pass it to subscribe methods.

package ty.circulari.o19;

/**
 * IEventCallback receives asynchronous events from foundframe service.
 *
 * All methods are one-way (oneway) - they don't block the service.
 * Clients should handle these callbacks quickly to avoid ANR.
 */
oneway interface IEventCallback {
    /**
     * Called when an entity changes in the service.
     *
     * @param entityType The type of entity that changed (e.g., "Bookmark", "Post")
     * @param entityId The unique identifier of the changed entity
     * @param changeType The type of change: "created", "updated", or "deleted"
     */
    void onEntityChanged(String entityType, String entityId, String changeType);

    /**
     * Called when the service status changes.
     *
     * @param status The new service status: "ready", "syncing", "error"
     * @param message Additional status information
     */
    void onStatusChanged(String status, String message);

    /**
     * Called when a background operation completes.
     *
     * @param operationId The unique ID of the completed operation
     * @param success Whether the operation succeeded
     * @param result The operation result (JSON string) or error message
     */
    void onOperationComplete(String operationId, boolean success, String result);
}
