// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/packages/spire-loom/machinery/bobbin/android/aidl_interface.aidl.mejs
// Template file: aidl_interface.aidl.mejs
// To override: Copy this template to loom/bobbin/android/aidl_interface.aidl.mejs
// 
// To modify the generated output, edit the template file above.
// IRustExternalLayerRadicle.aidl
// Generated AIDL interface for RustExternalLayer service
//
// This interface defines the contract between the Android service (running in
// :foundframe process) and client applications (running in their own processes).
//
// The NDK aidl tool generates:
// - IRustExternalLayerRadicle.java (interface)
// - IRustExternalLayerRadicle.Stub (binder implementation base class)
// - IRustExternalLayerRadicle.Default (proxy for client-side)

package ty.circulari.o19;

import ty.circulari.o19.IEventCallback;

/**
 * IRustExternalLayerRadicle defines cross-process API for RustExternalLayer.
 *
 * Methods are called via Binder IPC. All parameters are 'in' (client→service).
 * Return values are marshalled back via Binder.
 *
 * Security: Implementations should verify caller has:
 *   ty.circulari.o19.ACCESS_FOUNDFRAME permission (signature level)
 */
interface IRustExternalLayerRadicle {

    /**
     * BookmarkMgmt.bookmark_addBookmark
     * @param url url
     * @param title title
     * @param notes notes
     * @return Unit
     * @throws RemoteException if IPC fails
     */
    Unit bookmarkAddBookmark(in String url, in String title, in String notes);

    /**
     * BookmarkMgmt.bookmark_getBookmark
     * @param id id
     * @return Bookmark
     * @throws RemoteException if IPC fails
     */
    Bookmark bookmarkGetBookmark(in Int id);

    /**
     * BookmarkMgmt.bookmark_getBookmarkByUri
     * @param uri uri
     * @return Bookmark
     * @throws RemoteException if IPC fails
     */
    Bookmark bookmarkGetBookmarkByUri(in String uri);

    /**
     * BookmarkMgmt.bookmark_listBookmarks
     * @param limit limit
     * @param offset offset
     * @param filter filter
     * @return List<Bookmark>
     * @throws RemoteException if IPC fails
     */
    List<Bookmark> bookmarkListBookmarks(in Int limit, in Int offset, in BookmarkFilter filter);

    /**
     * BookmarkMgmt.bookmark_updateBookmark
     * @param id id
     * @param title title
     * @param notes notes
     * @return Boolean
     * @throws RemoteException if IPC fails
     */
    Boolean bookmarkUpdateBookmark(in Int id, in String title, in String notes);

    /**
     * BookmarkMgmt.bookmark_deleteBookmark
     * @param id id
     * @return Boolean
     * @throws RemoteException if IPC fails
     */
    Boolean bookmarkDeleteBookmark(in Int id);

    /**
     * ConversationMgmt.conversation_addConversation
     * @param content content
     * @param captureTime captureTime
     * @param title title
     * @param sourceUrl sourceUrl
     * @return Unit
     * @throws RemoteException if IPC fails
     */
    Unit conversationAddConversation(in List<ConversationEntry> content, in String captureTime, in String title, in String sourceUrl);

    /**
     * ConversationMgmt.conversation_getConversation
     * @param id id
     * @return Conversation
     * @throws RemoteException if IPC fails
     */
    Conversation conversationGetConversation(in Int id);

    /**
     * ConversationMgmt.conversation_listConversations
     * @param limit limit
     * @param offset offset
     * @param filter filter
     * @return List<Conversation>
     * @throws RemoteException if IPC fails
     */
    List<Conversation> conversationListConversations(in Int limit, in Int offset, in ConversationFilter filter);

    /**
     * ConversationMgmt.conversation_updateConversation
     * @param id id
     * @param title title
     * @param content content
     * @return Boolean
     * @throws RemoteException if IPC fails
     */
    Boolean conversationUpdateConversation(in Int id, in String title, in List<ConversationEntry> content);

    /**
     * ConversationMgmt.conversation_deleteConversation
     * @param id id
     * @return Boolean
     * @throws RemoteException if IPC fails
     */
    Boolean conversationDeleteConversation(in Int id);

    /**
     * ConversationMgmt.conversation_addParticipant
     * @param conversationId conversationId
     * @param personId personId
     * @param role role
     * @return Boolean
     * @throws RemoteException if IPC fails
     */
    Boolean conversationAddParticipant(in Int conversationId, in Int personId, in String role);

    /**
     * ConversationMgmt.conversation_removeParticipant
     * @param conversationId conversationId
     * @param personId personId
     * @return Boolean
     * @throws RemoteException if IPC fails
     */
    Boolean conversationRemoveParticipant(in Int conversationId, in Int personId);

    /**
     * ConversationMgmt.conversation_listParticipants
     * @param conversationId conversationId
     * @return List<Int>
     * @throws RemoteException if IPC fails
     */
    List<Int> conversationListParticipants(in Int conversationId);

    /**
     * ConversationMgmt.conversation_addConversationMedia
     * @param conversationId conversationId
     * @param mediaId mediaId
     * @param context context
     * @return Boolean
     * @throws RemoteException if IPC fails
     */
    Boolean conversationAddConversationMedia(in Int conversationId, in Int mediaId, in Record<string, unknown> context);

    /**
     * ConversationMgmt.conversation_removeConversationMedia
     * @param conversationId conversationId
     * @param mediaId mediaId
     * @return Boolean
     * @throws RemoteException if IPC fails
     */
    Boolean conversationRemoveConversationMedia(in Int conversationId, in Int mediaId);

    /**
     * ConversationMgmt.conversation_listConversationMedia
     * @param conversationId conversationId
     * @return List<Int>
     * @throws RemoteException if IPC fails
     */
    List<Int> conversationListConversationMedia(in Int conversationId);

    /**
     * DeviceMgmt.device_generatePairingCode
     * @return String
     * @throws RemoteException if IPC fails
     */
    String deviceGeneratePairingCode();

    /**
     * DeviceMgmt.device_confirmPairing
     * @param deviceId deviceId
     * @param code code
     * @return Boolean
     * @throws RemoteException if IPC fails
     */
    Boolean deviceConfirmPairing(in String deviceId, in String code);

    /**
     * DeviceMgmt.device_unpairDevice
     * @param deviceId deviceId
     * @return Unit
     * @throws RemoteException if IPC fails
     */
    Unit deviceUnpairDevice(in String deviceId);

    /**
     * DeviceMgmt.device_listPairedDevices
     * @return List<String>
     * @throws RemoteException if IPC fails
     */
    List<String> deviceListPairedDevices();

    /**
     * DeviceMgmt.device_followDevice
     * @param deviceId deviceId
     * @return Boolean
     * @throws RemoteException if IPC fails
     */
    Boolean deviceFollowDevice(in String deviceId);

    /**
     * DeviceMgmt.device_unfollowDevice
     * @param deviceId deviceId
     * @return Unit
     * @throws RemoteException if IPC fails
     */
    Unit deviceUnfollowDevice(in String deviceId);

    /**
     * DeviceMgmt.device_listFollowers
     * @return List<String>
     * @throws RemoteException if IPC fails
     */
    List<String> deviceListFollowers();

    /**
     * DeviceMgmt.device_isFollowing
     * @param deviceId deviceId
     * @return Boolean
     * @throws RemoteException if IPC fails
     */
    Boolean deviceIsFollowing(in String deviceId);

    /**
     * MediaMgmt.media_getMedia
     * @param id id
     * @return Media
     * @throws RemoteException if IPC fails
     */
    Media mediaGetMedia(in Int id);

    /**
     * MediaMgmt.media_getMediaByHash
     * @param contentHash contentHash
     * @return Media
     * @throws RemoteException if IPC fails
     */
    Media mediaGetMediaByHash(in String contentHash);

    /**
     * MediaMgmt.media_listMedia
     * @param limit limit
     * @param offset offset
     * @param filter filter
     * @return List<Media>
     * @throws RemoteException if IPC fails
     */
    List<Media> mediaListMedia(in Int limit, in Int offset, in MediaFilter filter);

    /**
     * MediaMgmt.media_updateMedia
     * @param id id
     * @param title title
     * @return Boolean
     * @throws RemoteException if IPC fails
     */
    Boolean mediaUpdateMedia(in Int id, in String title);

    /**
     * MediaMgmt.media_deleteMedia
     * @param id id
     * @return Boolean
     * @throws RemoteException if IPC fails
     */
    Boolean mediaDeleteMedia(in Int id);

    /**
     * MediaMgmt.media_addMediaLink
     * @param uri uri
     * @param mimeType mimeType
     * @param title title
     * @param directory directory
     * @return Unit
     * @throws RemoteException if IPC fails
     */
    Unit mediaAddMediaLink(in String uri, in String mimeType, in String title, in String directory);

    /**
     * MediaMgmt.media_addMediaFile
     * @param uri uri
     * @param title title
     * @return Unit
     * @throws RemoteException if IPC fails
     */
    Unit mediaAddMediaFile(in String uri, in String title);

    /**
     * MediaSourceMgmt.media_source_registerSource
     * @param url url
     * @param adapterType adapterType
     * @param capabilities capabilities
     * @param config config
     * @return Unit
     * @throws RemoteException if IPC fails
     */
    Unit mediaSourceRegisterSource(in String url, in MediaAdapterType adapterType, in List<MediaSourceCapability> capabilities, in Record<string, unknown> config);

    /**
     * MediaSourceMgmt.media_source_getSource
     * @param id id
     * @return MediaSource
     * @throws RemoteException if IPC fails
     */
    MediaSource mediaSourceGetSource(in Int id);

    /**
     * MediaSourceMgmt.media_source_listSources
     * @param activeOnly activeOnly
     * @param adapterType adapterType
     * @return List<MediaSource>
     * @throws RemoteException if IPC fails
     */
    List<MediaSource> mediaSourceListSources(in Boolean activeOnly, in MediaAdapterType adapterType);

    /**
     * MediaSourceMgmt.media_source_updateSource
     * @param id id
     * @param config config
     * @param isActive isActive
     * @return Boolean
     * @throws RemoteException if IPC fails
     */
    Boolean mediaSourceUpdateSource(in Int id, in Record<string, unknown> config, in Boolean isActive);

    /**
     * MediaSourceMgmt.media_source_unregisterSource
     * @param id id
     * @return Boolean
     * @throws RemoteException if IPC fails
     */
    Boolean mediaSourceUnregisterSource(in Int id);

    /**
     * MediaSourceMgmt.media_source_pollSource
     * @param id id
     * @return PollResult
     * @throws RemoteException if IPC fails
     */
    PollResult mediaSourcePollSource(in Int id);

    /**
     * MediaSourceMgmt.media_source_getHealth
     * @param id id
     * @return MediaSourceHealth
     * @throws RemoteException if IPC fails
     */
    MediaSourceHealth mediaSourceGetHealth(in Int id);

    /**
     * MediaSourceMgmt.media_source_resetErrors
     * @param id id
     * @return Boolean
     * @throws RemoteException if IPC fails
     */
    Boolean mediaSourceResetErrors(in Int id);

    /**
     * PersonMgmt.person_addPerson
     * @param displayName displayName
     * @param handle handle
     * @param metadata metadata
     * @return Unit
     * @throws RemoteException if IPC fails
     */
    Unit personAddPerson(in String displayName, in String handle, in Record<string, unknown> metadata);

    /**
     * PersonMgmt.person_getPerson
     * @param id id
     * @return Person
     * @throws RemoteException if IPC fails
     */
    Person personGetPerson(in Int id);

    /**
     * PersonMgmt.person_getPersonByHandle
     * @param handle handle
     * @return Person
     * @throws RemoteException if IPC fails
     */
    Person personGetPersonByHandle(in String handle);

    /**
     * PersonMgmt.person_listPeople
     * @param limit limit
     * @param offset offset
     * @param filter filter
     * @return List<Person>
     * @throws RemoteException if IPC fails
     */
    List<Person> personListPeople(in Int limit, in Int offset, in PersonFilter filter);

    /**
     * PersonMgmt.person_updatePerson
     * @param id id
     * @param displayName displayName
     * @param handle handle
     * @param metadata metadata
     * @return Boolean
     * @throws RemoteException if IPC fails
     */
    Boolean personUpdatePerson(in Int id, in String displayName, in String handle, in Record<string, unknown> metadata);

    /**
     * PersonMgmt.person_deletePerson
     * @param id id
     * @return Boolean
     * @throws RemoteException if IPC fails
     */
    Boolean personDeletePerson(in Int id);

    /**
     * PostMgmt.post_addPost
     * @param bits bits
     * @return Int
     * @throws RemoteException if IPC fails
     */
    Int postAddPost(in List<AccumulableBit> bits);

    /**
     * PostMgmt.post_getPost
     * @param id id
     * @return Post
     * @throws RemoteException if IPC fails
     */
    Post postGetPost(in Int id);

    /**
     * PostMgmt.post_listPosts
     * @param limit limit
     * @param offset offset
     * @param filter filter
     * @return List<Post>
     * @throws RemoteException if IPC fails
     */
    List<Post> postListPosts(in Int limit, in Int offset, in PostFilter filter);

    /**
     * PostMgmt.post_updatePost
     * @param id id
     * @param bits bits
     * @return Boolean
     * @throws RemoteException if IPC fails
     */
    Boolean postUpdatePost(in Int id, in List<AccumulableBit> bits);

    /**
     * PostMgmt.post_deletePost
     * @param id id
     * @return Boolean
     * @throws RemoteException if IPC fails
     */
    Boolean postDeletePost(in Int id);

    /**
     * TheStreamMgmt.the_stream_getEntries
     * @param limit limit
     * @param offset offset
     * @param filter filter
     * @return List<TheStreamEntry>
     * @throws RemoteException if IPC fails
     */
    List<TheStreamEntry> theStreamGetEntries(in Int limit, in Int offset, in TheStreamEntryFilter filter);

    /**
     * TheStreamMgmt.the_stream_getEntry
     * @param id id
     * @return TheStreamEntry
     * @throws RemoteException if IPC fails
     */
    TheStreamEntry theStreamGetEntry(in Int id);

    /**
     * TheStreamMgmt.the_stream_deleteEntry
     * @param id id
     * @return Boolean
     * @throws RemoteException if IPC fails
     */
    Boolean theStreamDeleteEntry(in Int id);

    /**
     * TheStreamMgmt.the_stream_getEntriesByKind
     * @param kind kind
     * @param limit limit
     * @param before before
     * @return List<TheStreamEntry>
     * @throws RemoteException if IPC fails
     */
    List<TheStreamEntry> theStreamGetEntriesByKind(in 'media' | 'post' | 'bookmark' | 'person' | 'conversation' kind, in Int limit, in Int before);

    /**
     * TheStreamMgmt.the_stream_search
     * @param query query
     * @param kinds kinds
     * @param limit limit
     * @return List<TheStreamEntry>
     * @throws RemoteException if IPC fails
     */
    List<TheStreamEntry> theStreamSearch(in String query, in List<String> kinds, in Int limit);

    /**
     * TheStreamMgmt.the_stream_addBookmark
     * @param bookmarkId bookmarkId
     * @param seenAt seenAt
     * @return TheStreamEntry
     * @throws RemoteException if IPC fails
     */
    TheStreamEntry theStreamAddBookmark(in Int bookmarkId, in Int seenAt);

    /**
     * TheStreamMgmt.the_stream_addPost
     * @param postId postId
     * @param seenAt seenAt
     * @return TheStreamEntry
     * @throws RemoteException if IPC fails
     */
    TheStreamEntry theStreamAddPost(in Int postId, in Int seenAt);

    /**
     * TheStreamMgmt.the_stream_addMedia
     * @param mediaId mediaId
     * @param seenAt seenAt
     * @return TheStreamEntry
     * @throws RemoteException if IPC fails
     */
    TheStreamEntry theStreamAddMedia(in Int mediaId, in Int seenAt);

    /**
     * TheStreamMgmt.the_stream_addPerson
     * @param personId personId
     * @param seenAt seenAt
     * @return TheStreamEntry
     * @throws RemoteException if IPC fails
     */
    TheStreamEntry theStreamAddPerson(in Int personId, in Int seenAt);

    /**
     * TheStreamMgmt.the_stream_addConversation
     * @param conversationId conversationId
     * @param seenAt seenAt
     * @return TheStreamEntry
     * @throws RemoteException if IPC fails
     */
    TheStreamEntry theStreamAddConversation(in Int conversationId, in Int seenAt);

    /**
     * ViewMgmt.view_addView
     * @param index index
     * @param badge badge
     * @param label label
     * @return Unit
     * @throws RemoteException if IPC fails
     */
    Unit viewAddView(in Int index, in String badge, in String label);

    /**
     * ViewMgmt.view_getView
     * @param id id
     * @return View
     * @throws RemoteException if IPC fails
     */
    View viewGetView(in Int id);

    /**
     * ViewMgmt.view_listViews
     * @return List<Unit>
     * @throws RemoteException if IPC fails
     */
    List<Unit> viewListViews();

    /**
     * ViewMgmt.view_deleteView
     * @param id id
     * @return Boolean
     * @throws RemoteException if IPC fails
     */
    Boolean viewDeleteView(in Int id);

}
