// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: tauri/foundframe_command_provider.kt.ejs
// Template file: foundframe_command_provider.kt.ejs
// This is a custom template in your workspace
// 
// To modify the generated output, edit the template file above.
package ty.circulari.o19

import android.app.Activity
import android.util.Log
import app.tauri.annotation.Command
import app.tauri.annotation.InvokeArg
import app.tauri.plugin.Invoke
import app.tauri.plugin.JSObject
import ty.circulari.o19.service.FoundframeRadicleClient

/**
 * FoundframeCommandProvider - Generated command handlers for foundframe operations
 *
 * This class is instantiated by ApiPlugin and provides all foundframe-related
 * Tauri commands. It manages the service client lifecycle and exposes methods
 * via the @Command annotation for Tauri to call from JavaScript.
 *
 * Generated from management methods. Do not edit manually.
 * Regenerate with: spire-loom
 */
class FoundframeCommandProvider(private val activity: Activity) {
    
    companion object {
        private const val TAG = "FoundframeCommandProvider"
    }
    
    private var client: FoundframeRadicleClient? = null
    
    /**
     * Initialize the command provider.
     * Starts and binds to the FoundframeRadicleService.
     * Called by ApiPlugin.load()
     */
    fun initialize() {
        Log.i(TAG, "Initializing FoundframeCommandProvider")
        
        client = FoundframeRadicleClient(activity)
        
        // Step 1: Start the service (it runs in :foundframe process)
        val started = client?.ensureStarted("deardiary") ?: false
        if (!started) {
            Log.e(TAG, "Failed to start FoundframeRadicleService")
        } else {
            Log.i(TAG, "FoundframeRadicleService started")
        }
        
        // Step 2: Bind to the service for AIDL IPC
        val connected = client?.connect() ?: false
        if (!connected) {
            Log.e(TAG, "Failed to connect to FoundframeRadicleService")
        } else {
            Log.i(TAG, "Connected to FoundframeRadicleService")
        }
    }
    
    /**
     * Cleanup resources.
     * Called by ApiPlugin.onDestroy()
     */
    fun cleanup() {
        Log.i(TAG, "Cleaning up FoundframeCommandProvider")
        client?.disconnect()
        client = null
    }
    
    // ==========================================================================
    // Service Status Commands
    // ==========================================================================
    
    /**
     * Check if connected to the service.
     */
    @Command
    fun isServiceReady(invoke: Invoke) {
        val ready = client?.isConnected() ?: false
        val response = JSObject()
        response.put("ready", ready)
        invoke.resolve(response)
    }
    
    /**
     * Explicitly connect to the service.
     */
    @Command
    fun connectService(invoke: Invoke) {
        val connected = client?.connect() ?: false
        val response = JSObject()
        response.put("connected", connected)
        invoke.resolve(response)
    }
    
    // ==========================================================================
    // Generated Command Handlers
    // ==========================================================================
    

}
