//! android-activities: FoundframeRadicle singleton service for Android
//!
//! This crate provides:
//! - `aidl_service`: The service-side implementation (runs in :foundframe process)
//! - `aidl_client`: The client-side bindings for connecting to the service
//!
//! # Architecture
//!
//! ```
//! App Process (Tauri)          :foundframe Process
//!     │                              │
//!     │  aidl_client::Client         │  aidl_service::Service
//!     │           │                  │           │
//!     └───────────┼──────────────────┼───────────┘
//!                 │    Binder IPC    │
//!                 └──────────────────┘
//! ```

// Include the generated AIDL code (types, traits, proxies, natives)
// Generated by rsbinder-aidl (in build.rs) from android/aidl/
// which creates the ty::circulari::o19 module
use rsbinder::*;
include!(concat!(env!("OUT_DIR"), "/ty_circulari_o19.rs"));

pub mod aidl_client;
pub mod aidl_service;

// Re-export the main client type
pub use aidl_client::Client;
