// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/packages/spire-loom/machinery/bobbin/tauri/adaptor.ts.ejs
// Template file: adaptor.ts.ejs
// To override: Copy this template to loom/bobbin/tauri/adaptor.ts.ejs
// 
// To modify the generated output, edit the template file above.
import { invoke } from '@tauri-apps/api/core';

/**
 * Bookmark Adaptor Implementations
 * 
 * Tauri-based adaptor for Bookmark operations.
 * All operations go through Tauri commands to the Rust core.
 * 
 * @generated by tauri-adaptor treadle
 */

import type { Bookmark, BookmarkFilter
} from '@o19/foundframe-front/domain';
import type {
  BookmarkPort,
  BookmarkReadPort,
  BookmarkWritePort
} from '@o19/foundframe-front/ports';

/**
 * Tauri-based adaptor for Bookmark
 */
export class TauriBookmarkAdaptor implements BookmarkReadPort, BookmarkWritePort {


  async getById(
  id: number
  ): Promise<Bookmark> {
    return invoke('plugin:o19-foundframe-tauri|get_bookmark' 
      , { id }
    );
  }
  async getBookmark(
  uri: string
  ): Promise<Bookmark> {
    return invoke('plugin:o19-foundframe-tauri|get_bookmark_by_uri' 
      , { uri }
    );
  }
  async list( data: { limit?: number, offset?: number, filter?: BookmarkFilter } ): Promise<Bookmark[]> {
    return invoke('plugin:o19-foundframe-tauri|list_bookmarks' 
      , data
    );
  }

/**
 * Write adaptor interface for Bookmark
 * Implements create/update/delete operations
 */

  create(data: { url: string, title?: string, notes?: string }): Promise<void> {
    return invoke('plugin:o19-foundframe-tauri|add_bookmark', data);
  }
  update(data: { id: number, title?: string, notes?: string }): Promise<boolean> {
    return invoke('plugin:o19-foundframe-tauri|update_bookmark', data);
  }

  delete(id: number): Promise<boolean> {
    return invoke('plugin:o19-foundframe-tauri|delete_bookmark', { id });
  }

}

/**
 * Convenience export - single adaptor handles all operations
 */
export { TauriBookmarkAdaptor as BookmarkAdaptor };
