// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/packages/spire-loom/machinery/bobbin/tauri/adaptor.ts.ejs
// Template file: adaptor.ts.ejs
// To override: Copy this template to loom/bobbin/tauri/adaptor.ts.ejs
// 
// To modify the generated output, edit the template file above.
import { invoke } from '@tauri-apps/api/core';

/**
 * Media Adaptor Implementations
 * 
 * Tauri-based adaptor for Media operations.
 * All operations go through Tauri commands to the Rust core.
 * 
 * @generated by tauri-adaptor treadle
 */

import type { Media, MediaFilter
} from '@o19/foundframe-front/domain';
import type {
  MediaPort,
  MediaReadPort,
  MediaWritePort
} from '@o19/foundframe-front/ports';

/**
 * Tauri-based adaptor for Media
 */
export class TauriMediaAdaptor implements MediaReadPort, MediaWritePort {

  async addMediaLink(data: { uri: string, mimeType: string, title?: string, directory?: string }): Promise<void> {
    return invoke('plugin:o19-foundframe-tauri|add_media_link', data);
  }
  async addMediaFile(data: { uri: string, title?: string }): Promise<void> {
    return invoke('plugin:o19-foundframe-tauri|add_media_file', data);
  }

  async getById(
  id: number
  ): Promise<Media> {
    return invoke('plugin:o19-foundframe-tauri|get_media' 
      , { id }
    );
  }
  async getMedia(
  contentHash: string
  ): Promise<Media> {
    return invoke('plugin:o19-foundframe-tauri|get_media_by_hash' 
      , { contentHash }
    );
  }
  async list( data: { limit?: number, offset?: number, filter?: MediaFilter } ): Promise<Media[]> {
    return invoke('plugin:o19-foundframe-tauri|list_media' 
      , data
    );
  }

/**
 * Write adaptor interface for Media
 * Implements create/update/delete operations
 */

  update(data: { id: number, title?: string }): Promise<boolean> {
    return invoke('plugin:o19-foundframe-tauri|update_media', data);
  }

  delete(id: number): Promise<boolean> {
    return invoke('plugin:o19-foundframe-tauri|delete_media', { id });
  }

}

/**
 * Convenience export - single adaptor handles all operations
 */
export { TauriMediaAdaptor as MediaAdaptor };
