// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/packages/spire-loom/machinery/bobbin/tauri/adaptor.ts.mejs
// Template file: adaptor.ts.mejs
// To override: Copy this template to loom/bobbin/tauri/adaptor.ts.mejs
// 
// To modify the generated output, edit the template file above.
import { invoke } from '@tauri-apps/api/core';

/**
 * Pkb Adaptor Implementations
 *
 * Tauri-based adaptor for pkb operations.
 * All operations go through Tauri commands to the Rust core.
 *
 * @generated by tauri-adaptor treadle
 */

import type { Pkb
} from '@o19/foundframe-front/domain';

import type {
  PkbPort,
  PkbReadPort,
  PkbWritePort
} from '@o19/foundframe-front/ports';

/**
 * Tauri-based adaptor for pkb
 */
export class TauriPkbAdaptor implements PkbReadPort, PkbWritePort {



  // ============================================================================
  // Write Operations
  // ============================================================================



}

/**
 * Convenience export - single adaptor handles all operations
 */
export { TauriPkbAdaptor as PkbAdaptor };
