// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/packages/spire-loom/machinery/bobbin/tauri/adaptor.ts.ejs
// Template file: adaptor.ts.ejs
// To override: Copy this template to loom/bobbin/tauri/adaptor.ts.ejs
// 
// To modify the generated output, edit the template file above.
import { invoke } from '@tauri-apps/api/core';

/**
 * Post Adaptor Implementations
 * 
 * Tauri-based adaptor for Post operations.
 * All operations go through Tauri commands to the Rust core.
 * 
 * @generated by tauri-adaptor treadle
 */

import type { Post, AccumulableBit, ConversationEntry, ConversationFilter, MediaAdapterType, MediaSourceCapability, PollResult, MediaSourceHealth
, PostFilter
} from '@o19/foundframe-front/domain';
import type {
  PostPort,
  PostReadPort,
  PostWritePort
} from '@o19/foundframe-front/ports';

/**
 * Tauri-based adaptor for Post
 */
export class TauriPostAdaptor implements PostReadPort, PostWritePort {


  async getById(
  id: number
  ): Promise<Post> {
    return invoke('plugin:o19-foundframe-tauri|get_post' 
      , { id }
    );
  }
  async list( data: { limit?: number, offset?: number, filter?: PostFilter } ): Promise<Post[]> {
    return invoke('plugin:o19-foundframe-tauri|list_posts' 
      , data
    );
  }

/**
 * Write adaptor interface for Post
 * Implements create/update/delete operations
 */

  create(data: { bits: AccumulableBit[] }): Promise<number> {
    return invoke('plugin:o19-foundframe-tauri|add_post', data);
  }
  update(data: { id: number, bits?: AccumulableBit[] }): Promise<boolean> {
    return invoke('plugin:o19-foundframe-tauri|update_post', data);
  }

  delete(id: number): Promise<boolean> {
    return invoke('plugin:o19-foundframe-tauri|delete_post', { id });
  }

}

/**
 * Convenience export - single adaptor handles all operations
 */
export { TauriPostAdaptor as PostAdaptor };
