// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/packages/spire-loom/machinery/bobbin/tauri/adaptor.ts.ejs
// Template file: adaptor.ts.ejs
// To override: Copy this template to loom/bobbin/tauri/adaptor.ts.ejs
// 
// To modify the generated output, edit the template file above.
import { invoke } from '@tauri-apps/api/core';

/**
 * View Adaptor Implementations
 * 
 * Tauri-based adaptor for View operations.
 * All operations go through Tauri commands to the Rust core.
 * 
 * @generated by tauri-adaptor treadle
 */

import type { View} from '@o19/foundframe-front/domain';
import type {
  ViewPort,
  ViewReadPort,
  ViewWritePort
} from '@o19/foundframe-front/ports';

/**
 * Tauri-based adaptor for View
 */
export class TauriViewAdaptor implements ViewReadPort, ViewWritePort {


  async getById(
  id: number
  ): Promise<View> {
    return invoke('plugin:o19-foundframe-tauri|get_view' 
      , { id }
    );
  }
  async list(
  
  ): Promise<void[]> {
    return invoke('plugin:o19-foundframe-tauri|list_views' );
  }

/**
 * Write adaptor interface for View
 * Implements create/update/delete operations
 */

  create(data: { index: number, badge: string, label?: string }): Promise<void> {
    return invoke('plugin:o19-foundframe-tauri|add_view', data);
  }

  delete(id: number): Promise<boolean> {
    return invoke('plugin:o19-foundframe-tauri|delete_view', { id });
  }

}

/**
 * Convenience export - single adaptor handles all operations
 */
export { TauriViewAdaptor as ViewAdaptor };
