// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: node_modules/@o19/spire-loom/machinery/bobbin/android/service.kt.ejs
// Template file: service.kt.ejs
// To override: Copy this template to loom/bobbin/android/service.kt.ejs
// 
// To modify the generated output, edit the template file above.
package ty.circulari.o19.service

import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.Service
import android.content.Context
import android.content.Intent
import android.os.Build
import android.os.IBinder
import android.os.Process
import android.os.RemoteException
import android.util.Log
import ty.circulari.o19.IFoundframeRadicle

/**
 * FoundframeRadicleService - Generated foreground service with AIDL IPC
 * 
 * This service runs in a separate process (:foundframe) and provides cross-process
 * access to the Rust core library via AIDL.
 * 
 * Architecture:
 * - Started service: Maintains native Rust core lifecycle via JNI
 * - Bound service: Provides AIDL interface for IPC from other apps/processes
 * - The service is both started (for lifecycle) AND bound (for IPC)
 */
class FoundframeRadicleService : Service() {
    
    companion object {
        private const val TAG = "FOUNDFRAMERADICLESERVICE"
        private const val NOTIFICATION_ID = 1
        private const val CHANNEL_ID = "foundframeradicleservice"
        
        init {
            try {
                Log.i(TAG, "[FoundframeRadicleService] Loading native library...")
                System.loadLibrary("android")
                Log.i(TAG, "[FoundframeRadicleService] Native library loaded successfully")
            } catch (e: Throwable) {
                Log.e(TAG, "[FoundframeRadicleService] FAILED to load native library: ${e.message}", e)
            }
        }
    }
    
    /** 
     * Native handle to the Rust service instance.
     * This is an opaque pointer - the actual Rust object lives in native memory.
     */
    private var nativeHandle: Long = 0
    
    /** Start the native service - returns a handle to the service instance */
    private external fun nativeStartService(homeDir: String, alias: String): Long
    
    /** Stop the native service and release the handle */
    private external fun nativeStopService(handle: Long)
    
    /** BookmarkMgmt.bookmark_addBookmark */
    private external fun nativeBookmarkAddBookmark(
        handle: Long,
                url: String,
                title: String,
                notes: String
        
    ): Unit
    
    /** BookmarkMgmt.bookmark_getBookmarkByUrl */
    private external fun nativeBookmarkGetBookmarkByUrl(
        handle: Long,
                pkbUrl: String
        
    ): String
    
    /** BookmarkMgmt.bookmark_listBookmarks */
    private external fun nativeBookmarkListBookmarks(
        handle: Long,
                directory: String
        
    ): List<String>
    
    /** BookmarkMgmt.bookmark_deleteBookmark */
    private external fun nativeBookmarkDeleteBookmark(
        handle: Long,
                pkbUrl: String
        
    ): Boolean
    
    /** ConversationMgmt.conversation_addConversation */
    private external fun nativeConversationAddConversation(
        handle: Long,
                conversationId: String,
                title: String,
                participants: String
        
    ): Unit
    
    /** ConversationMgmt.conversation_getConversation */
    private external fun nativeConversationGetConversation(
        handle: Long,
                conversationId: String
        
    ): String
    
    /** ConversationMgmt.conversation_listConversations */
    private external fun nativeConversationListConversations(
        handle: Long
        
    ): List<String>
    
    /** ConversationMgmt.conversation_updateConversation */
    private external fun nativeConversationUpdateConversation(
        handle: Long,
                conversationId: String,
                title: String,
                participants: String
        
    ): Boolean
    
    /** ConversationMgmt.conversation_deleteConversation */
    private external fun nativeConversationDeleteConversation(
        handle: Long,
                conversationId: String
        
    ): Boolean
    
    /** ConversationMgmt.conversation_addParticipant */
    private external fun nativeConversationAddParticipant(
        handle: Long,
                conversationId: String,
                personHandle: String,
                role: String
        
    ): Boolean
    
    /** ConversationMgmt.conversation_removeParticipant */
    private external fun nativeConversationRemoveParticipant(
        handle: Long,
                conversationId: String,
                personHandle: String
        
    ): Boolean
    
    /** ConversationMgmt.conversation_listParticipants */
    private external fun nativeConversationListParticipants(
        handle: Long,
                conversationId: String
        
    ): List<String>
    
    /** ConversationMgmt.conversation_addConversationMedia */
    private external fun nativeConversationAddConversationMedia(
        handle: Long,
                conversationId: String,
                mediaUrl: String,
                context: String
        
    ): Boolean
    
    /** ConversationMgmt.conversation_removeConversationMedia */
    private external fun nativeConversationRemoveConversationMedia(
        handle: Long,
                conversationId: String,
                mediaUrl: String
        
    ): Boolean
    
    /** ConversationMgmt.conversation_listConversationMedia */
    private external fun nativeConversationListConversationMedia(
        handle: Long,
                conversationId: String
        
    ): List<String>
    
    /** DeviceMgmt.device_generatePairingCode */
    private external fun nativeDeviceGeneratePairingCode(
        handle: Long
        
    ): String
    
    /** DeviceMgmt.device_confirmPairing */
    private external fun nativeDeviceConfirmPairing(
        handle: Long,
                deviceId: String,
                code: String
        
    ): Boolean
    
    /** DeviceMgmt.device_unpairDevice */
    private external fun nativeDeviceUnpairDevice(
        handle: Long,
                deviceId: String
        
    ): Unit
    
    /** DeviceMgmt.device_listPairedDevices */
    private external fun nativeDeviceListPairedDevices(
        handle: Long
        
    ): List<String>
    
    /** DeviceMgmt.device_followDevice */
    private external fun nativeDeviceFollowDevice(
        handle: Long,
                deviceId: String
        
    ): Boolean
    
    /** DeviceMgmt.device_unfollowDevice */
    private external fun nativeDeviceUnfollowDevice(
        handle: Long,
                deviceId: String
        
    ): Unit
    
    /** DeviceMgmt.device_listFollowers */
    private external fun nativeDeviceListFollowers(
        handle: Long
        
    ): List<String>
    
    /** DeviceMgmt.device_isFollowing */
    private external fun nativeDeviceIsFollowing(
        handle: Long,
                deviceId: String
        
    ): Boolean
    
    /** MediaMgmt.media_addMediaLink */
    private external fun nativeMediaAddMediaLink(
        handle: Long,
                url: String,
                title: String,
                mimeType: String,
                directory: String
        
    ): Unit
    
    /** MediaMgmt.media_addMediaFile */
    private external fun nativeMediaAddMediaFile(
        handle: Long,
                filePath: String,
                title: String
        
    ): Unit
    
    /** MediaMgmt.media_getMediaByUrl */
    private external fun nativeMediaGetMediaByUrl(
        handle: Long,
                url: String
        
    ): String
    
    /** MediaMgmt.media_listMedia */
    private external fun nativeMediaListMedia(
        handle: Long,
                directory: String
        
    ): List<String>
    
    /** MediaMgmt.media_deleteMedia */
    private external fun nativeMediaDeleteMedia(
        handle: Long,
                pkbUrl: String
        
    ): Boolean
    
    /** PersonMgmt.person_addPerson */
    private external fun nativePersonAddPerson(
        handle: Long,
                displayName: String,
                handle: String,
                metadata: String
        
    ): Unit
    
    /** PersonMgmt.person_getPersonByHandle */
    private external fun nativePersonGetPersonByHandle(
        handle: Long,
                handle: String
        
    ): String
    
    /** PersonMgmt.person_listPeople */
    private external fun nativePersonListPeople(
        handle: Long
        
    ): List<String>
    
    /** PersonMgmt.person_updatePerson */
    private external fun nativePersonUpdatePerson(
        handle: Long,
                handle: String,
                displayName: String,
                metadata: String
        
    ): Boolean
    
    /** PersonMgmt.person_deletePerson */
    private external fun nativePersonDeletePerson(
        handle: Long,
                handle: String
        
    ): Boolean
    
    /** PostMgmt.post_addPost */
    private external fun nativePostAddPost(
        handle: Long,
                content: String,
                title: String,
                tags: String
        
    ): Unit
    
    /** PostMgmt.post_getPostByUrl */
    private external fun nativePostGetPostByUrl(
        handle: Long,
                pkbUrl: String
        
    ): String
    
    /** PostMgmt.post_listPosts */
    private external fun nativePostListPosts(
        handle: Long,
                directory: String
        
    ): List<String>
    
    /** PostMgmt.post_updatePost */
    private external fun nativePostUpdatePost(
        handle: Long,
                pkbUrl: String,
                content: String,
                title: String
        
    ): Boolean
    
    /** PostMgmt.post_deletePost */
    private external fun nativePostDeletePost(
        handle: Long,
                pkbUrl: String
        
    ): Boolean
    
    
    /**
     * AIDL Binder Stub - generated by NDK aidl tool, implemented here.
     * 
     * This inner class extends the AIDL-generated Stub to provide the actual
     * implementation. It bridges AIDL calls to JNI calls into the Rust core.
     * 
     * Security: Access is controlled by AndroidManifest.xml permission:
     * ty.circulari.o19.ACCESS_FOUNDFRAME (signature level)
     */
    private val aidlBinder = object : IFoundframeRadicle.Stub() {
                
        @Throws(RemoteException::class)
        override fun bookmark_add_bookmark(
                        url: String,
                        title: String,
                        notes: String
            
        ): Unit {
            check(nativeHandle != 0L) { 
                "Service not initialized - ensure service is started before binding" 
            }
            return nativeBookmarkAddBookmark(
                nativeHandle,
                                url,
                                title,
                                notes
                
            )
        }
                
        @Throws(RemoteException::class)
        override fun bookmark_get_bookmark_by_url(
                        pkbUrl: String
            
        ): String {
            check(nativeHandle != 0L) { 
                "Service not initialized - ensure service is started before binding" 
            }
            return nativeBookmarkGetBookmarkByUrl(
                nativeHandle,
                                pkbUrl
                
            )
        }
                
        @Throws(RemoteException::class)
        override fun bookmark_list_bookmarks(
                        directory: String
            
        ): List<String> {
            check(nativeHandle != 0L) { 
                "Service not initialized - ensure service is started before binding" 
            }
            return nativeBookmarkListBookmarks(
                nativeHandle,
                                directory
                
            )
        }
                
        @Throws(RemoteException::class)
        override fun bookmark_delete_bookmark(
                        pkbUrl: String
            
        ): Boolean {
            check(nativeHandle != 0L) { 
                "Service not initialized - ensure service is started before binding" 
            }
            return nativeBookmarkDeleteBookmark(
                nativeHandle,
                                pkbUrl
                
            )
        }
                
        @Throws(RemoteException::class)
        override fun conversation_add_conversation(
                        conversationId: String,
                        title: String,
                        participants: String
            
        ): Unit {
            check(nativeHandle != 0L) { 
                "Service not initialized - ensure service is started before binding" 
            }
            return nativeConversationAddConversation(
                nativeHandle,
                                conversationId,
                                title,
                                participants
                
            )
        }
                
        @Throws(RemoteException::class)
        override fun conversation_get_conversation(
                        conversationId: String
            
        ): String {
            check(nativeHandle != 0L) { 
                "Service not initialized - ensure service is started before binding" 
            }
            return nativeConversationGetConversation(
                nativeHandle,
                                conversationId
                
            )
        }
                
        @Throws(RemoteException::class)
        override fun conversation_list_conversations(
            
        ): List<String> {
            check(nativeHandle != 0L) { 
                "Service not initialized - ensure service is started before binding" 
            }
            return nativeConversationListConversations(
                nativeHandle
                
            )
        }
                
        @Throws(RemoteException::class)
        override fun conversation_update_conversation(
                        conversationId: String,
                        title: String,
                        participants: String
            
        ): Boolean {
            check(nativeHandle != 0L) { 
                "Service not initialized - ensure service is started before binding" 
            }
            return nativeConversationUpdateConversation(
                nativeHandle,
                                conversationId,
                                title,
                                participants
                
            )
        }
                
        @Throws(RemoteException::class)
        override fun conversation_delete_conversation(
                        conversationId: String
            
        ): Boolean {
            check(nativeHandle != 0L) { 
                "Service not initialized - ensure service is started before binding" 
            }
            return nativeConversationDeleteConversation(
                nativeHandle,
                                conversationId
                
            )
        }
                
        @Throws(RemoteException::class)
        override fun conversation_add_participant(
                        conversationId: String,
                        personHandle: String,
                        role: String
            
        ): Boolean {
            check(nativeHandle != 0L) { 
                "Service not initialized - ensure service is started before binding" 
            }
            return nativeConversationAddParticipant(
                nativeHandle,
                                conversationId,
                                personHandle,
                                role
                
            )
        }
                
        @Throws(RemoteException::class)
        override fun conversation_remove_participant(
                        conversationId: String,
                        personHandle: String
            
        ): Boolean {
            check(nativeHandle != 0L) { 
                "Service not initialized - ensure service is started before binding" 
            }
            return nativeConversationRemoveParticipant(
                nativeHandle,
                                conversationId,
                                personHandle
                
            )
        }
                
        @Throws(RemoteException::class)
        override fun conversation_list_participants(
                        conversationId: String
            
        ): List<String> {
            check(nativeHandle != 0L) { 
                "Service not initialized - ensure service is started before binding" 
            }
            return nativeConversationListParticipants(
                nativeHandle,
                                conversationId
                
            )
        }
                
        @Throws(RemoteException::class)
        override fun conversation_add_conversation_media(
                        conversationId: String,
                        mediaUrl: String,
                        context: String
            
        ): Boolean {
            check(nativeHandle != 0L) { 
                "Service not initialized - ensure service is started before binding" 
            }
            return nativeConversationAddConversationMedia(
                nativeHandle,
                                conversationId,
                                mediaUrl,
                                context
                
            )
        }
                
        @Throws(RemoteException::class)
        override fun conversation_remove_conversation_media(
                        conversationId: String,
                        mediaUrl: String
            
        ): Boolean {
            check(nativeHandle != 0L) { 
                "Service not initialized - ensure service is started before binding" 
            }
            return nativeConversationRemoveConversationMedia(
                nativeHandle,
                                conversationId,
                                mediaUrl
                
            )
        }
                
        @Throws(RemoteException::class)
        override fun conversation_list_conversation_media(
                        conversationId: String
            
        ): List<String> {
            check(nativeHandle != 0L) { 
                "Service not initialized - ensure service is started before binding" 
            }
            return nativeConversationListConversationMedia(
                nativeHandle,
                                conversationId
                
            )
        }
                
        @Throws(RemoteException::class)
        override fun device_generate_pairing_code(
            
        ): String {
            check(nativeHandle != 0L) { 
                "Service not initialized - ensure service is started before binding" 
            }
            return nativeDeviceGeneratePairingCode(
                nativeHandle
                
            )
        }
                
        @Throws(RemoteException::class)
        override fun device_confirm_pairing(
                        deviceId: String,
                        code: String
            
        ): Boolean {
            check(nativeHandle != 0L) { 
                "Service not initialized - ensure service is started before binding" 
            }
            return nativeDeviceConfirmPairing(
                nativeHandle,
                                deviceId,
                                code
                
            )
        }
                
        @Throws(RemoteException::class)
        override fun device_unpair_device(
                        deviceId: String
            
        ): Unit {
            check(nativeHandle != 0L) { 
                "Service not initialized - ensure service is started before binding" 
            }
            return nativeDeviceUnpairDevice(
                nativeHandle,
                                deviceId
                
            )
        }
                
        @Throws(RemoteException::class)
        override fun device_list_paired_devices(
            
        ): List<String> {
            check(nativeHandle != 0L) { 
                "Service not initialized - ensure service is started before binding" 
            }
            return nativeDeviceListPairedDevices(
                nativeHandle
                
            )
        }
                
        @Throws(RemoteException::class)
        override fun device_follow_device(
                        deviceId: String
            
        ): Boolean {
            check(nativeHandle != 0L) { 
                "Service not initialized - ensure service is started before binding" 
            }
            return nativeDeviceFollowDevice(
                nativeHandle,
                                deviceId
                
            )
        }
                
        @Throws(RemoteException::class)
        override fun device_unfollow_device(
                        deviceId: String
            
        ): Unit {
            check(nativeHandle != 0L) { 
                "Service not initialized - ensure service is started before binding" 
            }
            return nativeDeviceUnfollowDevice(
                nativeHandle,
                                deviceId
                
            )
        }
                
        @Throws(RemoteException::class)
        override fun device_list_followers(
            
        ): List<String> {
            check(nativeHandle != 0L) { 
                "Service not initialized - ensure service is started before binding" 
            }
            return nativeDeviceListFollowers(
                nativeHandle
                
            )
        }
                
        @Throws(RemoteException::class)
        override fun device_is_following(
                        deviceId: String
            
        ): Boolean {
            check(nativeHandle != 0L) { 
                "Service not initialized - ensure service is started before binding" 
            }
            return nativeDeviceIsFollowing(
                nativeHandle,
                                deviceId
                
            )
        }
                
        @Throws(RemoteException::class)
        override fun media_add_media_link(
                        url: String,
                        title: String,
                        mimeType: String,
                        directory: String
            
        ): Unit {
            check(nativeHandle != 0L) { 
                "Service not initialized - ensure service is started before binding" 
            }
            return nativeMediaAddMediaLink(
                nativeHandle,
                                url,
                                title,
                                mimeType,
                                directory
                
            )
        }
                
        @Throws(RemoteException::class)
        override fun media_add_media_file(
                        filePath: String,
                        title: String
            
        ): Unit {
            check(nativeHandle != 0L) { 
                "Service not initialized - ensure service is started before binding" 
            }
            return nativeMediaAddMediaFile(
                nativeHandle,
                                filePath,
                                title
                
            )
        }
                
        @Throws(RemoteException::class)
        override fun media_get_media_by_url(
                        url: String
            
        ): String {
            check(nativeHandle != 0L) { 
                "Service not initialized - ensure service is started before binding" 
            }
            return nativeMediaGetMediaByUrl(
                nativeHandle,
                                url
                
            )
        }
                
        @Throws(RemoteException::class)
        override fun media_list_media(
                        directory: String
            
        ): List<String> {
            check(nativeHandle != 0L) { 
                "Service not initialized - ensure service is started before binding" 
            }
            return nativeMediaListMedia(
                nativeHandle,
                                directory
                
            )
        }
                
        @Throws(RemoteException::class)
        override fun media_delete_media(
                        pkbUrl: String
            
        ): Boolean {
            check(nativeHandle != 0L) { 
                "Service not initialized - ensure service is started before binding" 
            }
            return nativeMediaDeleteMedia(
                nativeHandle,
                                pkbUrl
                
            )
        }
                
        @Throws(RemoteException::class)
        override fun person_add_person(
                        displayName: String,
                        handle: String,
                        metadata: String
            
        ): Unit {
            check(nativeHandle != 0L) { 
                "Service not initialized - ensure service is started before binding" 
            }
            return nativePersonAddPerson(
                nativeHandle,
                                displayName,
                                handle,
                                metadata
                
            )
        }
                
        @Throws(RemoteException::class)
        override fun person_get_person_by_handle(
                        handle: String
            
        ): String {
            check(nativeHandle != 0L) { 
                "Service not initialized - ensure service is started before binding" 
            }
            return nativePersonGetPersonByHandle(
                nativeHandle,
                                handle
                
            )
        }
                
        @Throws(RemoteException::class)
        override fun person_list_people(
            
        ): List<String> {
            check(nativeHandle != 0L) { 
                "Service not initialized - ensure service is started before binding" 
            }
            return nativePersonListPeople(
                nativeHandle
                
            )
        }
                
        @Throws(RemoteException::class)
        override fun person_update_person(
                        handle: String,
                        displayName: String,
                        metadata: String
            
        ): Boolean {
            check(nativeHandle != 0L) { 
                "Service not initialized - ensure service is started before binding" 
            }
            return nativePersonUpdatePerson(
                nativeHandle,
                                handle,
                                displayName,
                                metadata
                
            )
        }
                
        @Throws(RemoteException::class)
        override fun person_delete_person(
                        handle: String
            
        ): Boolean {
            check(nativeHandle != 0L) { 
                "Service not initialized - ensure service is started before binding" 
            }
            return nativePersonDeletePerson(
                nativeHandle,
                                handle
                
            )
        }
                
        @Throws(RemoteException::class)
        override fun post_add_post(
                        content: String,
                        title: String,
                        tags: String
            
        ): Unit {
            check(nativeHandle != 0L) { 
                "Service not initialized - ensure service is started before binding" 
            }
            return nativePostAddPost(
                nativeHandle,
                                content,
                                title,
                                tags
                
            )
        }
                
        @Throws(RemoteException::class)
        override fun post_get_post_by_url(
                        pkbUrl: String
            
        ): String {
            check(nativeHandle != 0L) { 
                "Service not initialized - ensure service is started before binding" 
            }
            return nativePostGetPostByUrl(
                nativeHandle,
                                pkbUrl
                
            )
        }
                
        @Throws(RemoteException::class)
        override fun post_list_posts(
                        directory: String
            
        ): List<String> {
            check(nativeHandle != 0L) { 
                "Service not initialized - ensure service is started before binding" 
            }
            return nativePostListPosts(
                nativeHandle,
                                directory
                
            )
        }
                
        @Throws(RemoteException::class)
        override fun post_update_post(
                        pkbUrl: String,
                        content: String,
                        title: String
            
        ): Boolean {
            check(nativeHandle != 0L) { 
                "Service not initialized - ensure service is started before binding" 
            }
            return nativePostUpdatePost(
                nativeHandle,
                                pkbUrl,
                                content,
                                title
                
            )
        }
                
        @Throws(RemoteException::class)
        override fun post_delete_post(
                        pkbUrl: String
            
        ): Boolean {
            check(nativeHandle != 0L) { 
                "Service not initialized - ensure service is started before binding" 
            }
            return nativePostDeletePost(
                nativeHandle,
                                pkbUrl
                
            )
        }
            }
    
    override fun onCreate() {
        super.onCreate()
        Log.i(TAG, "[FoundframeRadicleService] Service creating in pid ${Process.myPid()}")
        
        // Create notification channel for foreground service
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val channel = NotificationChannel(
                CHANNEL_ID,
                "FoundframeRadicleService",
                NotificationManager.IMPORTANCE_LOW
            ).apply {
                description = "Background service for foundframe"
                setShowBadge(false)
            }
            
            val notificationManager = getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
            notificationManager.createNotificationChannel(channel)
        }
        
        // Start as foreground service
        startForeground(NOTIFICATION_ID, createNotification())
        Log.i(TAG, "[FoundframeRadicleService] Started as foreground service")
    }
    
    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
        Log.i(TAG, "[FoundframeRadicleService] Service starting (startId=$startId)")
        
        val homeDir = getDir(".foundframe", Context.MODE_PRIVATE).absolutePath
        val alias = intent?.getStringExtra("alias") ?: "android"
        
        // Start the native service in a background thread
        Thread {
            try {
                nativeHandle = nativeStartService(homeDir, alias)
                if (nativeHandle < 0) {
                    Log.e(TAG, "[FoundframeRadicleService] Native service failed to start")
                    stopSelf(startId)
                    return@Thread
                }
                
                Log.i(TAG, "[FoundframeRadicleService] Native service started with handle=$nativeHandle")
                
                // Service keeps running until explicitly stopped
                // The Rust core runs its own event loop
                Thread.currentThread().join()
                
                Log.w(TAG, "[FoundframeRadicleService] Native service thread exited unexpectedly")
            } catch (e: Exception) {
                Log.e(TAG, "[FoundframeRadicleService] Native service crashed: ${e.message}", e)
            } finally {
                if (nativeHandle != 0L) {
                    nativeStopService(nativeHandle)
                }
                nativeHandle = 0
                stopSelf(startId)
            }
        }.apply {
            name = "FoundframeRadicleService-Thread-$startId"
            start()
        }
        
        return START_STICKY
    }
    
    /**
     * Called when a client binds to this service.
     * 
     * Returns the AIDL binder stub that implements IFoundframeRadicle interface.
     * This enables cross-process IPC for apps with the same signing key.
     * 
     * @param intent The Intent that was used to bind to this service
     * @return IBinder The AIDL interface implementation
     */
    override fun onBind(intent: Intent): IBinder {
        Log.i(TAG, "[FoundframeRadicleService] onBind() - returning AIDL binder")
        return aidlBinder
    }
    
    override fun onDestroy() {
        super.onDestroy()
        Log.i(TAG, "[FoundframeRadicleService] Service destroying")
        if (nativeHandle != 0L) {
            nativeStopService(nativeHandle)
            nativeHandle = 0
        }
    }
    
    /**
     * Check if the native service is ready for AIDL calls.
     * Clients can use this to verify the service is initialized before calling methods.
     */
    fun isReady(): Boolean = nativeHandle != 0L
    
    private fun createNotification(): Notification {
        val builder = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            Notification.Builder(this, CHANNEL_ID)
        } else {
            @Suppress("DEPRECATION")
            Notification.Builder(this)
        }
        
        return builder
            .setContentTitle("foundframe Service")
            .setContentText("Running in background")
            .setSmallIcon(android.R.drawable.ic_menu_share)
            .setOngoing(true)
            .build()
    }
}
