// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/crates/foundframe/loom/bobbin/rust/db/db_actor.rs.ejs
// Template file: db_actor.rs.ejs
// This is a workspace custom template (from loom/bobbin/)
// 
// To modify the generated output, edit the template file above.
// GENERATED BY db-binding Treadle - Do not edit

use std::path::Path;
use std::thread::{self, JoinHandle};

use crossbeam_channel::{bounded, Receiver};
use sqlite as sql;
use sea_query::{Query, SqliteQueryBuilder};

use crate::db::DbCommand;
use crate::db::DbHandle;
use crate::Result;
use crate::error::Error;
use crate::db::bookmark_data::BookmarkData;
use crate::db::{BookmarkFilter, BookmarkIden};
use crate::db::conversation_data::ConversationData;
use crate::db::{ConversationFilter, ConversationIden};
use crate::db::media_data::MediaData;
use crate::db::{MediaFilter, MediaIden};
use crate::db::mediasource_data::MediaSourceData;
use crate::db::{MediaSourceFilter, MediaSourceIden};
use crate::db::person_data::PersonData;
use crate::db::{PersonFilter, PersonIden};
use crate::db::post_data::PostData;
use crate::db::{PostFilter, PostIden};
use crate::db::streamentry_data::StreamEntryData;
use crate::db::{StreamEntryFilter, StreamEntryIden};
use crate::db::view_data::ViewData;
use crate::db::{ViewFilter, ViewIden};

// ============================================================================
// DbActor — The Shard
// ============================================================================

/// The database actor — a single shard that owns SQLite.
pub struct DbActor {
  /// Command receiver — the "management interface"
  rx: Receiver<DbCommand>,
  
  /// SQLite connection — owned exclusively by this thread
  conn: sql::ConnectionThreadSafe,
}

impl DbActor {
  /// Create a new DbActor and return the handle to control it.
  pub async fn spawn<P: AsRef<Path>>(path: P) -> Result<(DbHandle, JoinHandle<()>)> {
    let path = path.as_ref().to_path_buf();
    
    // Run blocking initialization in spawn_blocking
    let (tx, rx, conn) = tokio::task::spawn_blocking(move || -> Result<_> {
      let (tx, rx) = bounded(128); // Backpressure: 128 command buffer
      
      // Open connection in blocking context
      let conn = sql::Connection::open_thread_safe(&path)?;
      conn.execute("PRAGMA foreign_keys = ON")?;
      
      // Run migrations
      DbActor::migrate_entities(&conn)?;
      
      Ok((tx, rx, conn))
    }).await
    .map_err(|e| Error::Other(format!("Spawn blocking failed: {}", e)))??;
    
    let actor = Self { rx, conn };
    
    // Spawn the shard (dedicated thread)
    let handle = thread::spawn(move || {
      actor.run();
    });
    
    Ok((DbHandle::new(tx), handle))
  }
  
  /// Spawn an in-memory actor for testing
  pub async fn spawn_in_memory() -> Result<(DbHandle, JoinHandle<()>)> {
    // Run blocking initialization in spawn_blocking
    let (tx, rx, conn) = tokio::task::spawn_blocking(move || -> Result<_> {
      let (tx, rx) = bounded(128);
      
      let conn = sql::Connection::open_thread_safe(":memory:")?;
      conn.execute("PRAGMA foreign_keys = ON")?;
      DbActor::migrate_entities(&conn)?;
      
      Ok((tx, rx, conn))
    }).await
    .map_err(|e| Error::Other(format!("Spawn blocking failed: {}", e)))??;
    
    let actor = Self { rx, conn };
    
    let handle = thread::spawn(move || {
      actor.run();
    });
    
    Ok((DbHandle::new(tx), handle))
  }
  
  /// Main event loop — process commands sequentially
  fn run(self) {
    while let Ok(cmd) = self.rx.recv() {
      match cmd {
        DbCommand::Shutdown => break,
        _ => self.handle_command(cmd),
      }
    }
  }
  
  /// Handle a single command
  fn handle_command(&self, cmd: DbCommand) {
    match cmd {
      // Bookmark commands
      DbCommand::CreateBookmark { data, respond } => {
        let _ = respond.send(self.insert_bookmark(data));
      }
      DbCommand::ReadBookmarkById { id, respond } => {
        let _ = respond.send(self.get_bookmark_by_id(id));
      }
      DbCommand::ReadBookmarkByUrl { url, respond } => {
        let _ = respond.send(self.get_bookmark_by_url(&url));
      }
      DbCommand::ListBookmarks { limit, offset, filter, respond } => {
        let _ = respond.send(self.list_bookmarks(limit, offset, &filter));
      }
      DbCommand::UpdateBookmark { id, data, respond } => {
        let _ = respond.send(self.update_bookmark(id, data));
      }
      DbCommand::UpdateBookmarkTitle { id, title, respond } => {
        let _ = respond.send(self.update_bookmark_title(id, title));
      }
      DbCommand::UpdateBookmarkNotes { id, notes, respond } => {
        let _ = respond.send(self.update_bookmark_notes(id, notes));
      }
      DbCommand::DeleteBookmark { id, respond } => {
        let _ = respond.send(self.delete_bookmark(id));
      }
      // Conversation commands
      DbCommand::CreateConversation { data, respond } => {
        let _ = respond.send(self.insert_conversation(data));
      }
      DbCommand::ReadConversationById { id, respond } => {
        let _ = respond.send(self.get_conversation_by_id(id));
      }
      DbCommand::ListConversations { limit, offset, filter, respond } => {
        let _ = respond.send(self.list_conversations(limit, offset, &filter));
      }
      DbCommand::UpdateConversation { id, data, respond } => {
        let _ = respond.send(self.update_conversation(id, data));
      }
      DbCommand::UpdateConversationTitle { id, title, respond } => {
        let _ = respond.send(self.update_conversation_title(id, title));
      }
      DbCommand::UpdateConversationAttributedTo { id, attributedTo, respond } => {
        let _ = respond.send(self.update_conversation_attributedTo(id, attributedTo));
      }
      DbCommand::UpdateConversationFirstEntryTime { id, firstEntryTime, respond } => {
        let _ = respond.send(self.update_conversation_firstEntryTime(id, firstEntryTime));
      }
      DbCommand::UpdateConversationLastEntryTime { id, lastEntryTime, respond } => {
        let _ = respond.send(self.update_conversation_lastEntryTime(id, lastEntryTime));
      }
      DbCommand::UpdateConversationSourceUrl { id, sourceUrl, respond } => {
        let _ = respond.send(self.update_conversation_sourceUrl(id, sourceUrl));
      }
      DbCommand::UpdateConversationUpdatedAt { id, updatedAt, respond } => {
        let _ = respond.send(self.update_conversation_updatedAt(id));
      }
      DbCommand::DeleteConversation { id, respond } => {
        let _ = respond.send(self.delete_conversation(id));
      }
      // Media commands
      DbCommand::CreateMedia { data, respond } => {
        let _ = respond.send(self.insert_media(data));
      }
      DbCommand::ReadMediaById { id, respond } => {
        let _ = respond.send(self.get_media_by_id(id));
      }
      DbCommand::ReadMediaByUrl { url, respond } => {
        let _ = respond.send(self.get_media_by_url(&url));
      }
      DbCommand::ListMedias { limit, offset, filter, respond } => {
        let _ = respond.send(self.list_medias(limit, offset, &filter));
      }
      DbCommand::UpdateMedia { id, data, respond } => {
        let _ = respond.send(self.update_media(id, data));
      }
      DbCommand::UpdateMediaContentHash { id, contentHash, respond } => {
        let _ = respond.send(self.update_media_contentHash(id, contentHash));
      }
      DbCommand::UpdateMediaWidth { id, width, respond } => {
        let _ = respond.send(self.update_media_width(id, width));
      }
      DbCommand::UpdateMediaHeight { id, height, respond } => {
        let _ = respond.send(self.update_media_height(id, height));
      }
      DbCommand::UpdateMediaDurationMs { id, durationMs, respond } => {
        let _ = respond.send(self.update_media_durationMs(id, durationMs));
      }
      DbCommand::UpdateMediaMetadata { id, metadata, respond } => {
        let _ = respond.send(self.update_media_metadata(id, metadata));
      }
      DbCommand::DeleteMedia { id, respond } => {
        let _ = respond.send(self.delete_media(id));
      }
      // MediaSource commands
      DbCommand::CreateMediaSource { data, respond } => {
        let _ = respond.send(self.insert_mediasource(data));
      }
      DbCommand::ReadMediaSourceById { id, respond } => {
        let _ = respond.send(self.get_mediasource_by_id(id));
      }
      DbCommand::ReadMediaSourceByUrl { url, respond } => {
        let _ = respond.send(self.get_mediasource_by_url(&url));
      }
      DbCommand::ListMediaSources { limit, offset, filter, respond } => {
        let _ = respond.send(self.list_mediasources(limit, offset, &filter));
      }
      DbCommand::UpdateMediaSource { id, data, respond } => {
        let _ = respond.send(self.update_mediasource(id, data));
      }
      DbCommand::UpdateMediaSourceCursorState { id, cursorState, respond } => {
        let _ = respond.send(self.update_mediasource_cursorState(id, cursorState));
      }
      DbCommand::UpdateMediaSourceConfig { id, config, respond } => {
        let _ = respond.send(self.update_mediasource_config(id, config));
      }
      DbCommand::UpdateMediaSourceLastPolledAt { id, lastPolledAt, respond } => {
        let _ = respond.send(self.update_mediasource_lastPolledAt(id, lastPolledAt));
      }
      DbCommand::UpdateMediaSourceLastError { id, lastError, respond } => {
        let _ = respond.send(self.update_mediasource_lastError(id, lastError));
      }
      DbCommand::UpdateMediaSourceUpdatedAt { id, updatedAt, respond } => {
        let _ = respond.send(self.update_mediasource_updatedAt(id));
      }
      DbCommand::DeleteMediaSource { id, respond } => {
        let _ = respond.send(self.delete_mediasource(id));
      }
      // Person commands
      DbCommand::CreatePerson { data, respond } => {
        let _ = respond.send(self.insert_person(data));
      }
      DbCommand::ReadPersonById { id, respond } => {
        let _ = respond.send(self.get_person_by_id(id));
      }
      DbCommand::ListPersons { limit, offset, filter, respond } => {
        let _ = respond.send(self.list_persons(limit, offset, &filter));
      }
      DbCommand::UpdatePerson { id, data, respond } => {
        let _ = respond.send(self.update_person(id, data));
      }
      DbCommand::UpdatePersonHandle { id, handle, respond } => {
        let _ = respond.send(self.update_person_handle(id, handle));
      }
      DbCommand::UpdatePersonAvatarMediaId { id, avatarMediaId, respond } => {
        let _ = respond.send(self.update_person_avatarMediaId(id, avatarMediaId));
      }
      DbCommand::UpdatePersonMetadata { id, metadata, respond } => {
        let _ = respond.send(self.update_person_metadata(id, metadata));
      }
      DbCommand::UpdatePersonUpdatedAt { id, updatedAt, respond } => {
        let _ = respond.send(self.update_person_updatedAt(id));
      }
      DbCommand::DeletePerson { id, respond } => {
        let _ = respond.send(self.delete_person(id));
      }
      // Post commands
      DbCommand::CreatePost { data, respond } => {
        let _ = respond.send(self.insert_post(data));
      }
      DbCommand::ReadPostById { id, respond } => {
        let _ = respond.send(self.get_post_by_id(id));
      }
      DbCommand::ListPosts { limit, offset, filter, respond } => {
        let _ = respond.send(self.list_posts(limit, offset, &filter));
      }
      DbCommand::UpdatePost { id, data, respond } => {
        let _ = respond.send(self.update_post(id, data));
      }
      DbCommand::UpdatePostContentHash { id, contentHash, respond } => {
        let _ = respond.send(self.update_post_contentHash(id, contentHash));
      }
      DbCommand::UpdatePostAuthorDid { id, authorDid, respond } => {
        let _ = respond.send(self.update_post_authorDid(id, authorDid));
      }
      DbCommand::UpdatePostSignature { id, signature, respond } => {
        let _ = respond.send(self.update_post_signature(id, signature));
      }
      DbCommand::UpdatePostUpdatedAt { id, updatedAt, respond } => {
        let _ = respond.send(self.update_post_updatedAt(id));
      }
      DbCommand::DeletePost { id, respond } => {
        let _ = respond.send(self.delete_post(id));
      }
      // StreamEntry commands
      DbCommand::CreateStreamEntry { data, respond } => {
        let _ = respond.send(self.insert_streamentry(data));
      }
      DbCommand::ReadStreamEntryById { id, respond } => {
        let _ = respond.send(self.get_streamentry_by_id(id));
      }
      DbCommand::ListStreamEntrys { limit, offset, filter, respond } => {
        let _ = respond.send(self.list_streamentrys(limit, offset, &filter));
      }
      DbCommand::UpdateStreamEntry { id, data, respond } => {
        let _ = respond.send(self.update_streamentry(id, data));
      }
      DbCommand::UpdateStreamEntryPersonId { id, personId, respond } => {
        let _ = respond.send(self.update_streamentry_personId(id, personId));
      }
      DbCommand::UpdateStreamEntryPostId { id, postId, respond } => {
        let _ = respond.send(self.update_streamentry_postId(id, postId));
      }
      DbCommand::UpdateStreamEntryMediaId { id, mediaId, respond } => {
        let _ = respond.send(self.update_streamentry_mediaId(id, mediaId));
      }
      DbCommand::UpdateStreamEntryBookmarkId { id, bookmarkId, respond } => {
        let _ = respond.send(self.update_streamentry_bookmarkId(id, bookmarkId));
      }
      DbCommand::UpdateStreamEntryConversationId { id, conversationId, respond } => {
        let _ = respond.send(self.update_streamentry_conversationId(id, conversationId));
      }
      DbCommand::UpdateStreamEntryDirectory { id, directory, respond } => {
        let _ = respond.send(self.update_streamentry_directory(id, directory));
      }
      DbCommand::UpdateStreamEntryKind { id, kind, respond } => {
        let _ = respond.send(self.update_streamentry_kind(id, kind));
      }
      DbCommand::UpdateStreamEntryContentHash { id, contentHash, respond } => {
        let _ = respond.send(self.update_streamentry_contentHash(id, contentHash));
      }
      DbCommand::DeleteStreamEntry { id, respond } => {
        let _ = respond.send(self.delete_streamentry(id));
      }
      // View commands
      DbCommand::CreateView { data, respond } => {
        let _ = respond.send(self.insert_view(data));
      }
      DbCommand::ReadViewById { id, respond } => {
        let _ = respond.send(self.get_view_by_id(id));
      }
      DbCommand::ListViews { limit, offset, filter, respond } => {
        let _ = respond.send(self.list_views(limit, offset, &filter));
      }
      DbCommand::UpdateView { id, data, respond } => {
        let _ = respond.send(self.update_view(id, data));
      }
      DbCommand::UpdateViewLabel { id, label, respond } => {
        let _ = respond.send(self.update_view_label(id, label));
      }
      DbCommand::UpdateViewUpdatedAt { id, updatedAt, respond } => {
        let _ = respond.send(self.update_view_updatedAt(id));
      }
      DbCommand::DeleteView { id, respond } => {
        let _ = respond.send(self.delete_view(id));
      }
      DbCommand::Shutdown => unreachable!(),
    }
  }
}

// ============================================================================
// SQL Implementations
// ============================================================================

impl DbActor {
  // --------------------------------------------------------------------------
  // Bookmark Queries
  // --------------------------------------------------------------------------
  
  fn insert_bookmark(&self, data: BookmarkData) -> Result<i64> {
    let sql = format!(
      "INSERT INTO bookmark ({}) VALUES ({ })",
      "uri,title,notes,creation_context",
      "?,?,?,?"
    );
    let mut stmt = self.conn.prepare(sql)?;
    
    stmt.bind((1, sql::Value::String(data.uri.to_string())))?;
    stmt.bind((2, sql::Value::String(data.title.to_string())))?;
    stmt.bind((3, sql::Value::String(data.notes.to_string())))?;
    stmt.bind((4, sql::Value::String(data.creation_context.to_string())))?;
    stmt.next()?;
    
    // Get the last inserted ID
    let mut stmt = self.conn.prepare("SELECT last_insert_rowid()")?;
    let id: i64 = if let Some(row) = stmt.into_iter().next() {
      row?.read(0)
    } else {
      return Err(Error::Other("Failed to get last insert ID".into()));
    };
    Ok(id)
  }
  
  fn get_bookmark_by_id(&self, id: i64) -> Result<Option<BookmarkData>> {
    let mut stmt = self.conn.prepare(
      "SELECT * FROM bookmark WHERE id = ?1"
    )?;
    stmt.bind((1, sql::Value::Integer(id)))?;
    
    if let Some(row) = stmt.into_iter().next() {
      let row = row?;
      Ok(Some(self.row_to_bookmark(&row)?))
    } else {
      Ok(None)
    }
  }
  
  fn get_bookmark_by_url(&self, url: &str) -> Result<Option<BookmarkData>> {
    let mut stmt = self.conn.prepare(
      "SELECT * FROM bookmark WHERE uri = ?1"
    )?;
    stmt.bind((1, sql::Value::String(url.to_string())))?;
    
    if let Some(row) = stmt.into_iter().next() {
      let row = row?;
      Ok(Some(self.row_to_bookmark(&row)?))
    } else {
      Ok(None)
    }
  }
  
  /// List Bookmarks with dynamic filtering using sea-query
  fn list_bookmarks(&self, limit: Option<usize>, offset: Option<usize>, filter: &BookmarkFilter) -> Result<Vec<BookmarkData>> {
    // Build query with sea-query
    let mut query = Query::select();
    query
      .column(BookmarkIden::Id)
      .column(BookmarkIden::Uri)
      .column(BookmarkIden::Title)
      .column(BookmarkIden::Notes)
      .column(BookmarkIden::CreationContext)
      .column(BookmarkIden::CreatedAt)
      .from(BookmarkIden::Table);
    
    // Add filter conditions
    let cond = filter.to_condition();
    if !cond.is_empty() {
      query.cond_where(cond);
    }
    
    // Add ordering (by created_at/seen_at desc, or first column if no time field)
    query.order_by(BookmarkIden::CreatedAt, sea_query::Order::Desc);
    
    // Add limit and offset
    if let Some(l) = limit {
      query.limit(l as u64);
    }
    if let Some(o) = offset {
      query.offset(o as u64);
    }
    
    // Build SQL
    let (sql, _values) = query.build(SqliteQueryBuilder);
    
    // Execute with sqlite crate
    let mut stmt = self.conn.prepare(&sql)?;
    let mut results = Vec::new();
    for row in stmt.into_iter() {
      let row = row?;
      results.push(self.row_to_bookmark(&row)?);
    }
    Ok(results)
  }
  
  fn update_bookmark(&self, id: i64, data: BookmarkData) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      r#"
      UPDATE bookmark SET
        uri = ?1,
        title = ?2,
        notes = ?3,
        creation_context = ?4
      WHERE id = ?5
      "#
    )?;
    
    stmt.bind((1, sql::Value::String(data.uri.to_string())))?;
    stmt.bind((2, sql::Value::String(data.title.to_string())))?;
    stmt.bind((3, sql::Value::String(data.notes.to_string())))?;
    stmt.bind((4, sql::Value::String(data.creation_context.to_string())))?;
    stmt.bind((5, sql::Value::Integer(id)))?;
    
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn update_bookmark_title(&self, id: i64, title: Option<string>) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      "UPDATE bookmark SET title = ?1 WHERE id = ?2"
    )?;
    stmt.bind((1, sql::Value::String(title.to_string())))?;
    stmt.bind((2, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn update_bookmark_notes(&self, id: i64, notes: Option<string>) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      "UPDATE bookmark SET notes = ?1 WHERE id = ?2"
    )?;
    stmt.bind((1, sql::Value::String(notes.to_string())))?;
    stmt.bind((2, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn delete_bookmark(&self, id: i64) -> Result<bool> {
    let mut stmt = self.conn.prepare("DELETE FROM bookmark WHERE id = ?1")?;
    stmt.bind((1, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn row_to_bookmark(&self, row: &sql::Row) -> Result<BookmarkData> {
    Ok(BookmarkData {
      id: row.try_read::<i64, _>("id")?,
      uri: row.try_read::<string, _>("uri")?,
      title: row.try_read::<Option<string>, _>("title")?,
      notes: row.try_read::<Option<string>, _>("notes")?,
      creation_context: {
        let s = row.try_read::<&str, _>("creation_context")?;
        serde_json::from_str(s).map_err(|e| Error::Other(format!("JSON parse error: {}", e)))?
      },
      created_at: row.try_read::<i64, _>("created_at")?,
    })
  }
  // --------------------------------------------------------------------------
  // Conversation Queries
  // --------------------------------------------------------------------------
  
  fn insert_conversation(&self, data: ConversationData) -> Result<i64> {
    let sql = format!(
      "INSERT INTO conversation ({}) VALUES ({ })",
      "title,content,attributed_to,capture_time,first_entry_time,last_entry_time,source_url",
      "?,?,?,?,?,?,?"
    );
    let mut stmt = self.conn.prepare(sql)?;
    
    stmt.bind((1, sql::Value::String(data.title.to_string())))?;
    stmt.bind((2, sql::Value::String(data.content.to_string())))?;
    stmt.bind((3, sql::Value::String(data.attributed_to.to_string())))?;
    stmt.bind((4, sql::Value::String(data.capture_time.to_string())))?;
    stmt.bind((5, sql::Value::String(data.first_entry_time.to_string())))?;
    stmt.bind((6, sql::Value::String(data.last_entry_time.to_string())))?;
    stmt.bind((7, sql::Value::String(data.source_url.to_string())))?;
    stmt.next()?;
    
    // Get the last inserted ID
    let mut stmt = self.conn.prepare("SELECT last_insert_rowid()")?;
    let id: i64 = if let Some(row) = stmt.into_iter().next() {
      row?.read(0)
    } else {
      return Err(Error::Other("Failed to get last insert ID".into()));
    };
    Ok(id)
  }
  
  fn get_conversation_by_id(&self, id: i64) -> Result<Option<ConversationData>> {
    let mut stmt = self.conn.prepare(
      "SELECT * FROM conversation WHERE id = ?1"
    )?;
    stmt.bind((1, sql::Value::Integer(id)))?;
    
    if let Some(row) = stmt.into_iter().next() {
      let row = row?;
      Ok(Some(self.row_to_conversation(&row)?))
    } else {
      Ok(None)
    }
  }
  
  /// List Conversations with dynamic filtering using sea-query
  fn list_conversations(&self, limit: Option<usize>, offset: Option<usize>, filter: &ConversationFilter) -> Result<Vec<ConversationData>> {
    // Build query with sea-query
    let mut query = Query::select();
    query
      .column(ConversationIden::Id)
      .column(ConversationIden::Title)
      .column(ConversationIden::Content)
      .column(ConversationIden::AttributedTo)
      .column(ConversationIden::CaptureTime)
      .column(ConversationIden::FirstEntryTime)
      .column(ConversationIden::LastEntryTime)
      .column(ConversationIden::SourceUrl)
      .column(ConversationIden::CreatedAt)
      .column(ConversationIden::UpdatedAt)
      .from(ConversationIden::Table);
    
    // Add filter conditions
    let cond = filter.to_condition();
    if !cond.is_empty() {
      query.cond_where(cond);
    }
    
    // Add ordering (by created_at/seen_at desc, or first column if no time field)
    query.order_by(ConversationIden::CreatedAt, sea_query::Order::Desc);
    
    // Add limit and offset
    if let Some(l) = limit {
      query.limit(l as u64);
    }
    if let Some(o) = offset {
      query.offset(o as u64);
    }
    
    // Build SQL
    let (sql, _values) = query.build(SqliteQueryBuilder);
    
    // Execute with sqlite crate
    let mut stmt = self.conn.prepare(&sql)?;
    let mut results = Vec::new();
    for row in stmt.into_iter() {
      let row = row?;
      results.push(self.row_to_conversation(&row)?);
    }
    Ok(results)
  }
  
  fn update_conversation(&self, id: i64, data: ConversationData) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      r#"
      UPDATE conversation SET
        title = ?1,
        content = ?2,
        attributed_to = ?3,
        capture_time = ?4,
        first_entry_time = ?5,
        last_entry_time = ?6,
        source_url = ?7,
        updated_at = ?8
      WHERE id = ?9
      "#
    )?;
    
    stmt.bind((1, sql::Value::String(data.title.to_string())))?;
    stmt.bind((2, sql::Value::String(data.content.to_string())))?;
    stmt.bind((3, sql::Value::String(data.attributed_to.to_string())))?;
    stmt.bind((4, sql::Value::String(data.capture_time.to_string())))?;
    stmt.bind((5, sql::Value::String(data.first_entry_time.to_string())))?;
    stmt.bind((6, sql::Value::String(data.last_entry_time.to_string())))?;
    stmt.bind((7, sql::Value::String(data.source_url.to_string())))?;
    stmt.bind((8, sql::Value::Integer(data.updated_at)))?;
    stmt.bind((9, sql::Value::Integer(id)))?;
    
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn update_conversation_title(&self, id: i64, title: Option<string>) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      "UPDATE conversation SET title = ?1 WHERE id = ?2"
    )?;
    stmt.bind((1, sql::Value::String(title.to_string())))?;
    stmt.bind((2, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn update_conversation_attributedTo(&self, id: i64, attributedTo: Option<string>) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      "UPDATE conversation SET attributed_to = ?1 WHERE id = ?2"
    )?;
    stmt.bind((1, sql::Value::String(attributedTo.to_string())))?;
    stmt.bind((2, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn update_conversation_firstEntryTime(&self, id: i64, firstEntryTime: Option<number>) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      "UPDATE conversation SET first_entry_time = ?1 WHERE id = ?2"
    )?;
    stmt.bind((1, sql::Value::String(firstEntryTime.to_string())))?;
    stmt.bind((2, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn update_conversation_lastEntryTime(&self, id: i64, lastEntryTime: Option<number>) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      "UPDATE conversation SET last_entry_time = ?1 WHERE id = ?2"
    )?;
    stmt.bind((1, sql::Value::String(lastEntryTime.to_string())))?;
    stmt.bind((2, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn update_conversation_sourceUrl(&self, id: i64, sourceUrl: Option<string>) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      "UPDATE conversation SET source_url = ?1 WHERE id = ?2"
    )?;
    stmt.bind((1, sql::Value::String(sourceUrl.to_string())))?;
    stmt.bind((2, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn update_conversation_updatedAt(&self, id: i64) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      "UPDATE conversation SET updated_at = unixepoch() WHERE id = ?1"
    )?;
    stmt.bind((1, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn delete_conversation(&self, id: i64) -> Result<bool> {
    let mut stmt = self.conn.prepare("DELETE FROM conversation WHERE id = ?1")?;
    stmt.bind((1, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn row_to_conversation(&self, row: &sql::Row) -> Result<ConversationData> {
    Ok(ConversationData {
      id: row.try_read::<i64, _>("id")?,
      title: row.try_read::<Option<string>, _>("title")?,
      content: {
        let s = row.try_read::<&str, _>("content")?;
        serde_json::from_str(s).map_err(|e| Error::Other(format!("JSON parse error: {}", e)))?
      },
      attributed_to: row.try_read::<Option<string>, _>("attributed_to")?,
      capture_time: row.try_read::<number, _>("capture_time")?,
      first_entry_time: row.try_read::<Option<number>, _>("first_entry_time")?,
      last_entry_time: row.try_read::<Option<number>, _>("last_entry_time")?,
      source_url: row.try_read::<Option<string>, _>("source_url")?,
      created_at: row.try_read::<i64, _>("created_at")?,
      updated_at: row.try_read::<i64, _>("updated_at")?,
    })
  }
  // --------------------------------------------------------------------------
  // Media Queries
  // --------------------------------------------------------------------------
  
  fn insert_media(&self, data: MediaData) -> Result<i64> {
    let sql = format!(
      "INSERT INTO media ({}) VALUES ({ })",
      "content_hash,mime_type,uri,width,height,duration_ms,metadata",
      "?,?,?,?,?,?,?"
    );
    let mut stmt = self.conn.prepare(sql)?;
    
    stmt.bind((1, sql::Value::String(data.content_hash.to_string())))?;
    stmt.bind((2, sql::Value::String(data.mime_type.to_string())))?;
    stmt.bind((3, sql::Value::String(data.uri.to_string())))?;
    stmt.bind((4, sql::Value::String(data.width.to_string())))?;
    stmt.bind((5, sql::Value::String(data.height.to_string())))?;
    stmt.bind((6, sql::Value::String(data.duration_ms.to_string())))?;
    stmt.bind((7, data.metadata.as_ref().map(|v| sql::Value::String(v.to_string()))))?;
    stmt.next()?;
    
    // Get the last inserted ID
    let mut stmt = self.conn.prepare("SELECT last_insert_rowid()")?;
    let id: i64 = if let Some(row) = stmt.into_iter().next() {
      row?.read(0)
    } else {
      return Err(Error::Other("Failed to get last insert ID".into()));
    };
    Ok(id)
  }
  
  fn get_media_by_id(&self, id: i64) -> Result<Option<MediaData>> {
    let mut stmt = self.conn.prepare(
      "SELECT * FROM media WHERE id = ?1"
    )?;
    stmt.bind((1, sql::Value::Integer(id)))?;
    
    if let Some(row) = stmt.into_iter().next() {
      let row = row?;
      Ok(Some(self.row_to_media(&row)?))
    } else {
      Ok(None)
    }
  }
  
  fn get_media_by_url(&self, url: &str) -> Result<Option<MediaData>> {
    let mut stmt = self.conn.prepare(
      "SELECT * FROM media WHERE uri = ?1"
    )?;
    stmt.bind((1, sql::Value::String(url.to_string())))?;
    
    if let Some(row) = stmt.into_iter().next() {
      let row = row?;
      Ok(Some(self.row_to_media(&row)?))
    } else {
      Ok(None)
    }
  }
  
  /// List Medias with dynamic filtering using sea-query
  fn list_medias(&self, limit: Option<usize>, offset: Option<usize>, filter: &MediaFilter) -> Result<Vec<MediaData>> {
    // Build query with sea-query
    let mut query = Query::select();
    query
      .column(MediaIden::Id)
      .column(MediaIden::ContentHash)
      .column(MediaIden::MimeType)
      .column(MediaIden::Uri)
      .column(MediaIden::Width)
      .column(MediaIden::Height)
      .column(MediaIden::DurationMs)
      .column(MediaIden::Metadata)
      .column(MediaIden::CreatedAt)
      .from(MediaIden::Table);
    
    // Add filter conditions
    let cond = filter.to_condition();
    if !cond.is_empty() {
      query.cond_where(cond);
    }
    
    // Add ordering (by created_at/seen_at desc, or first column if no time field)
    query.order_by(MediaIden::CreatedAt, sea_query::Order::Desc);
    
    // Add limit and offset
    if let Some(l) = limit {
      query.limit(l as u64);
    }
    if let Some(o) = offset {
      query.offset(o as u64);
    }
    
    // Build SQL
    let (sql, _values) = query.build(SqliteQueryBuilder);
    
    // Execute with sqlite crate
    let mut stmt = self.conn.prepare(&sql)?;
    let mut results = Vec::new();
    for row in stmt.into_iter() {
      let row = row?;
      results.push(self.row_to_media(&row)?);
    }
    Ok(results)
  }
  
  fn update_media(&self, id: i64, data: MediaData) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      r#"
      UPDATE media SET
        content_hash = ?1,
        mime_type = ?2,
        uri = ?3,
        width = ?4,
        height = ?5,
        duration_ms = ?6,
        metadata = ?7
      WHERE id = ?8
      "#
    )?;
    
    stmt.bind((1, sql::Value::String(data.content_hash.to_string())))?;
    stmt.bind((2, sql::Value::String(data.mime_type.to_string())))?;
    stmt.bind((3, sql::Value::String(data.uri.to_string())))?;
    stmt.bind((4, sql::Value::String(data.width.to_string())))?;
    stmt.bind((5, sql::Value::String(data.height.to_string())))?;
    stmt.bind((6, sql::Value::String(data.duration_ms.to_string())))?;
    stmt.bind((7, data.metadata.as_ref().map(|v| sql::Value::String(v.to_string()))))?;
    stmt.bind((8, sql::Value::Integer(id)))?;
    
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn update_media_contentHash(&self, id: i64, contentHash: Option<string>) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      "UPDATE media SET content_hash = ?1 WHERE id = ?2"
    )?;
    stmt.bind((1, sql::Value::String(contentHash.to_string())))?;
    stmt.bind((2, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn update_media_width(&self, id: i64, width: Option<number>) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      "UPDATE media SET width = ?1 WHERE id = ?2"
    )?;
    stmt.bind((1, sql::Value::String(width.to_string())))?;
    stmt.bind((2, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn update_media_height(&self, id: i64, height: Option<number>) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      "UPDATE media SET height = ?1 WHERE id = ?2"
    )?;
    stmt.bind((1, sql::Value::String(height.to_string())))?;
    stmt.bind((2, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn update_media_durationMs(&self, id: i64, durationMs: Option<number>) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      "UPDATE media SET duration_ms = ?1 WHERE id = ?2"
    )?;
    stmt.bind((1, sql::Value::String(durationMs.to_string())))?;
    stmt.bind((2, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn update_media_metadata(&self, id: i64, metadata: Option<serde_json::Value>) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      "UPDATE media SET metadata = ?1 WHERE id = ?2"
    )?;
    stmt.bind((1, metadata.as_ref().map(|v| sql::Value::String(v.to_string()))))?;
    stmt.bind((2, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn delete_media(&self, id: i64) -> Result<bool> {
    let mut stmt = self.conn.prepare("DELETE FROM media WHERE id = ?1")?;
    stmt.bind((1, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn row_to_media(&self, row: &sql::Row) -> Result<MediaData> {
    Ok(MediaData {
      id: row.try_read::<i64, _>("id")?,
      content_hash: row.try_read::<Option<string>, _>("content_hash")?,
      mime_type: row.try_read::<string, _>("mime_type")?,
      uri: row.try_read::<string, _>("uri")?,
      width: row.try_read::<Option<number>, _>("width")?,
      height: row.try_read::<Option<number>, _>("height")?,
      duration_ms: row.try_read::<Option<number>, _>("duration_ms")?,
      metadata: row.try_read::<Option<&str>, _>("metadata")?.and_then(|s| serde_json::from_str(s).ok()),
      created_at: row.try_read::<i64, _>("created_at")?,
    })
  }
  // --------------------------------------------------------------------------
  // MediaSource Queries
  // --------------------------------------------------------------------------
  
  fn insert_mediasource(&self, data: MediaSourceData) -> Result<i64> {
    let sql = format!(
      "INSERT INTO media_source ({}) VALUES ({ })",
      "url,adapter_type,cursor_state,capabilities,config,last_polled_at,last_error,is_active",
      "?,?,?,?,?,?,?,?"
    );
    let mut stmt = self.conn.prepare(sql)?;
    
    stmt.bind((1, sql::Value::String(data.url.to_string())))?;
    stmt.bind((2, sql::Value::String(data.adapter_type.to_string())))?;
    stmt.bind((3, data.cursor_state.as_ref().map(|v| sql::Value::String(v.to_string()))))?;
    stmt.bind((4, sql::Value::String(data.capabilities.to_string())))?;
    stmt.bind((5, data.config.as_ref().map(|v| sql::Value::String(v.to_string()))))?;
    stmt.bind((6, sql::Value::String(data.last_polled_at.to_string())))?;
    stmt.bind((7, sql::Value::String(data.last_error.to_string())))?;
    stmt.bind((8, sql::Value::String(data.is_active.to_string())))?;
    stmt.next()?;
    
    // Get the last inserted ID
    let mut stmt = self.conn.prepare("SELECT last_insert_rowid()")?;
    let id: i64 = if let Some(row) = stmt.into_iter().next() {
      row?.read(0)
    } else {
      return Err(Error::Other("Failed to get last insert ID".into()));
    };
    Ok(id)
  }
  
  fn get_mediasource_by_id(&self, id: i64) -> Result<Option<MediaSourceData>> {
    let mut stmt = self.conn.prepare(
      "SELECT * FROM media_source WHERE id = ?1"
    )?;
    stmt.bind((1, sql::Value::Integer(id)))?;
    
    if let Some(row) = stmt.into_iter().next() {
      let row = row?;
      Ok(Some(self.row_to_mediasource(&row)?))
    } else {
      Ok(None)
    }
  }
  
  fn get_mediasource_by_url(&self, url: &str) -> Result<Option<MediaSourceData>> {
    let mut stmt = self.conn.prepare(
      "SELECT * FROM media_source WHERE url = ?1"
    )?;
    stmt.bind((1, sql::Value::String(url.to_string())))?;
    
    if let Some(row) = stmt.into_iter().next() {
      let row = row?;
      Ok(Some(self.row_to_mediasource(&row)?))
    } else {
      Ok(None)
    }
  }
  
  /// List MediaSources with dynamic filtering using sea-query
  fn list_mediasources(&self, limit: Option<usize>, offset: Option<usize>, filter: &MediaSourceFilter) -> Result<Vec<MediaSourceData>> {
    // Build query with sea-query
    let mut query = Query::select();
    query
      .column(MediaSourceIden::Id)
      .column(MediaSourceIden::Url)
      .column(MediaSourceIden::AdapterType)
      .column(MediaSourceIden::CursorState)
      .column(MediaSourceIden::Capabilities)
      .column(MediaSourceIden::Config)
      .column(MediaSourceIden::LastPolledAt)
      .column(MediaSourceIden::LastError)
      .column(MediaSourceIden::IsActive)
      .column(MediaSourceIden::CreatedAt)
      .column(MediaSourceIden::UpdatedAt)
      .from(MediaSourceIden::Table);
    
    // Add filter conditions
    let cond = filter.to_condition();
    if !cond.is_empty() {
      query.cond_where(cond);
    }
    
    // Add ordering (by created_at/seen_at desc, or first column if no time field)
    query.order_by(MediaSourceIden::CreatedAt, sea_query::Order::Desc);
    
    // Add limit and offset
    if let Some(l) = limit {
      query.limit(l as u64);
    }
    if let Some(o) = offset {
      query.offset(o as u64);
    }
    
    // Build SQL
    let (sql, _values) = query.build(SqliteQueryBuilder);
    
    // Execute with sqlite crate
    let mut stmt = self.conn.prepare(&sql)?;
    let mut results = Vec::new();
    for row in stmt.into_iter() {
      let row = row?;
      results.push(self.row_to_mediasource(&row)?);
    }
    Ok(results)
  }
  
  fn update_mediasource(&self, id: i64, data: MediaSourceData) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      r#"
      UPDATE media_source SET
        url = ?1,
        adapter_type = ?2,
        cursor_state = ?3,
        capabilities = ?4,
        config = ?5,
        last_polled_at = ?6,
        last_error = ?7,
        is_active = ?8,
        updated_at = ?9
      WHERE id = ?10
      "#
    )?;
    
    stmt.bind((1, sql::Value::String(data.url.to_string())))?;
    stmt.bind((2, sql::Value::String(data.adapter_type.to_string())))?;
    stmt.bind((3, data.cursor_state.as_ref().map(|v| sql::Value::String(v.to_string()))))?;
    stmt.bind((4, sql::Value::String(data.capabilities.to_string())))?;
    stmt.bind((5, data.config.as_ref().map(|v| sql::Value::String(v.to_string()))))?;
    stmt.bind((6, sql::Value::String(data.last_polled_at.to_string())))?;
    stmt.bind((7, sql::Value::String(data.last_error.to_string())))?;
    stmt.bind((8, sql::Value::String(data.is_active.to_string())))?;
    stmt.bind((9, sql::Value::Integer(data.updated_at)))?;
    stmt.bind((10, sql::Value::Integer(id)))?;
    
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn update_mediasource_cursorState(&self, id: i64, cursorState: Option<serde_json::Value>) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      "UPDATE media_source SET cursor_state = ?1 WHERE id = ?2"
    )?;
    stmt.bind((1, cursorState.as_ref().map(|v| sql::Value::String(v.to_string()))))?;
    stmt.bind((2, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn update_mediasource_config(&self, id: i64, config: Option<serde_json::Value>) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      "UPDATE media_source SET config = ?1 WHERE id = ?2"
    )?;
    stmt.bind((1, config.as_ref().map(|v| sql::Value::String(v.to_string()))))?;
    stmt.bind((2, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn update_mediasource_lastPolledAt(&self, id: i64, lastPolledAt: Option<number>) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      "UPDATE media_source SET last_polled_at = ?1 WHERE id = ?2"
    )?;
    stmt.bind((1, sql::Value::String(lastPolledAt.to_string())))?;
    stmt.bind((2, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn update_mediasource_lastError(&self, id: i64, lastError: Option<string>) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      "UPDATE media_source SET last_error = ?1 WHERE id = ?2"
    )?;
    stmt.bind((1, sql::Value::String(lastError.to_string())))?;
    stmt.bind((2, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn update_mediasource_updatedAt(&self, id: i64) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      "UPDATE media_source SET updated_at = unixepoch() WHERE id = ?1"
    )?;
    stmt.bind((1, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn delete_mediasource(&self, id: i64) -> Result<bool> {
    let mut stmt = self.conn.prepare("DELETE FROM media_source WHERE id = ?1")?;
    stmt.bind((1, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn row_to_mediasource(&self, row: &sql::Row) -> Result<MediaSourceData> {
    Ok(MediaSourceData {
      id: row.try_read::<i64, _>("id")?,
      url: row.try_read::<string, _>("url")?,
      adapter_type: row.try_read::<string, _>("adapter_type")?,
      cursor_state: row.try_read::<Option<&str>, _>("cursor_state")?.and_then(|s| serde_json::from_str(s).ok()),
      capabilities: {
        let s = row.try_read::<&str, _>("capabilities")?;
        serde_json::from_str(s).map_err(|e| Error::Other(format!("JSON parse error: {}", e)))?
      },
      config: row.try_read::<Option<&str>, _>("config")?.and_then(|s| serde_json::from_str(s).ok()),
      last_polled_at: row.try_read::<Option<number>, _>("last_polled_at")?,
      last_error: row.try_read::<Option<string>, _>("last_error")?,
      is_active: row.try_read::<boolean, _>("is_active")?,
      created_at: row.try_read::<i64, _>("created_at")?,
      updated_at: row.try_read::<i64, _>("updated_at")?,
    })
  }
  // --------------------------------------------------------------------------
  // Person Queries
  // --------------------------------------------------------------------------
  
  fn insert_person(&self, data: PersonData) -> Result<i64> {
    let sql = format!(
      "INSERT INTO person ({}) VALUES ({ })",
      "display_name,handle,avatar_media_id,metadata",
      "?,?,?,?"
    );
    let mut stmt = self.conn.prepare(sql)?;
    
    stmt.bind((1, sql::Value::String(data.display_name.to_string())))?;
    stmt.bind((2, sql::Value::String(data.handle.to_string())))?;
    stmt.bind((3, sql::Value::String(data.avatar_media_id.to_string())))?;
    stmt.bind((4, data.metadata.as_ref().map(|v| sql::Value::String(v.to_string()))))?;
    stmt.next()?;
    
    // Get the last inserted ID
    let mut stmt = self.conn.prepare("SELECT last_insert_rowid()")?;
    let id: i64 = if let Some(row) = stmt.into_iter().next() {
      row?.read(0)
    } else {
      return Err(Error::Other("Failed to get last insert ID".into()));
    };
    Ok(id)
  }
  
  fn get_person_by_id(&self, id: i64) -> Result<Option<PersonData>> {
    let mut stmt = self.conn.prepare(
      "SELECT * FROM person WHERE id = ?1"
    )?;
    stmt.bind((1, sql::Value::Integer(id)))?;
    
    if let Some(row) = stmt.into_iter().next() {
      let row = row?;
      Ok(Some(self.row_to_person(&row)?))
    } else {
      Ok(None)
    }
  }
  
  /// List Persons with dynamic filtering using sea-query
  fn list_persons(&self, limit: Option<usize>, offset: Option<usize>, filter: &PersonFilter) -> Result<Vec<PersonData>> {
    // Build query with sea-query
    let mut query = Query::select();
    query
      .column(PersonIden::Id)
      .column(PersonIden::DisplayName)
      .column(PersonIden::Handle)
      .column(PersonIden::AvatarMediaId)
      .column(PersonIden::Metadata)
      .column(PersonIden::CreatedAt)
      .column(PersonIden::UpdatedAt)
      .from(PersonIden::Table);
    
    // Add filter conditions
    let cond = filter.to_condition();
    if !cond.is_empty() {
      query.cond_where(cond);
    }
    
    // Add ordering (by created_at/seen_at desc, or first column if no time field)
    query.order_by(PersonIden::CreatedAt, sea_query::Order::Desc);
    
    // Add limit and offset
    if let Some(l) = limit {
      query.limit(l as u64);
    }
    if let Some(o) = offset {
      query.offset(o as u64);
    }
    
    // Build SQL
    let (sql, _values) = query.build(SqliteQueryBuilder);
    
    // Execute with sqlite crate
    let mut stmt = self.conn.prepare(&sql)?;
    let mut results = Vec::new();
    for row in stmt.into_iter() {
      let row = row?;
      results.push(self.row_to_person(&row)?);
    }
    Ok(results)
  }
  
  fn update_person(&self, id: i64, data: PersonData) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      r#"
      UPDATE person SET
        display_name = ?1,
        handle = ?2,
        avatar_media_id = ?3,
        metadata = ?4,
        updated_at = ?5
      WHERE id = ?6
      "#
    )?;
    
    stmt.bind((1, sql::Value::String(data.display_name.to_string())))?;
    stmt.bind((2, sql::Value::String(data.handle.to_string())))?;
    stmt.bind((3, sql::Value::String(data.avatar_media_id.to_string())))?;
    stmt.bind((4, data.metadata.as_ref().map(|v| sql::Value::String(v.to_string()))))?;
    stmt.bind((5, sql::Value::Integer(data.updated_at)))?;
    stmt.bind((6, sql::Value::Integer(id)))?;
    
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn update_person_handle(&self, id: i64, handle: Option<string>) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      "UPDATE person SET handle = ?1 WHERE id = ?2"
    )?;
    stmt.bind((1, sql::Value::String(handle.to_string())))?;
    stmt.bind((2, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn update_person_avatarMediaId(&self, id: i64, avatarMediaId: Option<number>) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      "UPDATE person SET avatar_media_id = ?1 WHERE id = ?2"
    )?;
    stmt.bind((1, sql::Value::String(avatarMediaId.to_string())))?;
    stmt.bind((2, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn update_person_metadata(&self, id: i64, metadata: Option<serde_json::Value>) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      "UPDATE person SET metadata = ?1 WHERE id = ?2"
    )?;
    stmt.bind((1, metadata.as_ref().map(|v| sql::Value::String(v.to_string()))))?;
    stmt.bind((2, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn update_person_updatedAt(&self, id: i64) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      "UPDATE person SET updated_at = unixepoch() WHERE id = ?1"
    )?;
    stmt.bind((1, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn delete_person(&self, id: i64) -> Result<bool> {
    let mut stmt = self.conn.prepare("DELETE FROM person WHERE id = ?1")?;
    stmt.bind((1, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn row_to_person(&self, row: &sql::Row) -> Result<PersonData> {
    Ok(PersonData {
      id: row.try_read::<i64, _>("id")?,
      display_name: row.try_read::<string, _>("display_name")?,
      handle: row.try_read::<Option<string>, _>("handle")?,
      avatar_media_id: row.try_read::<Option<number>, _>("avatar_media_id")?,
      metadata: row.try_read::<Option<&str>, _>("metadata")?.and_then(|s| serde_json::from_str(s).ok()),
      created_at: row.try_read::<i64, _>("created_at")?,
      updated_at: row.try_read::<i64, _>("updated_at")?,
    })
  }
  // --------------------------------------------------------------------------
  // Post Queries
  // --------------------------------------------------------------------------
  
  fn insert_post(&self, data: PostData) -> Result<i64> {
    let sql = format!(
      "INSERT INTO post ({}) VALUES ({ })",
      "bits,content_hash,author_did,signature",
      "?,?,?,?"
    );
    let mut stmt = self.conn.prepare(sql)?;
    
    stmt.bind((1, sql::Value::String(data.bits.to_string())))?;
    stmt.bind((2, sql::Value::String(data.content_hash.to_string())))?;
    stmt.bind((3, sql::Value::String(data.author_did.to_string())))?;
    stmt.bind((4, sql::Value::String(data.signature.to_string())))?;
    stmt.next()?;
    
    // Get the last inserted ID
    let mut stmt = self.conn.prepare("SELECT last_insert_rowid()")?;
    let id: i64 = if let Some(row) = stmt.into_iter().next() {
      row?.read(0)
    } else {
      return Err(Error::Other("Failed to get last insert ID".into()));
    };
    Ok(id)
  }
  
  fn get_post_by_id(&self, id: i64) -> Result<Option<PostData>> {
    let mut stmt = self.conn.prepare(
      "SELECT * FROM post WHERE id = ?1"
    )?;
    stmt.bind((1, sql::Value::Integer(id)))?;
    
    if let Some(row) = stmt.into_iter().next() {
      let row = row?;
      Ok(Some(self.row_to_post(&row)?))
    } else {
      Ok(None)
    }
  }
  
  /// List Posts with dynamic filtering using sea-query
  fn list_posts(&self, limit: Option<usize>, offset: Option<usize>, filter: &PostFilter) -> Result<Vec<PostData>> {
    // Build query with sea-query
    let mut query = Query::select();
    query
      .column(PostIden::Id)
      .column(PostIden::Bits)
      .column(PostIden::ContentHash)
      .column(PostIden::AuthorDid)
      .column(PostIden::Signature)
      .column(PostIden::CreatedAt)
      .column(PostIden::UpdatedAt)
      .from(PostIden::Table);
    
    // Add filter conditions
    let cond = filter.to_condition();
    if !cond.is_empty() {
      query.cond_where(cond);
    }
    
    // Add ordering (by created_at/seen_at desc, or first column if no time field)
    query.order_by(PostIden::CreatedAt, sea_query::Order::Desc);
    
    // Add limit and offset
    if let Some(l) = limit {
      query.limit(l as u64);
    }
    if let Some(o) = offset {
      query.offset(o as u64);
    }
    
    // Build SQL
    let (sql, _values) = query.build(SqliteQueryBuilder);
    
    // Execute with sqlite crate
    let mut stmt = self.conn.prepare(&sql)?;
    let mut results = Vec::new();
    for row in stmt.into_iter() {
      let row = row?;
      results.push(self.row_to_post(&row)?);
    }
    Ok(results)
  }
  
  fn update_post(&self, id: i64, data: PostData) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      r#"
      UPDATE post SET
        bits = ?1,
        content_hash = ?2,
        author_did = ?3,
        signature = ?4,
        updated_at = ?5
      WHERE id = ?6
      "#
    )?;
    
    stmt.bind((1, sql::Value::String(data.bits.to_string())))?;
    stmt.bind((2, sql::Value::String(data.content_hash.to_string())))?;
    stmt.bind((3, sql::Value::String(data.author_did.to_string())))?;
    stmt.bind((4, sql::Value::String(data.signature.to_string())))?;
    stmt.bind((5, sql::Value::Integer(data.updated_at)))?;
    stmt.bind((6, sql::Value::Integer(id)))?;
    
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn update_post_contentHash(&self, id: i64, contentHash: Option<string>) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      "UPDATE post SET content_hash = ?1 WHERE id = ?2"
    )?;
    stmt.bind((1, sql::Value::String(contentHash.to_string())))?;
    stmt.bind((2, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn update_post_authorDid(&self, id: i64, authorDid: Option<string>) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      "UPDATE post SET author_did = ?1 WHERE id = ?2"
    )?;
    stmt.bind((1, sql::Value::String(authorDid.to_string())))?;
    stmt.bind((2, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn update_post_signature(&self, id: i64, signature: Option<string>) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      "UPDATE post SET signature = ?1 WHERE id = ?2"
    )?;
    stmt.bind((1, sql::Value::String(signature.to_string())))?;
    stmt.bind((2, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn update_post_updatedAt(&self, id: i64) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      "UPDATE post SET updated_at = unixepoch() WHERE id = ?1"
    )?;
    stmt.bind((1, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn delete_post(&self, id: i64) -> Result<bool> {
    let mut stmt = self.conn.prepare("DELETE FROM post WHERE id = ?1")?;
    stmt.bind((1, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn row_to_post(&self, row: &sql::Row) -> Result<PostData> {
    Ok(PostData {
      id: row.try_read::<i64, _>("id")?,
      bits: {
        let s = row.try_read::<&str, _>("bits")?;
        serde_json::from_str(s).map_err(|e| Error::Other(format!("JSON parse error: {}", e)))?
      },
      content_hash: row.try_read::<Option<string>, _>("content_hash")?,
      author_did: row.try_read::<Option<string>, _>("author_did")?,
      signature: row.try_read::<Option<string>, _>("signature")?,
      created_at: row.try_read::<i64, _>("created_at")?,
      updated_at: row.try_read::<i64, _>("updated_at")?,
    })
  }
  // --------------------------------------------------------------------------
  // StreamEntry Queries
  // --------------------------------------------------------------------------
  
  fn insert_streamentry(&self, data: StreamEntryData) -> Result<i64> {
    let sql = format!(
      "INSERT INTO stream_entry ({}) VALUES ({ })",
      "seen_at,person_id,post_id,media_id,bookmark_id,conversation_id,directory,kind,content_hash",
      "?,?,?,?,?,?,?,?,?"
    );
    let mut stmt = self.conn.prepare(sql)?;
    
    stmt.bind((1, sql::Value::String(data.seen_at.to_string())))?;
    stmt.bind((2, sql::Value::String(data.person_id.to_string())))?;
    stmt.bind((3, sql::Value::String(data.post_id.to_string())))?;
    stmt.bind((4, sql::Value::String(data.media_id.to_string())))?;
    stmt.bind((5, sql::Value::String(data.bookmark_id.to_string())))?;
    stmt.bind((6, sql::Value::String(data.conversation_id.to_string())))?;
    stmt.bind((7, sql::Value::String(data.directory.to_string())))?;
    stmt.bind((8, sql::Value::String(data.kind.to_string())))?;
    stmt.bind((9, sql::Value::String(data.content_hash.to_string())))?;
    stmt.next()?;
    
    // Get the last inserted ID
    let mut stmt = self.conn.prepare("SELECT last_insert_rowid()")?;
    let id: i64 = if let Some(row) = stmt.into_iter().next() {
      row?.read(0)
    } else {
      return Err(Error::Other("Failed to get last insert ID".into()));
    };
    Ok(id)
  }
  
  fn get_streamentry_by_id(&self, id: i64) -> Result<Option<StreamEntryData>> {
    let mut stmt = self.conn.prepare(
      "SELECT * FROM stream_entry WHERE id = ?1"
    )?;
    stmt.bind((1, sql::Value::Integer(id)))?;
    
    if let Some(row) = stmt.into_iter().next() {
      let row = row?;
      Ok(Some(self.row_to_streamentry(&row)?))
    } else {
      Ok(None)
    }
  }
  
  /// List StreamEntrys with dynamic filtering using sea-query
  fn list_streamentrys(&self, limit: Option<usize>, offset: Option<usize>, filter: &StreamEntryFilter) -> Result<Vec<StreamEntryData>> {
    // Build query with sea-query
    let mut query = Query::select();
    query
      .column(StreamEntryIden::Id)
      .column(StreamEntryIden::SeenAt)
      .column(StreamEntryIden::PersonId)
      .column(StreamEntryIden::PostId)
      .column(StreamEntryIden::MediaId)
      .column(StreamEntryIden::BookmarkId)
      .column(StreamEntryIden::ConversationId)
      .column(StreamEntryIden::Directory)
      .column(StreamEntryIden::Kind)
      .column(StreamEntryIden::ContentHash)
      .column(StreamEntryIden::CreatedAt)
      .from(StreamEntryIden::Table);
    
    // Add filter conditions
    let cond = filter.to_condition();
    if !cond.is_empty() {
      query.cond_where(cond);
    }
    
    // Add ordering (by created_at/seen_at desc, or first column if no time field)
    query.order_by(StreamEntryIden::SeenAt, sea_query::Order::Desc);
    
    // Add limit and offset
    if let Some(l) = limit {
      query.limit(l as u64);
    }
    if let Some(o) = offset {
      query.offset(o as u64);
    }
    
    // Build SQL
    let (sql, _values) = query.build(SqliteQueryBuilder);
    
    // Execute with sqlite crate
    let mut stmt = self.conn.prepare(&sql)?;
    let mut results = Vec::new();
    for row in stmt.into_iter() {
      let row = row?;
      results.push(self.row_to_streamentry(&row)?);
    }
    Ok(results)
  }
  
  fn update_streamentry(&self, id: i64, data: StreamEntryData) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      r#"
      UPDATE stream_entry SET
        seen_at = ?1,
        person_id = ?2,
        post_id = ?3,
        media_id = ?4,
        bookmark_id = ?5,
        conversation_id = ?6,
        directory = ?7,
        kind = ?8,
        content_hash = ?9
      WHERE id = ?10
      "#
    )?;
    
    stmt.bind((1, sql::Value::String(data.seen_at.to_string())))?;
    stmt.bind((2, sql::Value::String(data.person_id.to_string())))?;
    stmt.bind((3, sql::Value::String(data.post_id.to_string())))?;
    stmt.bind((4, sql::Value::String(data.media_id.to_string())))?;
    stmt.bind((5, sql::Value::String(data.bookmark_id.to_string())))?;
    stmt.bind((6, sql::Value::String(data.conversation_id.to_string())))?;
    stmt.bind((7, sql::Value::String(data.directory.to_string())))?;
    stmt.bind((8, sql::Value::String(data.kind.to_string())))?;
    stmt.bind((9, sql::Value::String(data.content_hash.to_string())))?;
    stmt.bind((10, sql::Value::Integer(id)))?;
    
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn update_streamentry_personId(&self, id: i64, personId: Option<number>) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      "UPDATE stream_entry SET person_id = ?1 WHERE id = ?2"
    )?;
    stmt.bind((1, sql::Value::String(personId.to_string())))?;
    stmt.bind((2, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn update_streamentry_postId(&self, id: i64, postId: Option<number>) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      "UPDATE stream_entry SET post_id = ?1 WHERE id = ?2"
    )?;
    stmt.bind((1, sql::Value::String(postId.to_string())))?;
    stmt.bind((2, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn update_streamentry_mediaId(&self, id: i64, mediaId: Option<number>) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      "UPDATE stream_entry SET media_id = ?1 WHERE id = ?2"
    )?;
    stmt.bind((1, sql::Value::String(mediaId.to_string())))?;
    stmt.bind((2, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn update_streamentry_bookmarkId(&self, id: i64, bookmarkId: Option<number>) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      "UPDATE stream_entry SET bookmark_id = ?1 WHERE id = ?2"
    )?;
    stmt.bind((1, sql::Value::String(bookmarkId.to_string())))?;
    stmt.bind((2, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn update_streamentry_conversationId(&self, id: i64, conversationId: Option<number>) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      "UPDATE stream_entry SET conversation_id = ?1 WHERE id = ?2"
    )?;
    stmt.bind((1, sql::Value::String(conversationId.to_string())))?;
    stmt.bind((2, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn update_streamentry_directory(&self, id: i64, directory: Option<string>) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      "UPDATE stream_entry SET directory = ?1 WHERE id = ?2"
    )?;
    stmt.bind((1, sql::Value::String(directory.to_string())))?;
    stmt.bind((2, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn update_streamentry_kind(&self, id: i64, kind: Option<string>) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      "UPDATE stream_entry SET kind = ?1 WHERE id = ?2"
    )?;
    stmt.bind((1, sql::Value::String(kind.to_string())))?;
    stmt.bind((2, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn update_streamentry_contentHash(&self, id: i64, contentHash: Option<string>) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      "UPDATE stream_entry SET content_hash = ?1 WHERE id = ?2"
    )?;
    stmt.bind((1, sql::Value::String(contentHash.to_string())))?;
    stmt.bind((2, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn delete_streamentry(&self, id: i64) -> Result<bool> {
    let mut stmt = self.conn.prepare("DELETE FROM stream_entry WHERE id = ?1")?;
    stmt.bind((1, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn row_to_streamentry(&self, row: &sql::Row) -> Result<StreamEntryData> {
    Ok(StreamEntryData {
      id: row.try_read::<i64, _>("id")?,
      seen_at: row.try_read::<number, _>("seen_at")?,
      person_id: row.try_read::<Option<number>, _>("person_id")?,
      post_id: row.try_read::<Option<number>, _>("post_id")?,
      media_id: row.try_read::<Option<number>, _>("media_id")?,
      bookmark_id: row.try_read::<Option<number>, _>("bookmark_id")?,
      conversation_id: row.try_read::<Option<number>, _>("conversation_id")?,
      directory: row.try_read::<Option<string>, _>("directory")?,
      kind: row.try_read::<Option<string>, _>("kind")?,
      content_hash: row.try_read::<Option<string>, _>("content_hash")?,
      created_at: row.try_read::<i64, _>("created_at")?,
    })
  }
  // --------------------------------------------------------------------------
  // View Queries
  // --------------------------------------------------------------------------
  
  fn insert_view(&self, data: ViewData) -> Result<i64> {
    let sql = format!(
      "INSERT INTO view ({}) VALUES ({ })",
      "index,label,badge,filters,sort_by,is_pinned,is_thestream",
      "?,?,?,?,?,?,?"
    );
    let mut stmt = self.conn.prepare(sql)?;
    
    stmt.bind((1, sql::Value::String(data.index.to_string())))?;
    stmt.bind((2, sql::Value::String(data.label.to_string())))?;
    stmt.bind((3, sql::Value::String(data.badge.to_string())))?;
    stmt.bind((4, sql::Value::String(data.filters.to_string())))?;
    stmt.bind((5, sql::Value::String(data.sort_by.to_string())))?;
    stmt.bind((6, sql::Value::String(data.is_pinned.to_string())))?;
    stmt.bind((7, sql::Value::String(data.is_thestream.to_string())))?;
    stmt.next()?;
    
    // Get the last inserted ID
    let mut stmt = self.conn.prepare("SELECT last_insert_rowid()")?;
    let id: i64 = if let Some(row) = stmt.into_iter().next() {
      row?.read(0)
    } else {
      return Err(Error::Other("Failed to get last insert ID".into()));
    };
    Ok(id)
  }
  
  fn get_view_by_id(&self, id: i64) -> Result<Option<ViewData>> {
    let mut stmt = self.conn.prepare(
      "SELECT * FROM view WHERE id = ?1"
    )?;
    stmt.bind((1, sql::Value::Integer(id)))?;
    
    if let Some(row) = stmt.into_iter().next() {
      let row = row?;
      Ok(Some(self.row_to_view(&row)?))
    } else {
      Ok(None)
    }
  }
  
  /// List Views with dynamic filtering using sea-query
  fn list_views(&self, limit: Option<usize>, offset: Option<usize>, filter: &ViewFilter) -> Result<Vec<ViewData>> {
    // Build query with sea-query
    let mut query = Query::select();
    query
      .column(ViewIden::Id)
      .column(ViewIden::Index)
      .column(ViewIden::Label)
      .column(ViewIden::Badge)
      .column(ViewIden::Filters)
      .column(ViewIden::SortBy)
      .column(ViewIden::IsPinned)
      .column(ViewIden::IsThestream)
      .column(ViewIden::CreatedAt)
      .column(ViewIden::UpdatedAt)
      .from(ViewIden::Table);
    
    // Add filter conditions
    let cond = filter.to_condition();
    if !cond.is_empty() {
      query.cond_where(cond);
    }
    
    // Add ordering (by created_at/seen_at desc, or first column if no time field)
    query.order_by(ViewIden::CreatedAt, sea_query::Order::Desc);
    
    // Add limit and offset
    if let Some(l) = limit {
      query.limit(l as u64);
    }
    if let Some(o) = offset {
      query.offset(o as u64);
    }
    
    // Build SQL
    let (sql, _values) = query.build(SqliteQueryBuilder);
    
    // Execute with sqlite crate
    let mut stmt = self.conn.prepare(&sql)?;
    let mut results = Vec::new();
    for row in stmt.into_iter() {
      let row = row?;
      results.push(self.row_to_view(&row)?);
    }
    Ok(results)
  }
  
  fn update_view(&self, id: i64, data: ViewData) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      r#"
      UPDATE view SET
        index = ?1,
        label = ?2,
        badge = ?3,
        filters = ?4,
        sort_by = ?5,
        is_pinned = ?6,
        is_thestream = ?7,
        updated_at = ?8
      WHERE id = ?9
      "#
    )?;
    
    stmt.bind((1, sql::Value::String(data.index.to_string())))?;
    stmt.bind((2, sql::Value::String(data.label.to_string())))?;
    stmt.bind((3, sql::Value::String(data.badge.to_string())))?;
    stmt.bind((4, sql::Value::String(data.filters.to_string())))?;
    stmt.bind((5, sql::Value::String(data.sort_by.to_string())))?;
    stmt.bind((6, sql::Value::String(data.is_pinned.to_string())))?;
    stmt.bind((7, sql::Value::String(data.is_thestream.to_string())))?;
    stmt.bind((8, sql::Value::Integer(data.updated_at)))?;
    stmt.bind((9, sql::Value::Integer(id)))?;
    
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn update_view_label(&self, id: i64, label: Option<string>) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      "UPDATE view SET label = ?1 WHERE id = ?2"
    )?;
    stmt.bind((1, sql::Value::String(label.to_string())))?;
    stmt.bind((2, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn update_view_updatedAt(&self, id: i64) -> Result<bool> {
    let mut stmt = self.conn.prepare(
      "UPDATE view SET updated_at = unixepoch() WHERE id = ?1"
    )?;
    stmt.bind((1, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn delete_view(&self, id: i64) -> Result<bool> {
    let mut stmt = self.conn.prepare("DELETE FROM view WHERE id = ?1")?;
    stmt.bind((1, sql::Value::Integer(id)))?;
    stmt.next()?;
    Ok(self.conn.change_count() > 0)
  }
  
  fn row_to_view(&self, row: &sql::Row) -> Result<ViewData> {
    Ok(ViewData {
      id: row.try_read::<i64, _>("id")?,
      index: row.try_read::<number, _>("index")?,
      label: row.try_read::<Option<string>, _>("label")?,
      badge: row.try_read::<string, _>("badge")?,
      filters: {
        let s = row.try_read::<&str, _>("filters")?;
        serde_json::from_str(s).map_err(|e| Error::Other(format!("JSON parse error: {}", e)))?
      },
      sort_by: row.try_read::<string, _>("sort_by")?,
      is_pinned: row.try_read::<boolean, _>("is_pinned")?,
      is_thestream: row.try_read::<boolean, _>("is_thestream")?,
      created_at: row.try_read::<i64, _>("created_at")?,
      updated_at: row.try_read::<i64, _>("updated_at")?,
    })
  }
}

// ============================================================================
// Schema Migrations
// ============================================================================

impl DbActor {
  fn migrate_entities(conn: &sql::ConnectionThreadSafe) -> Result<()> {
    // Bookmark table
    conn.execute(
      r#"
      CREATE TABLE IF NOT EXISTS bookmark (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        uri TEXT NOT NULL,
        title TEXT,
        notes TEXT,
        creation_context TEXT NOT NULL,
        created_at INTEGER NOT NULL
      )
      "#
    )?;
    conn.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_bookmark_url ON bookmark(uri)")?;
    conn.execute("CREATE INDEX IF NOT EXISTS idx_bookmark_created ON bookmark(created_at)")?;
    // Conversation table
    conn.execute(
      r#"
      CREATE TABLE IF NOT EXISTS conversation (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        title TEXT,
        content TEXT NOT NULL,
        attributed_to TEXT,
        capture_time TEXT NOT NULL,
        first_entry_time TEXT,
        last_entry_time TEXT,
        source_url TEXT,
        created_at INTEGER NOT NULL,
        updated_at INTEGER NOT NULL
      )
      "#
    )?;
    conn.execute("CREATE INDEX IF NOT EXISTS idx_conversation_created ON conversation(created_at)")?;
    // Media table
    conn.execute(
      r#"
      CREATE TABLE IF NOT EXISTS media (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        content_hash TEXT,
        mime_type TEXT NOT NULL,
        uri TEXT NOT NULL,
        width TEXT,
        height TEXT,
        duration_ms TEXT,
        metadata TEXT,
        created_at INTEGER NOT NULL
      )
      "#
    )?;
    conn.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_media_url ON media(uri)")?;
    conn.execute("CREATE INDEX IF NOT EXISTS idx_media_created ON media(created_at)")?;
    // MediaSource table
    conn.execute(
      r#"
      CREATE TABLE IF NOT EXISTS media_source (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        url TEXT NOT NULL,
        adapter_type TEXT NOT NULL,
        cursor_state TEXT,
        capabilities TEXT NOT NULL,
        config TEXT,
        last_polled_at TEXT,
        last_error TEXT,
        is_active TEXT NOT NULL,
        created_at INTEGER NOT NULL,
        updated_at INTEGER NOT NULL
      )
      "#
    )?;
    conn.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_media_source_url ON media_source(url)")?;
    conn.execute("CREATE INDEX IF NOT EXISTS idx_media_source_created ON media_source(created_at)")?;
    // Person table
    conn.execute(
      r#"
      CREATE TABLE IF NOT EXISTS person (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        display_name TEXT NOT NULL,
        handle TEXT,
        avatar_media_id TEXT,
        metadata TEXT,
        created_at INTEGER NOT NULL,
        updated_at INTEGER NOT NULL
      )
      "#
    )?;
    conn.execute("CREATE INDEX IF NOT EXISTS idx_person_created ON person(created_at)")?;
    // Post table
    conn.execute(
      r#"
      CREATE TABLE IF NOT EXISTS post (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        bits TEXT NOT NULL,
        content_hash TEXT,
        author_did TEXT,
        signature TEXT,
        created_at INTEGER NOT NULL,
        updated_at INTEGER NOT NULL
      )
      "#
    )?;
    conn.execute("CREATE INDEX IF NOT EXISTS idx_post_created ON post(created_at)")?;
    // StreamEntry table
    conn.execute(
      r#"
      CREATE TABLE IF NOT EXISTS stream_entry (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        seen_at TEXT NOT NULL,
        person_id TEXT,
        post_id TEXT,
        media_id TEXT,
        bookmark_id TEXT,
        conversation_id TEXT,
        directory TEXT,
        kind TEXT,
        content_hash TEXT,
        created_at INTEGER NOT NULL
      )
      "#
    )?;
    conn.execute("CREATE INDEX IF NOT EXISTS idx_stream_entry_created ON stream_entry(created_at)")?;
    // View table
    conn.execute(
      r#"
      CREATE TABLE IF NOT EXISTS view (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        index TEXT NOT NULL,
        label TEXT,
        badge TEXT NOT NULL,
        filters TEXT NOT NULL,
        sort_by TEXT NOT NULL,
        is_pinned TEXT NOT NULL,
        is_thestream TEXT NOT NULL,
        created_at INTEGER NOT NULL,
        updated_at INTEGER NOT NULL
      )
      "#
    )?;
    conn.execute("CREATE INDEX IF NOT EXISTS idx_view_created ON view(created_at)")?;
    Ok(())
  }
}
