// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/crates/foundframe/loom/bobbin/rust/db/db_handle.rs.mejs
// Template file: db_handle.rs.mejs
// This is a workspace custom template (from loom/bobbin/)
// 
// To modify the generated output, edit the template file above.
// GENERATED BY db-binding Treadle - Do not edit

use crate::Result;
use crate::db::DbHandle;

impl DbHandle {
  // BOOKMARK operations
  pub async fn create_bookmark(&self, data: BOOKMARKData) -> Result<i64> {
    self.send(DbCommand::CreateBOOKMARK { data }).await
  }
  
  pub async fn get_bookmark_by_id(&self, id: i64) -> Result<Option<BOOKMARKData>> {
    self.send(DbCommand::GetBOOKMARKById { id }).await
  }
  
  pub async fn update_bookmark(&self, id: i64, data: BOOKMARKData) -> Result<bool> {
    self.send(DbCommand::UpdateBOOKMARK { id, data }).await
  }
  
  pub async fn delete_bookmark(&self, id: i64) -> Result<bool> {
    self.send(DbCommand::DeleteBOOKMARK { id }).await
  }
  
  pub async fn list_bookmarks(&self, filter: BOOKMARKFilter) -> Result<Vec<BOOKMARKData>> {
    self.send(DbCommand::ListBOOKMARKs { filter }).await
  }

  // CONVERSATION operations
  pub async fn create_conversation(&self, data: CONVERSATIONData) -> Result<i64> {
    self.send(DbCommand::CreateCONVERSATION { data }).await
  }
  
  pub async fn get_conversation_by_id(&self, id: i64) -> Result<Option<CONVERSATIONData>> {
    self.send(DbCommand::GetCONVERSATIONById { id }).await
  }
  
  pub async fn update_conversation(&self, id: i64, data: CONVERSATIONData) -> Result<bool> {
    self.send(DbCommand::UpdateCONVERSATION { id, data }).await
  }
  
  pub async fn delete_conversation(&self, id: i64) -> Result<bool> {
    self.send(DbCommand::DeleteCONVERSATION { id }).await
  }
  
  pub async fn list_conversations(&self, filter: CONVERSATIONFilter) -> Result<Vec<CONVERSATIONData>> {
    self.send(DbCommand::ListCONVERSATIONs { filter }).await
  }

  // MEDIA operations
  pub async fn create_media(&self, data: MEDIAData) -> Result<i64> {
    self.send(DbCommand::CreateMEDIA { data }).await
  }
  
  pub async fn get_media_by_id(&self, id: i64) -> Result<Option<MEDIAData>> {
    self.send(DbCommand::GetMEDIAById { id }).await
  }
  
  pub async fn update_media(&self, id: i64, data: MEDIAData) -> Result<bool> {
    self.send(DbCommand::UpdateMEDIA { id, data }).await
  }
  
  pub async fn delete_media(&self, id: i64) -> Result<bool> {
    self.send(DbCommand::DeleteMEDIA { id }).await
  }
  
  pub async fn list_medias(&self, filter: MEDIAFilter) -> Result<Vec<MEDIAData>> {
    self.send(DbCommand::ListMEDIAs { filter }).await
  }

  // MEDIA_SOURCE operations
  pub async fn create_media_source(&self, data: MEDIA_SOURCEData) -> Result<i64> {
    self.send(DbCommand::CreateMEDIA_SOURCE { data }).await
  }
  
  pub async fn get_media_source_by_id(&self, id: i64) -> Result<Option<MEDIA_SOURCEData>> {
    self.send(DbCommand::GetMEDIA_SOURCEById { id }).await
  }
  
  pub async fn update_media_source(&self, id: i64, data: MEDIA_SOURCEData) -> Result<bool> {
    self.send(DbCommand::UpdateMEDIA_SOURCE { id, data }).await
  }
  
  pub async fn delete_media_source(&self, id: i64) -> Result<bool> {
    self.send(DbCommand::DeleteMEDIA_SOURCE { id }).await
  }
  
  pub async fn list_media_sources(&self, filter: MEDIA_SOURCEFilter) -> Result<Vec<MEDIA_SOURCEData>> {
    self.send(DbCommand::ListMEDIA_SOURCEs { filter }).await
  }

  // PERSON operations
  pub async fn create_person(&self, data: PERSONData) -> Result<i64> {
    self.send(DbCommand::CreatePERSON { data }).await
  }
  
  pub async fn get_person_by_id(&self, id: i64) -> Result<Option<PERSONData>> {
    self.send(DbCommand::GetPERSONById { id }).await
  }
  
  pub async fn update_person(&self, id: i64, data: PERSONData) -> Result<bool> {
    self.send(DbCommand::UpdatePERSON { id, data }).await
  }
  
  pub async fn delete_person(&self, id: i64) -> Result<bool> {
    self.send(DbCommand::DeletePERSON { id }).await
  }
  
  pub async fn list_persons(&self, filter: PERSONFilter) -> Result<Vec<PERSONData>> {
    self.send(DbCommand::ListPERSONs { filter }).await
  }

  // POST operations
  pub async fn create_post(&self, data: POSTData) -> Result<i64> {
    self.send(DbCommand::CreatePOST { data }).await
  }
  
  pub async fn get_post_by_id(&self, id: i64) -> Result<Option<POSTData>> {
    self.send(DbCommand::GetPOSTById { id }).await
  }
  
  pub async fn update_post(&self, id: i64, data: POSTData) -> Result<bool> {
    self.send(DbCommand::UpdatePOST { id, data }).await
  }
  
  pub async fn delete_post(&self, id: i64) -> Result<bool> {
    self.send(DbCommand::DeletePOST { id }).await
  }
  
  pub async fn list_posts(&self, filter: POSTFilter) -> Result<Vec<POSTData>> {
    self.send(DbCommand::ListPOSTs { filter }).await
  }

  // STREAM_ENTRY operations
  pub async fn create_stream_entry(&self, data: STREAM_ENTRYData) -> Result<i64> {
    self.send(DbCommand::CreateSTREAM_ENTRY { data }).await
  }
  
  pub async fn get_stream_entry_by_id(&self, id: i64) -> Result<Option<STREAM_ENTRYData>> {
    self.send(DbCommand::GetSTREAM_ENTRYById { id }).await
  }
  
  pub async fn update_stream_entry(&self, id: i64, data: STREAM_ENTRYData) -> Result<bool> {
    self.send(DbCommand::UpdateSTREAM_ENTRY { id, data }).await
  }
  
  pub async fn delete_stream_entry(&self, id: i64) -> Result<bool> {
    self.send(DbCommand::DeleteSTREAM_ENTRY { id }).await
  }
  
  pub async fn list_stream_entrys(&self, filter: STREAM_ENTRYFilter) -> Result<Vec<STREAM_ENTRYData>> {
    self.send(DbCommand::ListSTREAM_ENTRYs { filter }).await
  }

  // VIEW operations
  pub async fn create_view(&self, data: VIEWData) -> Result<i64> {
    self.send(DbCommand::CreateVIEW { data }).await
  }
  
  pub async fn get_view_by_id(&self, id: i64) -> Result<Option<VIEWData>> {
    self.send(DbCommand::GetVIEWById { id }).await
  }
  
  pub async fn update_view(&self, id: i64, data: VIEWData) -> Result<bool> {
    self.send(DbCommand::UpdateVIEW { id, data }).await
  }
  
  pub async fn delete_view(&self, id: i64) -> Result<bool> {
    self.send(DbCommand::DeleteVIEW { id }).await
  }
  
  pub async fn list_views(&self, filter: VIEWFilter) -> Result<Vec<VIEWData>> {
    self.send(DbCommand::ListVIEWs { filter }).await
  }

}
