// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/crates/foundframe/loom/bobbin/rust/db/db_handle.rs.ejs
// Template file: db_handle.rs.ejs
// This is a workspace custom template (from loom/bobbin/)
// 
// To modify the generated output, edit the template file above.
// GENERATED BY db-binding Treadle - Do not edit

use crossbeam_channel::Sender;

use crate::db::DbCommand;
use crate::db::oneshot;
use crate::Result;
use crate::db::bookmark_data::BookmarkData;
use crate::db::BookmarkFilter;
use crate::db::conversation_data::ConversationData;
use crate::db::ConversationFilter;
use crate::db::media_data::MediaData;
use crate::db::MediaFilter;
use crate::db::mediasource_data::MediaSourceData;
use crate::db::MediaSourceFilter;
use crate::db::person_data::PersonData;
use crate::db::PersonFilter;
use crate::db::post_data::PostData;
use crate::db::PostFilter;
use crate::db::streamentry_data::StreamEntryData;
use crate::db::StreamEntryFilter;
use crate::db::view_data::ViewData;
use crate::db::ViewFilter;

// ============================================================================
// DbHandle — The Consumer Interface
// ============================================================================

/// Handle to the database actor — the "Management" interface.
#[derive(Clone)]
pub struct DbHandle {
  tx: Sender<DbCommand>,
}

impl DbHandle {
  /// Create a new handle (called by DbActor)
  pub(crate) fn new(tx: Sender<DbCommand>) -> Self {
    Self { tx }
  }
  
  /// Send a command and wait for response
  async fn send_command<T>(&self, make_cmd: impl FnOnce(oneshot::Sender<T>) -> DbCommand) -> T {
    let (tx, rx) = oneshot::channel();
    let cmd = make_cmd(tx);
    
    let _ = self.tx.send(cmd);
    
    rx.recv().expect("DbActor died")
  }
  
  /// Graceful shutdown
  pub fn shutdown(&self) {
    let _ = self.tx.send(DbCommand::Shutdown);
  }
  // ============================================================================
  // Bookmark Operations
  // ============================================================================
  
  /// Insert new bookmark
  pub async fn insert_bookmark(&self, data: BookmarkData) -> Result<i64> {
    self.send_command(|respond| DbCommand::CreateBookmark { data, respond }).await
  }
  
  /// Get bookmark by ID
  pub async fn get_bookmark_by_id(&self, id: i64) -> Result<Option<BookmarkData>> {
    self.send_command(|respond| DbCommand::ReadBookmarkById { id, respond }).await
  }
  /// Get bookmark by URL
  pub async fn get_bookmark_by_url(&self, url: &str) -> Result<Option<BookmarkData>> {
    let url = url.to_string();
    self.send_command(|respond| DbCommand::ReadBookmarkByUrl { url, respond }).await
  }
  
  /// List bookmarks with optional filtering
  ///
  /// # Arguments
  /// * `limit` - Maximum number of results to return
  /// * `offset` - Number of results to skip (for pagination)
  /// * `filter` - Filter criteria (use `BookmarkFilter::new()` for no filtering)
  ///
  /// # Example
  /// ```rust,ignore
  /// // List all entries
  /// let entries = db.list_bookmarks(Some(50), Some(0), BookmarkFilter::new()).await?;
  ///
  /// ```
  pub async fn list_bookmarks(&self, limit: Option<usize>, offset: Option<usize>, filter: BookmarkFilter) -> Result<Vec<BookmarkData>> {
    self.send_command(|respond| DbCommand::ListBookmarks { limit, offset, filter, respond }).await
  }
  
  /// Update bookmark
  pub async fn update_bookmark(&self, id: i64, data: BookmarkData) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdateBookmark { id, data, respond }).await
  }
  /// Update bookmark's title
  pub async fn update_bookmark_title(&self, id: i64, title: Option<string>) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdateBookmarkTitle { id, title, respond }).await
  }
  /// Update bookmark's notes
  pub async fn update_bookmark_notes(&self, id: i64, notes: Option<string>) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdateBookmarkNotes { id, notes, respond }).await
  }
  /// Delete bookmark
  pub async fn delete_bookmark(&self, id: i64) -> Result<bool> {
    self.send_command(|respond| DbCommand::DeleteBookmark { id, respond }).await
  }
  // ============================================================================
  // Conversation Operations
  // ============================================================================
  
  /// Insert new conversation
  pub async fn insert_conversation(&self, data: ConversationData) -> Result<i64> {
    self.send_command(|respond| DbCommand::CreateConversation { data, respond }).await
  }
  
  /// Get conversation by ID
  pub async fn get_conversation_by_id(&self, id: i64) -> Result<Option<ConversationData>> {
    self.send_command(|respond| DbCommand::ReadConversationById { id, respond }).await
  }
  
  /// List conversations with optional filtering
  ///
  /// # Arguments
  /// * `limit` - Maximum number of results to return
  /// * `offset` - Number of results to skip (for pagination)
  /// * `filter` - Filter criteria (use `ConversationFilter::new()` for no filtering)
  ///
  /// # Example
  /// ```rust,ignore
  /// // List all entries
  /// let entries = db.list_conversations(Some(50), Some(0), ConversationFilter::new()).await?;
  ///
  /// ```
  pub async fn list_conversations(&self, limit: Option<usize>, offset: Option<usize>, filter: ConversationFilter) -> Result<Vec<ConversationData>> {
    self.send_command(|respond| DbCommand::ListConversations { limit, offset, filter, respond }).await
  }
  
  /// Update conversation
  pub async fn update_conversation(&self, id: i64, data: ConversationData) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdateConversation { id, data, respond }).await
  }
  /// Update conversation's title
  pub async fn update_conversation_title(&self, id: i64, title: Option<string>) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdateConversationTitle { id, title, respond }).await
  }
  /// Update conversation's attributedTo
  pub async fn update_conversation_attributedTo(&self, id: i64, attributedTo: Option<string>) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdateConversationAttributedTo { id, attributedTo, respond }).await
  }
  /// Update conversation's firstEntryTime
  pub async fn update_conversation_firstEntryTime(&self, id: i64, firstEntryTime: Option<number>) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdateConversationFirstEntryTime { id, firstEntryTime, respond }).await
  }
  /// Update conversation's lastEntryTime
  pub async fn update_conversation_lastEntryTime(&self, id: i64, lastEntryTime: Option<number>) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdateConversationLastEntryTime { id, lastEntryTime, respond }).await
  }
  /// Update conversation's sourceUrl
  pub async fn update_conversation_sourceUrl(&self, id: i64, sourceUrl: Option<string>) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdateConversationSourceUrl { id, sourceUrl, respond }).await
  }
  /// Touch conversation (update updatedAt)
  pub async fn touch_conversation(&self, id: i64) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdateConversationUpdatedAt { id, updatedAt: 0, respond }).await
  }
  /// Delete conversation
  pub async fn delete_conversation(&self, id: i64) -> Result<bool> {
    self.send_command(|respond| DbCommand::DeleteConversation { id, respond }).await
  }
  // ============================================================================
  // Media Operations
  // ============================================================================
  
  /// Insert new media
  pub async fn insert_media(&self, data: MediaData) -> Result<i64> {
    self.send_command(|respond| DbCommand::CreateMedia { data, respond }).await
  }
  
  /// Get media by ID
  pub async fn get_media_by_id(&self, id: i64) -> Result<Option<MediaData>> {
    self.send_command(|respond| DbCommand::ReadMediaById { id, respond }).await
  }
  /// Get media by URL
  pub async fn get_media_by_url(&self, url: &str) -> Result<Option<MediaData>> {
    let url = url.to_string();
    self.send_command(|respond| DbCommand::ReadMediaByUrl { url, respond }).await
  }
  
  /// List medias with optional filtering
  ///
  /// # Arguments
  /// * `limit` - Maximum number of results to return
  /// * `offset` - Number of results to skip (for pagination)
  /// * `filter` - Filter criteria (use `MediaFilter::new()` for no filtering)
  ///
  /// # Example
  /// ```rust,ignore
  /// // List all entries
  /// let entries = db.list_medias(Some(50), Some(0), MediaFilter::new()).await?;
  ///
  /// ```
  pub async fn list_medias(&self, limit: Option<usize>, offset: Option<usize>, filter: MediaFilter) -> Result<Vec<MediaData>> {
    self.send_command(|respond| DbCommand::ListMedias { limit, offset, filter, respond }).await
  }
  
  /// Update media
  pub async fn update_media(&self, id: i64, data: MediaData) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdateMedia { id, data, respond }).await
  }
  /// Update media's contentHash
  pub async fn update_media_contentHash(&self, id: i64, contentHash: Option<string>) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdateMediaContentHash { id, contentHash, respond }).await
  }
  /// Update media's width
  pub async fn update_media_width(&self, id: i64, width: Option<number>) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdateMediaWidth { id, width, respond }).await
  }
  /// Update media's height
  pub async fn update_media_height(&self, id: i64, height: Option<number>) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdateMediaHeight { id, height, respond }).await
  }
  /// Update media's durationMs
  pub async fn update_media_durationMs(&self, id: i64, durationMs: Option<number>) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdateMediaDurationMs { id, durationMs, respond }).await
  }
  /// Update media's metadata
  pub async fn update_media_metadata(&self, id: i64, metadata: Option<serde_json::Value>) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdateMediaMetadata { id, metadata, respond }).await
  }
  /// Delete media
  pub async fn delete_media(&self, id: i64) -> Result<bool> {
    self.send_command(|respond| DbCommand::DeleteMedia { id, respond }).await
  }
  // ============================================================================
  // MediaSource Operations
  // ============================================================================
  
  /// Insert new mediasource
  pub async fn insert_mediasource(&self, data: MediaSourceData) -> Result<i64> {
    self.send_command(|respond| DbCommand::CreateMediaSource { data, respond }).await
  }
  
  /// Get mediasource by ID
  pub async fn get_mediasource_by_id(&self, id: i64) -> Result<Option<MediaSourceData>> {
    self.send_command(|respond| DbCommand::ReadMediaSourceById { id, respond }).await
  }
  /// Get mediasource by URL
  pub async fn get_mediasource_by_url(&self, url: &str) -> Result<Option<MediaSourceData>> {
    let url = url.to_string();
    self.send_command(|respond| DbCommand::ReadMediaSourceByUrl { url, respond }).await
  }
  
  /// List mediasources with optional filtering
  ///
  /// # Arguments
  /// * `limit` - Maximum number of results to return
  /// * `offset` - Number of results to skip (for pagination)
  /// * `filter` - Filter criteria (use `MediaSourceFilter::new()` for no filtering)
  ///
  /// # Example
  /// ```rust,ignore
  /// // List all entries
  /// let entries = db.list_mediasources(Some(50), Some(0), MediaSourceFilter::new()).await?;
  ///
  /// ```
  pub async fn list_mediasources(&self, limit: Option<usize>, offset: Option<usize>, filter: MediaSourceFilter) -> Result<Vec<MediaSourceData>> {
    self.send_command(|respond| DbCommand::ListMediaSources { limit, offset, filter, respond }).await
  }
  
  /// Update mediasource
  pub async fn update_mediasource(&self, id: i64, data: MediaSourceData) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdateMediaSource { id, data, respond }).await
  }
  /// Update mediasource's cursorState
  pub async fn update_mediasource_cursorState(&self, id: i64, cursorState: Option<serde_json::Value>) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdateMediaSourceCursorState { id, cursorState, respond }).await
  }
  /// Update mediasource's config
  pub async fn update_mediasource_config(&self, id: i64, config: Option<serde_json::Value>) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdateMediaSourceConfig { id, config, respond }).await
  }
  /// Update mediasource's lastPolledAt
  pub async fn update_mediasource_lastPolledAt(&self, id: i64, lastPolledAt: Option<number>) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdateMediaSourceLastPolledAt { id, lastPolledAt, respond }).await
  }
  /// Update mediasource's lastError
  pub async fn update_mediasource_lastError(&self, id: i64, lastError: Option<string>) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdateMediaSourceLastError { id, lastError, respond }).await
  }
  /// Touch mediasource (update updatedAt)
  pub async fn touch_mediasource(&self, id: i64) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdateMediaSourceUpdatedAt { id, updatedAt: 0, respond }).await
  }
  /// Delete mediasource
  pub async fn delete_mediasource(&self, id: i64) -> Result<bool> {
    self.send_command(|respond| DbCommand::DeleteMediaSource { id, respond }).await
  }
  // ============================================================================
  // Person Operations
  // ============================================================================
  
  /// Insert new person
  pub async fn insert_person(&self, data: PersonData) -> Result<i64> {
    self.send_command(|respond| DbCommand::CreatePerson { data, respond }).await
  }
  
  /// Get person by ID
  pub async fn get_person_by_id(&self, id: i64) -> Result<Option<PersonData>> {
    self.send_command(|respond| DbCommand::ReadPersonById { id, respond }).await
  }
  
  /// List persons with optional filtering
  ///
  /// # Arguments
  /// * `limit` - Maximum number of results to return
  /// * `offset` - Number of results to skip (for pagination)
  /// * `filter` - Filter criteria (use `PersonFilter::new()` for no filtering)
  ///
  /// # Example
  /// ```rust,ignore
  /// // List all entries
  /// let entries = db.list_persons(Some(50), Some(0), PersonFilter::new()).await?;
  ///
  /// ```
  pub async fn list_persons(&self, limit: Option<usize>, offset: Option<usize>, filter: PersonFilter) -> Result<Vec<PersonData>> {
    self.send_command(|respond| DbCommand::ListPersons { limit, offset, filter, respond }).await
  }
  
  /// Update person
  pub async fn update_person(&self, id: i64, data: PersonData) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdatePerson { id, data, respond }).await
  }
  /// Update person's handle
  pub async fn update_person_handle(&self, id: i64, handle: Option<string>) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdatePersonHandle { id, handle, respond }).await
  }
  /// Update person's avatarMediaId
  pub async fn update_person_avatarMediaId(&self, id: i64, avatarMediaId: Option<number>) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdatePersonAvatarMediaId { id, avatarMediaId, respond }).await
  }
  /// Update person's metadata
  pub async fn update_person_metadata(&self, id: i64, metadata: Option<serde_json::Value>) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdatePersonMetadata { id, metadata, respond }).await
  }
  /// Touch person (update updatedAt)
  pub async fn touch_person(&self, id: i64) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdatePersonUpdatedAt { id, updatedAt: 0, respond }).await
  }
  /// Delete person
  pub async fn delete_person(&self, id: i64) -> Result<bool> {
    self.send_command(|respond| DbCommand::DeletePerson { id, respond }).await
  }
  // ============================================================================
  // Post Operations
  // ============================================================================
  
  /// Insert new post
  pub async fn insert_post(&self, data: PostData) -> Result<i64> {
    self.send_command(|respond| DbCommand::CreatePost { data, respond }).await
  }
  
  /// Get post by ID
  pub async fn get_post_by_id(&self, id: i64) -> Result<Option<PostData>> {
    self.send_command(|respond| DbCommand::ReadPostById { id, respond }).await
  }
  
  /// List posts with optional filtering
  ///
  /// # Arguments
  /// * `limit` - Maximum number of results to return
  /// * `offset` - Number of results to skip (for pagination)
  /// * `filter` - Filter criteria (use `PostFilter::new()` for no filtering)
  ///
  /// # Example
  /// ```rust,ignore
  /// // List all entries
  /// let entries = db.list_posts(Some(50), Some(0), PostFilter::new()).await?;
  ///
  /// ```
  pub async fn list_posts(&self, limit: Option<usize>, offset: Option<usize>, filter: PostFilter) -> Result<Vec<PostData>> {
    self.send_command(|respond| DbCommand::ListPosts { limit, offset, filter, respond }).await
  }
  
  /// Update post
  pub async fn update_post(&self, id: i64, data: PostData) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdatePost { id, data, respond }).await
  }
  /// Update post's contentHash
  pub async fn update_post_contentHash(&self, id: i64, contentHash: Option<string>) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdatePostContentHash { id, contentHash, respond }).await
  }
  /// Update post's authorDid
  pub async fn update_post_authorDid(&self, id: i64, authorDid: Option<string>) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdatePostAuthorDid { id, authorDid, respond }).await
  }
  /// Update post's signature
  pub async fn update_post_signature(&self, id: i64, signature: Option<string>) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdatePostSignature { id, signature, respond }).await
  }
  /// Touch post (update updatedAt)
  pub async fn touch_post(&self, id: i64) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdatePostUpdatedAt { id, updatedAt: 0, respond }).await
  }
  /// Delete post
  pub async fn delete_post(&self, id: i64) -> Result<bool> {
    self.send_command(|respond| DbCommand::DeletePost { id, respond }).await
  }
  // ============================================================================
  // StreamEntry Operations
  // ============================================================================
  
  /// Insert new streamentry
  pub async fn insert_streamentry(&self, data: StreamEntryData) -> Result<i64> {
    self.send_command(|respond| DbCommand::CreateStreamEntry { data, respond }).await
  }
  
  /// Get streamentry by ID
  pub async fn get_streamentry_by_id(&self, id: i64) -> Result<Option<StreamEntryData>> {
    self.send_command(|respond| DbCommand::ReadStreamEntryById { id, respond }).await
  }
  
  /// List streamentrys with optional filtering
  ///
  /// # Arguments
  /// * `limit` - Maximum number of results to return
  /// * `offset` - Number of results to skip (for pagination)
  /// * `filter` - Filter criteria (use `StreamEntryFilter::new()` for no filtering)
  ///
  /// # Example
  /// ```rust,ignore
  /// // List all entries
  /// let entries = db.list_streamentrys(Some(50), Some(0), StreamEntryFilter::new()).await?;
  ///
  /// // Filter by kind
  /// let filter = StreamEntryFilter::new().kind("post".to_string());
  /// let posts = db.list_streamentrys(Some(50), Some(0), filter).await?;
  /// ```
  pub async fn list_streamentrys(&self, limit: Option<usize>, offset: Option<usize>, filter: StreamEntryFilter) -> Result<Vec<StreamEntryData>> {
    self.send_command(|respond| DbCommand::ListStreamEntrys { limit, offset, filter, respond }).await
  }
  
  /// Update streamentry
  pub async fn update_streamentry(&self, id: i64, data: StreamEntryData) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdateStreamEntry { id, data, respond }).await
  }
  /// Update streamentry's personId
  pub async fn update_streamentry_personId(&self, id: i64, personId: Option<number>) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdateStreamEntryPersonId { id, personId, respond }).await
  }
  /// Update streamentry's postId
  pub async fn update_streamentry_postId(&self, id: i64, postId: Option<number>) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdateStreamEntryPostId { id, postId, respond }).await
  }
  /// Update streamentry's mediaId
  pub async fn update_streamentry_mediaId(&self, id: i64, mediaId: Option<number>) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdateStreamEntryMediaId { id, mediaId, respond }).await
  }
  /// Update streamentry's bookmarkId
  pub async fn update_streamentry_bookmarkId(&self, id: i64, bookmarkId: Option<number>) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdateStreamEntryBookmarkId { id, bookmarkId, respond }).await
  }
  /// Update streamentry's conversationId
  pub async fn update_streamentry_conversationId(&self, id: i64, conversationId: Option<number>) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdateStreamEntryConversationId { id, conversationId, respond }).await
  }
  /// Update streamentry's directory
  pub async fn update_streamentry_directory(&self, id: i64, directory: Option<string>) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdateStreamEntryDirectory { id, directory, respond }).await
  }
  /// Update streamentry's kind
  pub async fn update_streamentry_kind(&self, id: i64, kind: Option<string>) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdateStreamEntryKind { id, kind, respond }).await
  }
  /// Update streamentry's contentHash
  pub async fn update_streamentry_contentHash(&self, id: i64, contentHash: Option<string>) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdateStreamEntryContentHash { id, contentHash, respond }).await
  }
  /// Delete streamentry
  pub async fn delete_streamentry(&self, id: i64) -> Result<bool> {
    self.send_command(|respond| DbCommand::DeleteStreamEntry { id, respond }).await
  }
  // ============================================================================
  // View Operations
  // ============================================================================
  
  /// Insert new view
  pub async fn insert_view(&self, data: ViewData) -> Result<i64> {
    self.send_command(|respond| DbCommand::CreateView { data, respond }).await
  }
  
  /// Get view by ID
  pub async fn get_view_by_id(&self, id: i64) -> Result<Option<ViewData>> {
    self.send_command(|respond| DbCommand::ReadViewById { id, respond }).await
  }
  
  /// List views with optional filtering
  ///
  /// # Arguments
  /// * `limit` - Maximum number of results to return
  /// * `offset` - Number of results to skip (for pagination)
  /// * `filter` - Filter criteria (use `ViewFilter::new()` for no filtering)
  ///
  /// # Example
  /// ```rust,ignore
  /// // List all entries
  /// let entries = db.list_views(Some(50), Some(0), ViewFilter::new()).await?;
  ///
  /// ```
  pub async fn list_views(&self, limit: Option<usize>, offset: Option<usize>, filter: ViewFilter) -> Result<Vec<ViewData>> {
    self.send_command(|respond| DbCommand::ListViews { limit, offset, filter, respond }).await
  }
  
  /// Update view
  pub async fn update_view(&self, id: i64, data: ViewData) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdateView { id, data, respond }).await
  }
  /// Update view's label
  pub async fn update_view_label(&self, id: i64, label: Option<string>) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdateViewLabel { id, label, respond }).await
  }
  /// Touch view (update updatedAt)
  pub async fn touch_view(&self, id: i64) -> Result<bool> {
    self.send_command(|respond| DbCommand::UpdateViewUpdatedAt { id, updatedAt: 0, respond }).await
  }
  /// Delete view
  pub async fn delete_view(&self, id: i64) -> Result<bool> {
    self.send_command(|respond| DbCommand::DeleteView { id, respond }).await
  }
}
