// GENERATED BY DBBINDING TREADLE - Do not edit

use async_trait::async_trait;
use crate::db::{DbHandle, Result};
use crate::bookmark::Bookmark;

/// Database operations for Bookmark
#[async_trait]
pub trait BookmarkDb {

  /// Insert a new bookmark
  async fn insert_bookmark(
    &self,
    url: &str,
    title: Option<&str>,
    notes: Option<&str>,
    content_hash: Option<&str>,
  ) -> Result<i64>;

  /// Get bookmark by ID
  async fn get_bookmark_by_id(&self, id: i64) -> Result<Option<Bookmark>>;

  /// Get bookmark by unique field (e.g., URL for bookmarks)
  async fn get_bookmark_by_url(&self, url: &str) -> Result<Option<Bookmark>>;

  /// List all bookmarks with pagination
  async fn list_bookmarks(
    &self,
    limit: Option<usize>,
    offset: Option<usize>,
  ) -> Result<Vec<Bookmark>>;

  /// Update bookmark fields
  async fn update_bookmark(
    &self,
    id: i64,
    title: Option<&str>,
    notes: Option<&str>,
  ) -> Result<bool>;

  /// Delete bookmark by ID
  async fn delete_bookmark(&self, id: i64) -> Result<bool>;

  /// Delete bookmark by unique field
  async fn delete_bookmark_by_url(&self, url: &str) -> Result<bool>;
}

/// Implementation via DbActor
#[async_trait]
impl BookmarkDb for DbHandle {

  /// Insert a new bookmark
  async fn insert_bookmark(
    &self,
    url: &str,
    title: Option<&str>,
    notes: Option<&str>,
    content_hash: Option<&str>,
  ) -> Result<i64>; {
    // Implementation sends DbCommand to actor
    todo!("Generated implementation")
  }

  /// Get bookmark by ID
  async fn get_bookmark_by_id(&self, id: i64) -> Result<Option<Bookmark>>;

  /// Get bookmark by unique field (e.g., URL for bookmarks)
  async fn get_bookmark_by_url(&self, url: &str) -> Result<Option<Bookmark>>; {
    // Implementation sends DbCommand to actor
    todo!("Generated implementation")
  }

  /// List all bookmarks with pagination
  async fn list_bookmarks(
    &self,
    limit: Option<usize>,
    offset: Option<usize>,
  ) -> Result<Vec<Bookmark>>; {
    // Implementation sends DbCommand to actor
    todo!("Generated implementation")
  }

  /// Update bookmark fields
  async fn update_bookmark(
    &self,
    id: i64,
    title: Option<&str>,
    notes: Option<&str>,
  ) -> Result<bool>; {
    // Implementation sends DbCommand to actor
    todo!("Generated implementation")
  }

  /// Delete bookmark by ID
  async fn delete_bookmark(&self, id: i64) -> Result<bool>;

  /// Delete bookmark by unique field
  async fn delete_bookmark_by_url(&self, url: &str) -> Result<bool>; {
    // Implementation sends DbCommand to actor
    todo!("Generated implementation")
  }
}
