// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/crates/foundframe/loom/bobbin/rust/db/entity_data.rs.mejs
// Template file: entity_data.rs.mejs
// This is a workspace custom template (from loom/bobbin/)
// 
// To modify the generated output, edit the template file above.
// GENERATED BY db-binding Treadle - Do not edit

/// BOOKMARK data structure.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct BOOKMARKData {
  /// id
  pub : String,
  /// uri
  pub : String,
  /// title
  pub : Option<String>,
  /// notes
  pub : Option<String>,
  /// creationContext
  pub : serde_json::Value,
  /// createdAt
  pub : String,
}

impl BOOKMARKData {
  /// Create new with default values
  pub fn new() -> Self {
    Self {
      : 0,
      : String::new(),
      : None,
      : None,
      : Default::default(),
      : 0,
    }
  }

  /// Create new with id
  pub fn with_id(id: i64) -> Self {
    let mut data = Self::new();
    data.id = id;
    data
  }
}

impl Default for BOOKMARKData {
  fn default() -> Self {
    Self::new()
  }
}
