// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/crates/foundframe/loom/bobbin/rust/db/entity_data.rs.ejs
// Template file: entity_data.rs.ejs
// This is a workspace custom template (from loom/bobbin/)
// 
// To modify the generated output, edit the template file above.
// GENERATED BY db-binding Treadle - Do not edit

/// Conversation data structure.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ConversationData {
  /// id
  pub id: i64,
  /// title
  pub title: Option<string>,
  /// content
  pub content: serde_json::Value,
  /// attributedTo
  pub attributed_to: Option<string>,
  /// captureTime
  pub capture_time: number,
  /// firstEntryTime
  pub first_entry_time: Option<number>,
  /// lastEntryTime
  pub last_entry_time: Option<number>,
  /// sourceUrl
  pub source_url: Option<string>,
  /// createdAt
  pub created_at: i64,
  /// updatedAt
  pub updated_at: i64,
}

impl ConversationData {
  /// Create new with default values
  pub fn new() -> Self {
    Self {
      id: 0,
      title: None,
      content: Default::default(),
      attributed_to: None,
      capture_time: 0,
      first_entry_time: None,
      last_entry_time: None,
      source_url: None,
      created_at: 0,
      updated_at: 0,
    }
  }


  /// Create new with id
  pub fn with_id(id: i64) -> Self {
    let mut data = Self::new();
    data.id = id;
    data
  }
}

impl Default for ConversationData {
  fn default() -> Self {
    Self::new()
  }
}
