// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/crates/foundframe/loom/bobbin/rust/db/entity_data.rs.mejs
// Template file: entity_data.rs.mejs
// This is a workspace custom template (from loom/bobbin/)
// 
// To modify the generated output, edit the template file above.
// GENERATED BY db-binding Treadle - Do not edit

/// MEDIA data structure.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct MEDIAData {
  /// id
  pub : String,
  /// contentHash
  pub : Option<String>,
  /// mimeType
  pub : String,
  /// uri
  pub : String,
  /// width
  pub : Option<String>,
  /// height
  pub : Option<String>,
  /// durationMs
  pub : Option<String>,
  /// metadata
  pub : Option<serde_json::Value>,
  /// createdAt
  pub : String,
}

impl MEDIAData {
  /// Create new with default values
  pub fn new() -> Self {
    Self {
      : 0,
      : None,
      : String::new(),
      : String::new(),
      : None,
      : None,
      : None,
      : None,
      : 0,
    }
  }

  /// Create new with id
  pub fn with_id(id: i64) -> Self {
    let mut data = Self::new();
    data.id = id;
    data
  }
}

impl Default for MEDIAData {
  fn default() -> Self {
    Self::new()
  }
}
