// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/crates/foundframe/loom/bobbin/rust/db/entity_trait.rs.ejs
// Template file: entity_trait.rs.ejs
// This is a workspace custom template (from loom/bobbin/)
// 
// To modify the generated output, edit the template file above.
// GENERATED BY db-binding Treadle - Do not edit

use async_trait::async_trait;
use crate::db::DbHandle;
use crate::db::media_data::MediaData;
use crate::Result;

/// Database operations for Media
#[async_trait]
pub trait MediaDb {
  /// Insert new media
  async fn insert_media(&self, data: MediaData) -> Result<i64>;

  /// Get media by ID
  async fn get_media_by_id(&self, id: i64) -> Result<Option<MediaData>>;

  /// List all medias
  async fn list_medias(&self, limit: Option<usize>, offset: Option<usize>) -> Result<Vec<MediaData>>;

  /// Update media
  async fn update_media(&self, id: i64, data: MediaData) -> Result<bool>;

  /// Delete media
  async fn delete_media(&self, id: i64) -> Result<bool>;
}

#[async_trait]
impl MediaDb for DbHandle {
  async fn insert_media(&self, _data: MediaData) -> Result<i64> {
    todo!("Insert media")
  }

  async fn get_media_by_id(&self, _id: i64) -> Result<Option<MediaData>> {
    todo!("Get media by id")
  }

  async fn list_medias(&self, _limit: Option<usize>, _offset: Option<usize>) -> Result<Vec<MediaData>> {
    todo!("List medias")
  }

  async fn update_media(&self, _id: i64, _data: MediaData) -> Result<bool> {
    todo!("Update media")
  }

  async fn delete_media(&self, _id: i64) -> Result<bool> {
    todo!("Delete media")
  }
}
