// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/crates/foundframe/loom/bobbin/rust/db/entity_trait.rs.mejs
// Template file: entity_trait.rs.mejs
// This is a workspace custom template (from loom/bobbin/)
// 
// To modify the generated output, edit the template file above.
// GENERATED BY db-binding Treadle - Do not edit

use crate::Result;
use crate::db::MEDIA_SOURCEData;

/// Database operations for MEDIA_SOURCE
pub trait MEDIA_SOURCEDb {
  /// Create a new MEDIA_SOURCE and return its ID
  fn create(&self, data: MEDIA_SOURCEData) -> impl std::future::Future<Output = Result<i64>> + Send;
  
  /// Get MEDIA_SOURCE by ID
  fn get_by_id(&self, id: i64) -> impl std::future::Future<Output = Result<Option<MEDIA_SOURCEData>>> + Send;
  
  /// Update MEDIA_SOURCE by ID
  fn update(&self, id: i64, data: MEDIA_SOURCEData) -> impl std::future::Future<Output = Result<bool>> + Send;
  
  /// Delete MEDIA_SOURCE by ID
  fn delete(&self, id: i64) -> impl std::future::Future<Output = Result<bool>> + Send;
  
  /// List all MEDIA_SOURCEs with optional filter
  fn list(&self) -> impl std::future::Future<Output = Result<Vec<MEDIA_SOURCEData>>> + Send;
}
