// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/crates/foundframe/loom/bobbin/rust/db/entity_data.rs.ejs
// Template file: entity_data.rs.ejs
// This is a workspace custom template (from loom/bobbin/)
// 
// To modify the generated output, edit the template file above.
// GENERATED BY db-binding Treadle - Do not edit

/// MediaSource data structure.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct MediaSourceData {
  /// id
  pub id: ,
  /// url
  pub url: ,
  /// adapterType
  pub adapter_type: ,
  /// cursorState
  pub cursor_state: ,
  /// capabilities
  pub capabilities: ,
  /// config
  pub config: ,
  /// lastPolledAt
  pub last_polled_at: ,
  /// lastError
  pub last_error: ,
  /// isActive
  pub is_active: ,
  /// createdAt
  pub created_at: ,
  /// updatedAt
  pub updated_at: ,
}

impl MediaSourceData {
  /// Create new with default values
  pub fn new() -> Self {
    Self {
      id: 0,
      url: String::new(),
      adapter_type: String::new(),
      cursor_state: None,
      capabilities: Default::default(),
      config: None,
      last_polled_at: None,
      last_error: None,
      is_active: false,
      created_at: 0,
      updated_at: 0,
    }
  }


  /// Create new with id
  pub fn with_id(id: i64) -> Self {
    let mut data = Self::new();
    data.id = id;
    data
  }
}

impl Default for MediaSourceData {
  fn default() -> Self {
    Self::new()
  }
}
