// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/crates/foundframe/loom/bobbin/rust/db/entity_trait.rs.mejs
// Template file: entity_trait.rs.mejs
// This is a workspace custom template (from loom/bobbin/)
// 
// To modify the generated output, edit the template file above.
// GENERATED BY db-binding Treadle - Do not edit

use crate::Result;
use crate::db::PERSONData;

/// Database operations for PERSON
pub trait PERSONDb {
  /// Create a new PERSON and return its ID
  fn create(&self, data: PERSONData) -> impl std::future::Future<Output = Result<i64>> + Send;
  
  /// Get PERSON by ID
  fn get_by_id(&self, id: i64) -> impl std::future::Future<Output = Result<Option<PERSONData>>> + Send;
  
  /// Update PERSON by ID
  fn update(&self, id: i64, data: PERSONData) -> impl std::future::Future<Output = Result<bool>> + Send;
  
  /// Delete PERSON by ID
  fn delete(&self, id: i64) -> impl std::future::Future<Output = Result<bool>> + Send;
  
  /// List all PERSONs with optional filter
  fn list(&self) -> impl std::future::Future<Output = Result<Vec<PERSONData>>> + Send;
}
