// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/crates/foundframe/loom/bobbin/rust/db/entity_trait.rs.mejs
// Template file: entity_trait.rs.mejs
// This is a workspace custom template (from loom/bobbin/)
// 
// To modify the generated output, edit the template file above.
// GENERATED BY db-binding Treadle - Do not edit

use crate::Result;
use crate::db::POSTData;

/// Database operations for POST
pub trait POSTDb {
  /// Create a new POST and return its ID
  fn create(&self, data: POSTData) -> impl std::future::Future<Output = Result<i64>> + Send;
  
  /// Get POST by ID
  fn get_by_id(&self, id: i64) -> impl std::future::Future<Output = Result<Option<POSTData>>> + Send;
  
  /// Update POST by ID
  fn update(&self, id: i64, data: POSTData) -> impl std::future::Future<Output = Result<bool>> + Send;
  
  /// Delete POST by ID
  fn delete(&self, id: i64) -> impl std::future::Future<Output = Result<bool>> + Send;
  
  /// List all POSTs with optional filter
  fn list(&self) -> impl std::future::Future<Output = Result<Vec<POSTData>>> + Send;
}
