// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/crates/foundframe/loom/bobbin/rust/db/entity_trait.rs.mejs
// Template file: entity_trait.rs.mejs
// This is a workspace custom template (from loom/bobbin/)
// 
// To modify the generated output, edit the template file above.
// GENERATED BY db-binding Treadle - Do not edit

use crate::Result;
use crate::db::STREAM_ENTRYData;

/// Database operations for STREAM_ENTRY
pub trait STREAM_ENTRYDb {
  /// Create a new STREAM_ENTRY and return its ID
  fn create(&self, data: STREAM_ENTRYData) -> impl std::future::Future<Output = Result<i64>> + Send;
  
  /// Get STREAM_ENTRY by ID
  fn get_by_id(&self, id: i64) -> impl std::future::Future<Output = Result<Option<STREAM_ENTRYData>>> + Send;
  
  /// Update STREAM_ENTRY by ID
  fn update(&self, id: i64, data: STREAM_ENTRYData) -> impl std::future::Future<Output = Result<bool>> + Send;
  
  /// Delete STREAM_ENTRY by ID
  fn delete(&self, id: i64) -> impl std::future::Future<Output = Result<bool>> + Send;
  
  /// List all STREAM_ENTRYs with optional filter
  fn list(&self) -> impl std::future::Future<Output = Result<Vec<STREAM_ENTRYData>>> + Send;
}
