// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/crates/foundframe/loom/bobbin/rust/db/entity_trait.rs.ejs
// Template file: entity_trait.rs.ejs
// This is a workspace custom template (from loom/bobbin/)
// 
// To modify the generated output, edit the template file above.
// GENERATED BY db-binding Treadle - Do not edit

use async_trait::async_trait;
use crate::db::DbHandle;
use crate::db::view_data::ViewData;
use crate::Result;

/// Database operations for View
#[async_trait]
pub trait ViewDb {
  /// Insert new view
  async fn insert_view(&self, data: ViewData) -> Result<i64>;

  /// Get view by ID
  async fn get_view_by_id(&self, id: i64) -> Result<Option<ViewData>>;

  /// List all views
  async fn list_views(&self, limit: Option<usize>, offset: Option<usize>) -> Result<Vec<ViewData>>;

  /// Update view
  async fn update_view(&self, id: i64, data: ViewData) -> Result<bool>;

  /// Delete view
  async fn delete_view(&self, id: i64) -> Result<bool>;
}

#[async_trait]
impl ViewDb for DbHandle {
  async fn insert_view(&self, _data: ViewData) -> Result<i64> {
    todo!("Insert view")
  }

  async fn get_view_by_id(&self, _id: i64) -> Result<Option<ViewData>> {
    todo!("Get view by id")
  }

  async fn list_views(&self, _limit: Option<usize>, _offset: Option<usize>) -> Result<Vec<ViewData>> {
    todo!("List views")
  }

  async fn update_view(&self, _id: i64, _data: ViewData) -> Result<bool> {
    todo!("Update view")
  }

  async fn delete_view(&self, _id: i64) -> Result<bool> {
    todo!("Delete view")
  }
}
