// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/packages/spire-loom/machinery/bobbin/ddd/port.ts.ejs
// Template file: port.ts.ejs
// To override: Copy this template to loom/bobbin/ddd/port.ts.ejs
// 
// To modify the generated output, edit the template file above.
/**
 * BookmarkPort
 * 
 * Port interface for Bookmark operations.
 * Generated from BookmarkMgmt management methods.
 * 
 * @generated by ddd-services treadle
 */
import type { Bookmark, BookmarkFilter
} from '@o19/foundframe-front/domain';

/**
 * Read adaptor interface for Bookmark
 * Implements read/list operations
 */
export interface BookmarkReadPort {
  getById(
    id: number
  ): Promise<Bookmark>;

  getBookmark(
    uri: string
  ): Promise<Bookmark>;

  list( data: { limit?: number, offset?: number, filter?: BookmarkFilter } ): Promise<Bookmark[]>;

}

/**
 * Write adaptor interface for Bookmark
 * Implements create/update/delete operations
 */
export interface BookmarkWritePort {

  create(data: { url: string, title?: string, notes?: string }): Promise<void>;
  update(data: { id: number, title?: string, notes?: string }): Promise<boolean>;

  delete(id: number): Promise<boolean>;
}

/**
 * Full adaptor interface for Bookmark
 * Implements rest operations
 */
export interface BookmarkPort extends BookmarkReadPort, BookmarkWritePort {
}
