// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/packages/spire-loom/machinery/bobbin/ddd/port.ts.mejs
// Template file: port.ts.mejs
// To override: Copy this template to loom/bobbin/ddd/port.ts.mejs
// 
// To modify the generated output, edit the template file above.
/**
 * CONVERSATION_PORT
 *
 * Port interface for conversation operations.
 * Generated from CONVERSATION management methods.
 *
 * @generated by ddd-services treadle
 */


import type { Conversation
  , ConversationEntry
  , ConversationFilter
} from '@o19/foundframe-front/domain';

/**
 * Read adaptor interface for conversation
 * Implements read/list operations
 */
export interface ConversationReadPort {
}

/**
 * Write adaptor interface for conversation
 * Implements create/update/delete operations
 */
export interface ConversationWritePort {


}

/**
 * Full adaptor interface for conversation
 * Implements rest operations
 */
export interface ConversationPort extends ConversationReadPort, ConversationWritePort {
}
