// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/packages/spire-loom/machinery/bobbin/ddd/port.ts.ejs
// Template file: port.ts.ejs
// To override: Copy this template to loom/bobbin/ddd/port.ts.ejs
// 
// To modify the generated output, edit the template file above.
/**
 * ConversationPort
 * 
 * Port interface for Conversation operations.
 * Generated from ConversationMgmt management methods.
 * 
 * @generated by ddd-services treadle
 */
import type { Conversation, ConversationEntry, ConversationFilter
} from '@o19/foundframe-front/domain';

/**
 * Read adaptor interface for Conversation
 * Implements read/list operations
 */
export interface ConversationReadPort {
  getById(
    id: number
  ): Promise<Conversation>;

  list( data: { limit?: number, offset?: number, filter?: ConversationFilter } ): Promise<Conversation[]>;

}

/**
 * Write adaptor interface for Conversation
 * Implements create/update/delete operations
 */
export interface ConversationWritePort {

  create(data: { content: ConversationEntry[], captureTime: Date, title?: string, sourceUrl?: string }): Promise<void>;
  update(data: { id: number, title?: string, content?: ConversationEntry[] }): Promise<boolean>;

  delete(id: number): Promise<boolean>;
}

/**
 * Full adaptor interface for Conversation
 * Implements rest operations
 */
export interface ConversationPort extends ConversationReadPort, ConversationWritePort {
  /**
   * ConversationMgmt.addParticipant
   */
  addParticipant(data: { conversationId: number, personId: number, role?: string }): Promise<boolean>;
  /**
   * ConversationMgmt.removeParticipant
   */
  removeParticipant(data: { conversationId: number, personId: number }): Promise<boolean>;
  /**
   * ConversationMgmt.listParticipants
   */
  listParticipants(data: { conversationId: number }): Promise<number[]>;
  /**
   * ConversationMgmt.addConversationMedia
   */
  addConversationMedia(data: { conversationId: number, mediaId: number, context?: Record<string, unknown> }): Promise<boolean>;
  /**
   * ConversationMgmt.removeConversationMedia
   */
  removeConversationMedia(data: { conversationId: number, mediaId: number }): Promise<boolean>;
  /**
   * ConversationMgmt.listConversationMedia
   */
  listConversationMedia(data: { conversationId: number }): Promise<number[]>;
}
