// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/packages/spire-loom/machinery/bobbin/ddd/port.ts.mejs
// Template file: port.ts.mejs
// To override: Copy this template to loom/bobbin/ddd/port.ts.mejs
// 
// To modify the generated output, edit the template file above.
/**
 * DEVICE_PORT
 *
 * Port interface for device operations.
 * Generated from DEVICE management methods.
 *
 * @generated by ddd-services treadle
 */


import type { Device
} from '@o19/foundframe-front/domain';

/**
 * Read adaptor interface for device
 * Implements read/list operations
 */
export interface DeviceReadPort {
}

/**
 * Write adaptor interface for device
 * Implements create/update/delete operations
 */
export interface DeviceWritePort {


}

/**
 * Full adaptor interface for device
 * Implements rest operations
 */
export interface DevicePort extends DeviceReadPort, DeviceWritePort {
}
