// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/packages/spire-loom/machinery/bobbin/typescript/ports.ts.mejs
// Template file: ports.ts.mejs
// To override: Copy this template to loom/bobbin/typescript/ports.ts.mejs
// 
// To modify the generated output, edit the template file above.
/**
 * Ports Index
 * 
 * Re-exports all generated port interfaces.
 * 
 * @generated by typescript treadle
 */

export type * from './unknown.port.js';
