// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/packages/spire-loom/machinery/bobbin/ddd/port.ts.ejs
// Template file: port.ts.ejs
// To override: Copy this template to loom/bobbin/ddd/port.ts.ejs
// 
// To modify the generated output, edit the template file above.
/**
 * MediaSourcePort
 * 
 * Port interface for MediaSource operations.
 * Generated from MediaSourceMgmt management methods.
 * 
 * @generated by ddd-services treadle
 */
import type { MediaSource, MediaAdapterType, MediaSourceCapability, PollResult, MediaSourceHealth
} from '@o19/foundframe-front/domain';

/**
 * Read adaptor interface for MediaSource
 * Implements read/list operations
 */
export interface MediaSourceReadPort {
  getById(
    id: number
  ): Promise<MediaSource>;

  list( data: { activeOnly?: boolean, adapterType?: MediaAdapterType } ): Promise<MediaSource[]>;

}

/**
 * Write adaptor interface for MediaSource
 * Implements create/update/delete operations
 */
export interface MediaSourceWritePort {

  create(data: { url: string, adapterType: MediaAdapterType, capabilities: MediaSourceCapability[], config?: Record<string, unknown> }): Promise<void>;
  update(data: { id: number, config?: Record<string, unknown>, isActive?: boolean }): Promise<boolean>;

  delete(id: number): Promise<boolean>;
}

/**
 * Full adaptor interface for MediaSource
 * Implements rest operations
 */
export interface MediaSourcePort extends MediaSourceReadPort, MediaSourceWritePort {
  /**
   * MediaSourceMgmt.pollSource
   */
  pollSource(data: { id: number }): Promise<PollResult>;
  /**
   * MediaSourceMgmt.getHealth
   */
  getHealth(data: { id: number }): Promise<MediaSourceHealth>;
  /**
   * MediaSourceMgmt.resetErrors
   */
  resetErrors(data: { id: number }): Promise<boolean>;
}
