// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/packages/spire-loom/machinery/bobbin/ddd/port.ts.mejs
// Template file: port.ts.mejs
// To override: Copy this template to loom/bobbin/ddd/port.ts.mejs
// 
// To modify the generated output, edit the template file above.
/**
 * PERSON_PORT
 *
 * Port interface for person operations.
 * Generated from PERSON management methods.
 *
 * @generated by ddd-services treadle
 */


import type { Person
  , PersonFilter
} from '@o19/foundframe-front/domain';

/**
 * Read adaptor interface for person
 * Implements read/list operations
 */
export interface PersonReadPort {
}

/**
 * Write adaptor interface for person
 * Implements create/update/delete operations
 */
export interface PersonWritePort {


}

/**
 * Full adaptor interface for person
 * Implements rest operations
 */
export interface PersonPort extends PersonReadPort, PersonWritePort {
}
