// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/packages/spire-loom/machinery/bobbin/ddd/port.ts.ejs
// Template file: port.ts.ejs
// To override: Copy this template to loom/bobbin/ddd/port.ts.ejs
// 
// To modify the generated output, edit the template file above.
/**
 * PersonPort
 * 
 * Port interface for Person operations.
 * Generated from PersonMgmt management methods.
 * 
 * @generated by ddd-services treadle
 */
import type { Person, PersonFilter
} from '@o19/foundframe-front/domain';

/**
 * Read adaptor interface for Person
 * Implements read/list operations
 */
export interface PersonReadPort {
  getById(
    id: number
  ): Promise<Person>;

  getPerson(
    handle: string
  ): Promise<Person>;

  list( data: { limit?: number, offset?: number, filter?: PersonFilter } ): Promise<Person[]>;

}

/**
 * Write adaptor interface for Person
 * Implements create/update/delete operations
 */
export interface PersonWritePort {

  create(data: { displayName: string, handle?: string, metadata?: Record<string, unknown> }): Promise<void>;
  update(data: { id: number, displayName?: string, handle?: string, metadata?: Record<string, unknown> }): Promise<boolean>;

  delete(id: number): Promise<boolean>;
}

/**
 * Full adaptor interface for Person
 * Implements rest operations
 */
export interface PersonPort extends PersonReadPort, PersonWritePort {
}
