// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/packages/spire-loom/machinery/bobbin/ddd/port.ts.mejs
// Template file: port.ts.mejs
// To override: Copy this template to loom/bobbin/ddd/port.ts.mejs
// 
// To modify the generated output, edit the template file above.
/**
 * PKB_PORT
 *
 * Port interface for pkb operations.
 * Generated from PKB management methods.
 *
 * @generated by ddd-services treadle
 */


import type { Pkb
} from '@o19/foundframe-front/domain';

/**
 * Read adaptor interface for pkb
 * Implements read/list operations
 */
export interface PkbReadPort {
}

/**
 * Write adaptor interface for pkb
 * Implements create/update/delete operations
 */
export interface PkbWritePort {


}

/**
 * Full adaptor interface for pkb
 * Implements rest operations
 */
export interface PkbPort extends PkbReadPort, PkbWritePort {
}
