// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/packages/spire-loom/machinery/bobbin/ddd/port.ts.ejs
// Template file: port.ts.ejs
// To override: Copy this template to loom/bobbin/ddd/port.ts.ejs
// 
// To modify the generated output, edit the template file above.
/**
 * PostPort
 * 
 * Port interface for Post operations.
 * Generated from PostMgmt management methods.
 * 
 * @generated by ddd-services treadle
 */
import type { Post, AccumulableBit, ConversationEntry, ConversationFilter, MediaAdapterType, MediaSourceCapability, PollResult, MediaSourceHealth
, PostFilter
} from '@o19/foundframe-front/domain';

/**
 * Read adaptor interface for Post
 * Implements read/list operations
 */
export interface PostReadPort {
  getById(
    id: number
  ): Promise<Post>;

  list( data: { limit?: number, offset?: number, filter?: PostFilter } ): Promise<Post[]>;

}

/**
 * Write adaptor interface for Post
 * Implements create/update/delete operations
 */
export interface PostWritePort {

  create(data: { bits: AccumulableBit[] }): Promise<number>;
  update(data: { id: number, bits?: AccumulableBit[] }): Promise<boolean>;

  delete(id: number): Promise<boolean>;
}

/**
 * Full adaptor interface for Post
 * Implements rest operations
 */
export interface PostPort extends PostReadPort, PostWritePort {
}
