// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/packages/spire-loom/machinery/bobbin/ddd/port.ts.mejs
// Template file: port.ts.mejs
// To override: Copy this template to loom/bobbin/ddd/port.ts.mejs
// 
// To modify the generated output, edit the template file above.
/**
 * POST_PORT
 *
 * Port interface for post operations.
 * Generated from POST management methods.
 *
 * @generated by ddd-services treadle
 */


import type { Post
  , AccumulableBit, ConversationEntry, ConversationFilter, MediaAdapterType, MediaSourceCapability, PollResult, MediaSourceHealth
  , PostFilter
} from '@o19/foundframe-front/domain';

/**
 * Read adaptor interface for post
 * Implements read/list operations
 */
export interface PostReadPort {
}

/**
 * Write adaptor interface for post
 * Implements create/update/delete operations
 */
export interface PostWritePort {


}

/**
 * Full adaptor interface for post
 * Implements rest operations
 */
export interface PostPort extends PostReadPort, PostWritePort {
}
