// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/packages/spire-loom/machinery/bobbin/ddd/port.ts.ejs
// Template file: port.ts.ejs
// To override: Copy this template to loom/bobbin/ddd/port.ts.ejs
// 
// To modify the generated output, edit the template file above.
/**
 * ViewPort
 * 
 * Port interface for View operations.
 * Generated from ViewMgmt management methods.
 * 
 * @generated by ddd-services treadle
 */
import type { View} from '@o19/foundframe-front/domain';

/**
 * Read adaptor interface for View
 * Implements read/list operations
 */
export interface ViewReadPort {
  getById(
    id: number
  ): Promise<View>;

  list(
    
  ): Promise<void[]>;

}

/**
 * Write adaptor interface for View
 * Implements create/update/delete operations
 */
export interface ViewWritePort {

  create(data: { index: number, badge: string, label?: string }): Promise<void>;

  delete(id: number): Promise<boolean>;
}

/**
 * Full adaptor interface for View
 * Implements rest operations
 */
export interface ViewPort extends ViewReadPort, ViewWritePort {
}
