/**
 * Method Enhancement System 🌀
 *
 * Generic method enhancement with language-specific views.
 *
 * Declares itself as the 'method' enhancement system using declareEnhancement().
 * Provides:
 * - enhanceMethod: Transform a raw method for a specific language
 * - createLanguageView: Create an idiomatic view with naming conventions
 * - createEnhancedMethod: Container with multiple language views
 *
 * @module machinery/reed/enhanced/methods
 */

import { languages as languageRegistry, getLanguageExtensionKey } from '../language/index.js';
import type {
  LanguageDefinition,
  LanguageMethod,
  NamingConventions,
  RawMethod
} from '../language/imperative.js';
import type { LanguageParam } from '../language/types.js';
import { pascalCase, camelCase, toSnakeCase } from '../../stringing.js';
import { declareEnhancement } from './enhancement.js';

// ============================================================================
// Method Enhancement
// ============================================================================

/**
 * Enhance a raw method with a language's transform pipeline.
 *
 * @param method - Raw method from management metadata
 * @param language - Language identifier (e.g., 'rust', 'typescript')
 * @returns Language-enhanced method
 * @throws Error if language not registered or has no transform
 */
export function enhanceMethod(method: RawMethod, language: string): LanguageMethod {
  const lang = languageRegistry.get(language);
  if (!lang?.codeGen?.transform) {
    throw new Error(
      `Language '${language}' not registered or has no transform. ` +
        `Registered languages: ${
          languageRegistry
            .getAll()
            .map((l) => l.name)
            .join(', ') || '(none)'
        }`
    );
  }

  const [enhanced] = lang.codeGen.transform([method]);
  return enhanced;
}

// ============================================================================
// Language View
// ============================================================================

/**
 * Simplified parameter view for language views.
 */
export interface ParamView {
  /** Original parameter name */
  readonly name: string;
  /** Language-appropriate variable name */
  readonly variableName: string;
  /** Language-specific type */
  readonly type: string;
  /** Original TypeScript type */
  readonly tsType: string;
  /** Whether parameter is optional */
  readonly optional: boolean;
}

/**
 * Parameter views array with legacy helper properties.
 */
export interface ParamViews extends Array<ParamView> {
  /** Comma-separated parameter list for function signatures (e.g., "name: string, age: number") */
  readonly list: string;
  /** Parameter list with optional markers (e.g., "name?: string") */
  readonly listWithOptionality: string;
  /** Comma-separated parameter names only (e.g., "name, age") */
  readonly names: string;
  /** Object-style invocation (e.g., "name: name, age: age") */
  readonly invocation: string;
}

/**
 * Variant view - function signature with modifiers applied.
 *
 * Variants compose to create different function forms:
 * - method.rs.async.signature → "async fn foo()"
 * - method.rs.pub.async.signature → "pub async fn foo()"
 * - method.ts.public.static.signature → "public static foo()"
 *
 * The variant view calls into lang.codeGen.rendering functions that are
 * generated by compileToExecutive() from declarative config.
 */
export interface VariantView {
  /** Function signature with variants applied */
  readonly signature: string;

  /**
   * Returns the signature for EJS compatibility.
   * Enables: <%= method.crudDefinition.async %>
   */
  toString(): string;

  /**
   * Wrap parameters in an object parameter.
   * Returns a new VariantView with object-wrapped params.
   *
   * @example
   * method.crudDefinition.withObjectParams('data').async
   * // → "async create(data: { name: string }): Promise<Bookmark>"
   */
  withObjectParams(objectParamName: string): VariantView;

  // Chainable variants - each returns a new VariantView with combined modifiers
  readonly async?: VariantView;
  readonly pub?: VariantView;
  readonly public?: VariantView;
  readonly private?: VariantView;
  readonly protected?: VariantView;
  readonly static?: VariantView;
  readonly unsafe?: VariantView;
  readonly const?: VariantView;
  readonly mut?: VariantView;
  readonly ref?: VariantView;
  // Additional variants can be added dynamically
  // Allow function properties like toString() that return string
  [variant: string]:
    | VariantView
    | string
    | (() => string)
    | ((name: string) => VariantView)
    | undefined;
}

/**
 * Language view - idiomatic API for a specific language.
 *
 * Provides naming conventions and simplified access to method properties.
 * Variant accessors (async, pub, etc.) call into rendering functions
 * generated by compileToExecutive() from declarative config.
 */
export interface LanguageView {
  /** Reference to language definition */
  readonly _language: LanguageDefinition;
  /** Reference to underlying LanguageMethod */
  readonly _raw: LanguageMethod;
  /** Reference to naming convention */
  readonly _naming: NamingConventions;

  // Idiomatic naming (from convention)
  /** Function name in language's convention */
  readonly functionName: string;
  /** Type name in language's convention (usually PascalCase) */
  readonly typeName: string;
  /** Variable name in language's convention */
  readonly variableName: string;
  /** Constant name in language's convention (usually SCREAMING_SNAKE) */
  readonly constName: string;
  /** Module/file name in language's convention */
  readonly moduleName: string;

  // Raw names (always available)
  readonly camelName: string;
  readonly pascalName: string;
  readonly snakeName: string;

  // Type information
  /** Return type in language syntax */
  readonly returnType: string;
  /** Stub return value for mocks */
  readonly stubReturn: string;
  /** Parameters with language-appropriate naming */
  readonly params: ParamViews;

  // Base code generation (no variants) - calls functionSignature
  readonly signature: string;

  // Variant accessors - chainable modifiers
  // These call into lang.codeGen.rendering functions
  readonly async: VariantView;
  readonly pub: VariantView;
  readonly public: VariantView;
  readonly private: VariantView;
  readonly protected: VariantView;
  readonly static: VariantView;
  readonly unsafe: VariantView;

  // CRUD definition - uses crudName instead of method.name
  // Example: method.crudDefinition.async.signature → "async create(data: CreateBookmark): Promise<Bookmark>"
  readonly crudDefinition: VariantView;

  // Language-specific extras (dynamic)
  [key: string]: unknown;
}

/**
 * Apply naming convention to a name.
 */
function applyNamingConvention(
  name: string,
  convention: NamingConventions[keyof NamingConventions] | null | undefined
): string {
  if (!convention) return name;

  switch (convention) {
    case 'snake_case':
      return toSnakeCase(name);
    case 'camelCase':
      return camelCase(name);
    case 'PascalCase':
      return pascalCase(name);
    case 'SCREAMING_SNAKE':
      return toSnakeCase(name).toUpperCase();
    case 'kebab-case':
      return toSnakeCase(name).replace(/_/g, '-');
    default:
      return name;
  }
}

/**
 * Create a language view with idiomatic naming.
 *
 * @param method - Language-enhanced method
 * @param lang - Language definition
 * @param langKey - Extension key (rs, ts, kt)
 * @returns Language view with simplified API
 */
export function createLanguageView(
  method: LanguageMethod,
  lang: LanguageDefinition,
  langKey: string
): LanguageView {
  const view = {} as LanguageView;

  // Get naming convention from language declaration
  const naming = lang.conventions.naming;

  // Store references
  Object.defineProperty(view, '_language', {
    value: lang,
    writable: false,
    enumerable: false
  });
  Object.defineProperty(view, '_raw', {
    value: method,
    writable: false,
    enumerable: false
  });
  Object.defineProperty(view, '_naming', {
    value: naming,
    writable: false,
    enumerable: false
  });

  // Idiomatic naming properties
  Object.defineProperty(view, 'functionName', {
    get() {
      return applyNamingConvention(method.name, naming.function);
    },
    enumerable: true
  });

  Object.defineProperty(view, 'typeName', {
    get() {
      return applyNamingConvention(method.name, naming.type);
    },
    enumerable: true
  });

  Object.defineProperty(view, 'variableName', {
    get() {
      return applyNamingConvention(method.name, naming.variable);
    },
    enumerable: true
  });

  Object.defineProperty(view, 'constName', {
    get() {
      return applyNamingConvention(method.name, naming.const);
    },
    enumerable: true
  });

  Object.defineProperty(view, 'moduleName', {
    get() {
      return applyNamingConvention(method.name, naming.module);
    },
    enumerable: true
  });

  // Raw names
  Object.defineProperty(view, 'camelName', {
    get() {
      return method.camelName;
    },
    enumerable: true
  });

  Object.defineProperty(view, 'pascalName', {
    get() {
      return method.pascalName;
    },
    enumerable: true
  });

  Object.defineProperty(view, 'snakeName', {
    get() {
      return method.snakeName;
    },
    enumerable: true
  });

  // Type information
  Object.defineProperty(view, 'returnType', {
    get() {
      return method.returnTypeDef.name;
    },
    enumerable: true
  });

  Object.defineProperty(view, 'stubReturn', {
    get() {
      return method.stubReturn;
    },
    enumerable: true
  });

  // Parameters with language-appropriate naming
  Object.defineProperty(view, 'params', {
    get() {
      const paramViews = method.params.map((p: LanguageParam) => ({
        get name() {
          return p.name;
        },
        get variableName() {
          return applyNamingConvention(p.name, naming.variable);
        },
        get type() {
          return p.langType;
        },
        get tsType() {
          return p.type;
        },
        get optional() {
          return p.optional ?? false;
        }
      }));

      // Legacy helper properties for template compatibility
      Object.defineProperty(paramViews, 'list', {
        get() {
          return method.params
            .map(
              (p: LanguageParam) =>
                `${applyNamingConvention(p.name, naming.variable)}: ${p.langType}`
            )
            .join(', ');
        },
        enumerable: false
      });

      Object.defineProperty(paramViews, 'listWithOptionality', {
        get() {
          return method.params
            .map(
              (p: LanguageParam) =>
                `${applyNamingConvention(p.name, naming.variable)}${p.optional ? '?' : ''}: ${p.langType}`
            )
            .join(', ');
        },
        enumerable: false
      });

      Object.defineProperty(paramViews, 'names', {
        get() {
          return method.params
            .map((p: LanguageParam) => applyNamingConvention(p.name, naming.variable))
            .join(', ');
        },
        enumerable: false
      });

      Object.defineProperty(paramViews, 'invocation', {
        get() {
          return method.params
            .map(
              (p: LanguageParam) =>
                `${applyNamingConvention(p.name, naming.variable)}: ${applyNamingConvention(p.name, naming.variable)}`
            )
            .join(', ');
        },
        enumerable: false
      });

      return paramViews;
    },
    enumerable: true
  });

  // Code generation - base signature (no variants)
  Object.defineProperty(view, 'signature', {
    get() {
      return lang.codeGen.rendering.functionSignature(method);
    },
    enumerable: true
  });

  // Deprecated: definition with hardcoded public=true - use view.pub.signature instead
  Object.defineProperty(view, 'definition', {
    get() {
      const render = lang.codeGen.rendering.renderDefinition;
      return render
        ? render(method, { public: true })
        : lang.codeGen.rendering.functionSignature(method);
    },
    enumerable: true
  });

  // ============================================================================
  // Variant Views - chainable function modifiers
  // ============================================================================

  /**
   * Create a variant view with accumulated modifiers.
   * Calls into lang.codeGen.rendering functions generated by compileToExecutive.
   * Max 3 levels of nesting (e.g., view.pub.static.async).
   *
   * @param variants - Array of variant names (async, pub, etc.)
   * @param depth - Current nesting depth (max 3)
   * @param nameOverride - Optional name to use instead of method.name (for crudDefinition)
   * @param objectParamName - Optional name to wrap params in an object
   */
  function createVariantView(
    variants: string[],
    depth: number = 1,
    nameOverride?: string,
    objectParamName?: string
  ): VariantView {
    const variantView = {} as VariantView;
    const rendering = lang.codeGen.rendering;
    const naming = lang.conventions.naming;

    let effectiveMethod = nameOverride ? method.withNewName(nameOverride) : method;

    // If objectParamName specified, wrap params in an object
    if (objectParamName) {
      if (!rendering.renderObjectWrappedParams) {
        throw new Error(
          `Language '${lang.name}' does not support object-wrapped parameters. ` +
            `Define 'composition.objectWrappedParams' in the language declaration.`
        );
      }
    }

    // Signature getter - uses appropriate rendering function based on variants
    Object.defineProperty(variantView, 'signature', {
      get() {
        const isAsync = variants.includes('async');
        const isPublic = variants.includes('pub') || variants.includes('public');
        const isPrivate = variants.includes('private');
        const isProtected = variants.includes('protected');
        const isStatic = variants.includes('static');

        // Build object-wrapped params if specified
        const paramList = objectParamName
          ? rendering.renderObjectWrappedParams!(effectiveMethod, objectParamName)
          : effectiveMethod.params
              .map((p: LanguageParam) => `${p.formattedName}: ${p.langType}`)
              .join(', ');

        // Priority: visibility/static modifiers use renderDefinition if available
        if (isPublic || isPrivate || isProtected || isStatic) {
          if (rendering.renderDefinition) {
            // Create a synthetic method with the wrapped param list for renderDefinition
            const syntheticMethod = objectParamName
              ? effectiveMethod.cloneWith({
                  params: [
                    {
                      name: objectParamName,
                      type: paramList.replace(/^[^:]+: /, ''),
                      langType: paramList.replace(/^[^:]+: /, ''),
                      formattedName: objectParamName,
                      optional: false
                    } as LanguageParam
                  ]
                })
              : effectiveMethod;
            return rendering.renderDefinition(syntheticMethod, {
              public: isPublic,
              private: isPrivate,
              protected: isProtected,
              static: isStatic,
              async: isAsync
            });
          }
        }

        // Async variant uses asyncFunctionSignature
        if (isAsync && rendering.asyncFunctionSignature) {
          if (objectParamName) {
            // For async with object params, manually construct since asyncFunctionSignature
            // doesn't support object wrapping directly
            const baseSignature = rendering.functionSignature(effectiveMethod);
            // Replace the params in the signature with wrapped version
            const originalParams = effectiveMethod.params
              .map((p: LanguageParam) => `${p.formattedName}: ${p.langType}`)
              .join(', ');
            return baseSignature.replace(originalParams, paramList);
          }
          return rendering.asyncFunctionSignature(effectiveMethod);
        }

        // Fall back to base signature with wrapped params
        const baseSignature = rendering.functionSignature(effectiveMethod);
        if (objectParamName) {
          const originalParams = effectiveMethod.params
            .map((p: LanguageParam) => `${p.formattedName}: ${p.langType}`)
            .join(', ');
          return baseSignature.replace(originalParams, paramList);
        }
        return baseSignature;
      },
      enumerable: true
    });

    // toString for EJS compatibility
    Object.defineProperty(variantView, 'toString', {
      value: function () {
        return this.signature;
      },
      enumerable: false
    });

    // Chainable variant accessors - max 3 levels
    if (depth < 3) {
      const variantNames = [
        'async',
        'pub',
        'public',
        'private',
        'protected',
        'static',
        'unsafe',
        'const',
        'mut',
        'ref'
      ];
      for (const variantName of variantNames) {
        Object.defineProperty(variantView, variantName, {
          get() {
            // Avoid duplicate variants in chain
            if (variants.includes(variantName)) {
              return variantView;
            }
            return createVariantView(
              [...variants, variantName],
              depth + 1,
              nameOverride,
              objectParamName
            );
          },
          enumerable: true
        });
      }
    }

    // withObjectParams - wrap params in an object
    Object.defineProperty(variantView, 'withObjectParams', {
      value: (newObjectParamName: string) => {
        return createVariantView(variants, depth, nameOverride, newObjectParamName);
      },
      enumerable: true
    });

    return variantView;
  }

  // Attach base variant accessors to LanguageView
  const baseVariants = [
    'async',
    'pub',
    'public',
    'private',
    'protected',
    'static',
    'unsafe',
    'const'
  ];
  for (const variantName of baseVariants) {
    Object.defineProperty(view, variantName, {
      get() {
        return createVariantView([variantName]);
      },
      enumerable: true
    });
  }

  // CRUD definition - variant view that uses crudName instead of method.name
  Object.defineProperty(view, 'crudDefinition', {
    get() {
      // Get the crudName from the method (set by CRUD pipeline)
      const crudName = (method as any).crudName;
      if (!crudName) {
        // Fallback to regular name if no crudName
        return createVariantView([]);
      }
      return createVariantView([], 1, crudName);
    },
    enumerable: true
  });

  // Copy any extra properties from custom enhancers
  for (const key of Object.keys(method)) {
    if (key.startsWith('_')) continue;
    if (key in view) continue;

    Object.defineProperty(view, key, {
      get() {
        return (method as unknown as Record<string, unknown>)[key];
      },
      enumerable: true
    });
  }

  return view;
}

// ============================================================================
// Enhanced Method Container
// ============================================================================

/**
 * Enhanced method with multiple language views.
 *
 * The base RawMethod properties are preserved, with language views
 * attached as extension-keyed properties (rs, ts, kt).
 *
 * Getters like `returnType` delegate to the default language view.
 */
export interface EnhancedMethod extends RawMethod {
  /** Default language extension key */
  readonly _default: string;
  /** All enhanced language keys */
  readonly _languages: string[];
  /** Raw methods snapshot for incremental enhancement */
  readonly _raw?: RawMethod[];

  // Default language getters (delegate to _default view)
  readonly returnType: string;
  readonly signature: string;
  readonly definition: string;
  readonly functionName: string;
  readonly typeName: string;
  readonly variableName: string;
  readonly constName: string;
  readonly moduleName: string;
  readonly camelName: string;
  readonly pascalName: string;
  readonly snakeName: string;
  readonly stubReturn: string;
  readonly params: ParamViews;
  readonly crudDefinition: VariantView;

  // Helper methods
  hasTag(tag: string): boolean;

  // Language views by extension key
  readonly rs?: LanguageView;
  readonly ts?: LanguageView;
  readonly kt?: LanguageView;
}

/**
 * Create an enhanced method container with language views.
 *
 * @param raw - Original raw method
 * @param enhancements - Map of language key to {method, lang}
 * @param defaultLangKey - Default language extension key
 * @returns Enhanced method with views and delegating getters
 */
export function createEnhancedMethod(
  raw: RawMethod,
  enhancements: Map<string, { item: LanguageMethod; lang: LanguageDefinition }>,
  defaultLangKey: string
): EnhancedMethod {
  // Start with raw method properties
  const container = { ...raw } as EnhancedMethod;

  // Create views for each language
  for (const [langKey, { item, lang }] of enhancements) {
    const view = createLanguageView(item, lang, langKey);
    (container as unknown as Record<string, unknown>)[langKey] = view;
  }

  // Store metadata
  Object.defineProperty(container, '_default', {
    value: defaultLangKey,
    writable: false,
    enumerable: false
  });

  Object.defineProperty(container, '_languages', {
    value: Array.from(enhancements.keys()),
    writable: false,
    enumerable: false
  });

  // Create delegating getters
  const createDelegator = (prop: keyof LanguageView) => {
    Object.defineProperty(container, prop, {
      get() {
        const view = (this as Record<string, LanguageView>)[this._default];
        return view?.[prop];
      },
      enumerable: true
    });
  };

  createDelegator('returnType');
  createDelegator('signature');
  createDelegator('definition');
  createDelegator('functionName');
  createDelegator('typeName');
  createDelegator('variableName');
  createDelegator('constName');
  createDelegator('moduleName');
  createDelegator('camelName');
  createDelegator('pascalName');
  createDelegator('snakeName');
  createDelegator('stubReturn');
  createDelegator('params');
  createDelegator('crudDefinition');

  // Attach hasTag helper
  if (!('hasTag' in container)) {
    Object.defineProperty(container, 'hasTag', {
      value: function (tag: string): boolean {
        return this.tags?.includes(tag) ?? false;
      },
      enumerable: false
    });
  }

  return container;
}

/**
 * Enhance multiple methods with multiple languages.
 *
 * @param methods - Raw methods to enhance
 * @param languages - Language identifiers to enhance with
 * @param defaultLanguage - Default language (first in array if not specified)
 * @returns Enhanced methods with language views
 */
export function enhanceMethods(
  methods: RawMethod[],
  languages: string[],
  defaultLanguage?: string
): EnhancedMethod[] {
  const defaultLang = defaultLanguage || languages[0];
  const defaultLangKey = getLanguageExtensionKey(defaultLang);

  return methods.map((raw) => {
    // Enhance for each language
    const enhancements = new Map<string, { item: LanguageMethod; lang: LanguageDefinition }>();

    for (const langName of languages) {
      const langKey = getLanguageExtensionKey(langName);
      const langDef = languageRegistry.get(langName);
      if (!langDef) continue;

      const enhanced = enhanceMethod(raw, langName);
      enhancements.set(langKey, { item: enhanced, lang: langDef });
    }

    return createEnhancedMethod(raw, enhancements, defaultLangKey);
  });
}

/**
 * Type guard to check if a method is enhanced.
 */
export function isEnhanced(method: RawMethod | EnhancedMethod): method is EnhancedMethod {
  return '_default' in method;
}

// ============================================================================
// Self-Declaration: The Method Enhancement System
// ============================================================================

/**
 * The method enhancement system.
 *
 * Declares itself using declareEnhancement(), providing both single-item
 * enhancement and batch operations via enhanceAll().
 *
 * @example
 * ```typescript
 * // Direct use (same as enhanceMethod)
 * const enhanced = methodEnhancement(raw, 'rust');
 *
 * // Batch enhance with multiple languages
 * const enhanced = methodEnhancement.enhanceAll(methods, ['rust', 'typescript']);
 * ```
 */
export const methodEnhancement = declareEnhancement({
  name: 'method',
  enhance: enhanceMethod,
  createView: createLanguageView,
  createContainer: (raw, enhancements, defaultLangKey) =>
    createEnhancedMethod(raw, enhancements, defaultLangKey)
});
