import type { MethodMetadata } from '../../../warp/metadata.js';
import { Name } from '../../stringing.js';
import type { FunctionVariantDeclaration } from './declarative.js';
import type { LanguageDefinitionImperative, LanguageRenderingConfig } from './imperative.js';
import { LanguageThing, LanguageValue, type LanguageParam, type LanguageType } from './types.js';

/**
 * Language-specific method extends raw with:
 * - Naming variants (camelName, pascalName, snakeName)
 * - Type definition (returnTypeDef)
 * - Stub return value
 * - Template helpers (params, signature)
 *
 * This is the internal representation after language enhancement.
 * For templates, use LanguageView (from enhanced/methods.ts) which provides
 * idiomatic naming via conventions.
 */
export class LanguageMethod<T extends LanguageType = LanguageType> extends LanguageThing<T> {
  private _render!: LanguageRenderingConfig;
  public tags: string[];
  readonly mgmtName: string;

  /** Reference to underlying LanguageMethod */

  constructor(
    readonly raw: MethodMetadata,
    readonly appliedVariants: Record<string, FunctionVariantDeclaration<T>> = {}
  ) {
    super(raw.name);
    this.tags = raw.tags ?? [];
    this.mgmtName = raw.managementName;
  }

  get name() {
    let name: Name | string = super.name;
    for (const variant of Object.values(this.appliedVariants)) {
      if (variant.overrideName) {
        name = variant.overrideName;
      }
    }
    return name instanceof Name ? name : new Name(name);
  }

  set lang(lang: LanguageDefinitionImperative) {
    super.lang = lang;
    this._render = lang.codeGen.rendering;
  }

  get prependedKeywords() {
    return Object.values(this.appliedVariants)
      .filter((v) => !!v.prependKeyword)
      .map((v) => v.prependKeyword);
  }

  /**
   * Check if this method has a specific tag.
   */
  hasTag(tag: string): boolean {
    return this.tags?.includes(tag) ?? false;
  }

  /**
   * Get CRUD operation from tags (e.g., 'create', 'read').
   */
  getCrudOperation(): string | undefined {
    return this.tags?.find((t) => t.startsWith('crud:'))?.replace('crud:', '');
  }

  /**
   * CRUD operation type (create, read, update, delete, list).
   * Convenience getter that calls getCrudOperation().
   */
  get crudOperation(): string | undefined {
    return this.getCrudOperation();
  }

  get isAsync() {
    return !!this.appliedVariants.async;
  }

  get isPublic() {
    return !!this.appliedVariants.public || !this.appliedVariants.private;
  }

  get isPrivate() {
    return !this.isPublic;
  }

  get isStatic() {
    return !!this.appliedVariants.static;
  }

  get isProtected() {
    return !!this.appliedVariants.protected;
  }

  get isWithObjectParam() {
    return !!this.appliedVariants.objectParam;
  }

  get paramTypes() {
    return this.raw.params.map((p) => this.lang.types.fromTsType(p.tsType, false));
  }

  get returnType() {
    return this.lang.types.fromTsType(this.raw.returnType, !!this.raw.isCollection);
  }

  get params() {
    let params: Array<[string, T]> = this.raw.params.map((p) => [
      p.name,
      this.lang.types.fromTsType(p.tsType) as T
    ]);
    for (const variant of Object.values(this.appliedVariants)) {
      if (variant.processParams) {
        params = variant.processParams(params);
      }
    }
    return this.lang.codeGen.rendering.renderParams(
      params.map((p) => this.lang.codeGen.rendering.formatParam(p[0], p[1]))
    );
  }

  get generics() {
    // TODO
    return '';
  }

  get stubReturn() {
    return this.returnType.stub;
  }

  get signature() {
    return this._render.functionSignature(this);
  }

  get definition() {
    return this._render.renderDefinition(this);
  }

  get crudName() {
    // TODO
    return this.name;
  }

  paramsAsObject(name: string) {
    const propertyCtor = this.lang.types.property;
    if (!propertyCtor) throw new Error("can't wrap params in a language with no objects...");

    return this._render.renderParams([
      this._render.formatParam(
        name,
        this.lang.types.object(
          ...this.raw.params.map((p) => propertyCtor(p.name, this.lang.types.fromTsType(p.tsType)))
        )
      )
    ]);
  }

  // ============================================================================
  // Variant Views - chainable function modifiers
  // ============================================================================

  /**
   * Create a variant view with accumulated modifiers.
   * Calls into lang.codeGen.rendering functions generated by compileToExecutive.
   * Max 3 levels of nesting (e.g., view.pub.static.async).
   *
   * @param variants - Array of variant names (async, pub, etc.)
   * @param depth - Current nesting depth (max 3)
   * @param nameOverride - Optional name to use instead of method.name (for crudDefinition)
   * @param objectParamName - Optional name to wrap params in an object
   */
  createVariant(variantName: string, variant: FunctionVariantDeclaration<T>): LanguageMethod<T> {
    const variants = {
      ...this.appliedVariants,
      [variantName]: variant
    };
    const newMethod = new LanguageMethod(this.raw, variants);

    return newMethod;
  }

  withNewName(overrideName: Name | string, variantName = 'rename'): LanguageMethod<T> {
    return this.createVariant(variantName, {
      overrideName
    });
  }

  withObjectParams(objectParamName: string): LanguageMethod<T> {
    const propertyCtor = this.lang.types.property;
    if (!propertyCtor) throw new Error("can't wrap params in a language with no objects...");
    return this.createVariant('objectParam', {
      processParams: (params: Array<[string, T]>) => [
        [
          objectParamName,
          this.lang.types.object(...params.map(([name, type]) => propertyCtor(name, type))) as T
        ]
      ]
    });
  }

  get crud(): LanguageMethod<T> {
    return this.crudName ? this.withNewName(this.crudName) : this;
  }
}
