// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: tauri/adaptor.ts.ejs
// Template file: adaptor.ts.ejs
// This is a custom template in your workspace
// 
// To modify the generated output, edit the template file above.
// GENERATED BY tauri-adaptor Treadle - Do not edit
// Tauri adaptor exports

// Bookmark commands
export {
  createBookmark,
  updateBookmark,
  deleteBookmark
} from './commands.gen.js';

// Media commands
export {
  createMedia,
  updateMedia,
  deleteMedia
} from './commands.gen.js';

// Post commands
export {
  createPost,
  updatePost,
  deletePost
} from './commands.gen.js';

// Person commands
export {
  createPerson,
  updatePerson,
  deletePerson
} from './commands.gen.js';

// Conversation commands
export {
  createConversation,
  updateConversation,
  deleteConversation
} from './commands.gen.js';

// Re-export all as TauriCommands namespace
export * as TauriCommands from './commands.gen.js';
