// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/packages/spire-loom/machinery/bobbin/ddd/service.ts.ejs
// Template file: service.ts.ejs
// To override: Copy this template to loom/bobbin/ddd/service.ts.ejs
// 
// To modify the generated output, edit the template file above.
/**
 * BookmarkService
 * 
 * Domain service for Bookmark operations.
 * Routes read operations to readAdaptor, write operations to writeAdaptor.
 * 
 * @generated by ddd-services treadle
 */

import type { Bookmark, BookmarkFilter
} from '@o19/foundframe-front/domain';
import type {
  BookmarkPort,
  BookmarkReadPort,
  BookmarkWritePort
} from '@o19/foundframe-front/ports';

export class BookmarkService implements BookmarkPort {
  constructor(
    private readAdaptor: BookmarkReadPort,
    private writeAdaptor: BookmarkWritePort
  ) {}

  // ============================================================================
  // Read Operations (via Tauri)
  // ============================================================================

  async getById(
    id: number
  ): Promise<Bookmark> {
    return this.readAdaptor.getById(
  
    id
   );
  }

  async getBookmark(
    uri: string
  ): Promise<Bookmark> {
    return this.readAdaptor.getBookmark(
  
    uri
   );
  }

  async list( data: { limit?: number, offset?: number, filter?: BookmarkFilter } ): Promise<Bookmark[]> {
    return this.readAdaptor.list(
   data );
  }

  // ============================================================================
  // Write Operations (via Tauri)
  // ============================================================================

  async create(data: { url: string, title?: string, notes?: string }): Promise<void> {
    return this.writeAdaptor.create(data /*url, title, notes*/);
  }

  async update(data: { id: number, title?: string, notes?: string }): Promise<boolean> {
    return this.writeAdaptor.update(data /*id, title, notes*/);
  }

  // ============================================================================
  // Delete Operations (via Tauri)
  // ============================================================================
  async delete(id: number): Promise<boolean> {
    return this.writeAdaptor.delete(id);
  }

  // ============================================================================
  // Passthrough Operations (implementation-specific)
  // ============================================================================
}
