// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/packages/spire-loom/machinery/bobbin/ddd/service.ts.mejs
// Template file: service.ts.mejs
// To override: Copy this template to loom/bobbin/ddd/service.ts.mejs
// 
// To modify the generated output, edit the template file above.
/**
 * PERSON_SERVICE
 * 
 * Domain service for person operations.
 * Routes read operations to readAdaptor, write operations to writeAdaptor.
 * 
 * @generated by ddd-services treadle
 */

import type { Person
  , PersonFilter
} from '@o19/foundframe-front/domain';

import type {
  PERSON_PORT,
  PersonReadPort,
  PersonWritePort
} from '@o19/foundframe-front/ports';

export class PersonService implements PersonPort {
  constructor(
    private readAdaptor: PersonReadPort,
    private writeAdaptor: PersonWritePort
  ) {}

  // ============================================================================
  // Read Operations (via Tauri)
  // ============================================================================

  // ============================================================================
  // Write Operations (via Tauri)
  // ============================================================================

  // ============================================================================
  // Delete Operations (via Tauri)
  // ============================================================================

  // ============================================================================
  // Passthrough Operations (implementation-specific)
  // ============================================================================
}
