// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/packages/spire-loom/machinery/bobbin/ddd/service.ts.ejs
// Template file: service.ts.ejs
// To override: Copy this template to loom/bobbin/ddd/service.ts.ejs
// 
// To modify the generated output, edit the template file above.
/**
 * PersonService
 * 
 * Domain service for Person operations.
 * Routes read operations to readAdaptor, write operations to writeAdaptor.
 * 
 * @generated by ddd-services treadle
 */

import type { Person, PersonFilter
} from '@o19/foundframe-front/domain';
import type {
  PersonPort,
  PersonReadPort,
  PersonWritePort
} from '@o19/foundframe-front/ports';

export class PersonService implements PersonPort {
  constructor(
    private readAdaptor: PersonReadPort,
    private writeAdaptor: PersonWritePort
  ) {}

  // ============================================================================
  // Read Operations (via Tauri)
  // ============================================================================

  async getById(
    id: number
  ): Promise<Person> {
    return this.readAdaptor.getById(
  
    id
   );
  }

  async getPerson(
    handle: string
  ): Promise<Person> {
    return this.readAdaptor.getPerson(
  
    handle
   );
  }

  async list( data: { limit?: number, offset?: number, filter?: PersonFilter } ): Promise<Person[]> {
    return this.readAdaptor.list(
   data );
  }

  // ============================================================================
  // Write Operations (via Tauri)
  // ============================================================================

  async create(data: { displayName: string, handle?: string, metadata?: Record<string, unknown> }): Promise<void> {
    return this.writeAdaptor.create(data /*displayName, handle, metadata*/);
  }

  async update(data: { id: number, displayName?: string, handle?: string, metadata?: Record<string, unknown> }): Promise<boolean> {
    return this.writeAdaptor.update(data /*id, displayName, handle, metadata*/);
  }

  // ============================================================================
  // Delete Operations (via Tauri)
  // ============================================================================
  async delete(id: number): Promise<boolean> {
    return this.writeAdaptor.delete(id);
  }

  // ============================================================================
  // Passthrough Operations (implementation-specific)
  // ============================================================================
}
