// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/packages/spire-loom/machinery/bobbin/ddd/service.ts.mejs
// Template file: service.ts.mejs
// To override: Copy this template to loom/bobbin/ddd/service.ts.mejs
// 
// To modify the generated output, edit the template file above.
/**
 * PKB_SERVICE
 * 
 * Domain service for pkb operations.
 * Routes read operations to readAdaptor, write operations to writeAdaptor.
 * 
 * @generated by ddd-services treadle
 */

import type { Pkb
} from '@o19/foundframe-front/domain';

import type {
  PKB_PORT,
  PkbReadPort,
  PkbWritePort
} from '@o19/foundframe-front/ports';

export class PkbService implements PkbPort {
  constructor(
    private readAdaptor: PkbReadPort,
    private writeAdaptor: PkbWritePort
  ) {}

  // ============================================================================
  // Read Operations (via Tauri)
  // ============================================================================

  // ============================================================================
  // Write Operations (via Tauri)
  // ============================================================================

  // ============================================================================
  // Delete Operations (via Tauri)
  // ============================================================================

  // ============================================================================
  // Passthrough Operations (implementation-specific)
  // ============================================================================
}
