// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/packages/spire-loom/machinery/bobbin/ddd/service.ts.mejs
// Template file: service.ts.mejs
// To override: Copy this template to loom/bobbin/ddd/service.ts.mejs
// 
// To modify the generated output, edit the template file above.
/**
 * POST_SERVICE
 * 
 * Domain service for post operations.
 * Routes read operations to readAdaptor, write operations to writeAdaptor.
 * 
 * @generated by ddd-services treadle
 */

import type { Post
  , AccumulableBit, ConversationEntry, ConversationFilter, MediaAdapterType, MediaSourceCapability, PollResult, MediaSourceHealth
  , PostFilter
} from '@o19/foundframe-front/domain';

import type {
  POST_PORT,
  PostReadPort,
  PostWritePort
} from '@o19/foundframe-front/ports';

export class PostService implements PostPort {
  constructor(
    private readAdaptor: PostReadPort,
    private writeAdaptor: PostWritePort
  ) {}

  // ============================================================================
  // Read Operations (via Tauri)
  // ============================================================================

  // ============================================================================
  // Write Operations (via Tauri)
  // ============================================================================

  // ============================================================================
  // Delete Operations (via Tauri)
  // ============================================================================

  // ============================================================================
  // Passthrough Operations (implementation-specific)
  // ============================================================================
}
