// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/packages/spire-loom/machinery/bobbin/ddd/service.ts.ejs
// Template file: service.ts.ejs
// To override: Copy this template to loom/bobbin/ddd/service.ts.ejs
// 
// To modify the generated output, edit the template file above.
/**
 * PostService
 * 
 * Domain service for Post operations.
 * Routes read operations to readAdaptor, write operations to writeAdaptor.
 * 
 * @generated by ddd-services treadle
 */

import type { Post, AccumulableBit, ConversationEntry, ConversationFilter, MediaAdapterType, MediaSourceCapability, PollResult, MediaSourceHealth
, PostFilter
} from '@o19/foundframe-front/domain';
import type {
  PostPort,
  PostReadPort,
  PostWritePort
} from '@o19/foundframe-front/ports';

export class PostService implements PostPort {
  constructor(
    private readAdaptor: PostReadPort,
    private writeAdaptor: PostWritePort
  ) {}

  // ============================================================================
  // Read Operations (via Tauri)
  // ============================================================================

  async getById(
    id: number
  ): Promise<Post> {
    return this.readAdaptor.getById(
  
    id
   );
  }

  async list( data: { limit?: number, offset?: number, filter?: PostFilter } ): Promise<Post[]> {
    return this.readAdaptor.list(
   data );
  }

  // ============================================================================
  // Write Operations (via Tauri)
  // ============================================================================

  async create(data: { bits: AccumulableBit[] }): Promise<number> {
    return this.writeAdaptor.create(data /*bits*/);
  }

  async update(data: { id: number, bits?: AccumulableBit[] }): Promise<boolean> {
    return this.writeAdaptor.update(data /*id, bits*/);
  }

  // ============================================================================
  // Delete Operations (via Tauri)
  // ============================================================================
  async delete(id: number): Promise<boolean> {
    return this.writeAdaptor.delete(id);
  }

  // ============================================================================
  // Passthrough Operations (implementation-specific)
  // ============================================================================
}
