// GENERATED BY SPIRE-LOOM - DO NOT EDIT (even if LLM)
// 
// This file is automatically generated from a template.
// Changes will be overwritten on next generation.
// 
// Template: /home/mnzaki/Projects/circulari.ty/o19/packages/spire-loom/machinery/bobbin/ddd/service.ts.ejs
// Template file: service.ts.ejs
// To override: Copy this template to loom/bobbin/ddd/service.ts.ejs
// 
// To modify the generated output, edit the template file above.
/**
 * ViewService
 * 
 * Domain service for View operations.
 * Routes read operations to readAdaptor, write operations to writeAdaptor.
 * 
 * @generated by ddd-services treadle
 */

import type { View} from '@o19/foundframe-front/domain';
import type {
  ViewPort,
  ViewReadPort,
  ViewWritePort
} from '@o19/foundframe-front/ports';

export class ViewService implements ViewPort {
  constructor(
    private readAdaptor: ViewReadPort,
    private writeAdaptor: ViewWritePort
  ) {}

  // ============================================================================
  // Read Operations (via Tauri)
  // ============================================================================

  async getById(
    id: number
  ): Promise<View> {
    return this.readAdaptor.getById(
  
    id
   );
  }

  async list(
    
  ): Promise<void[]> {
    return this.readAdaptor.list(
  
    
   );
  }

  // ============================================================================
  // Write Operations (via Tauri)
  // ============================================================================

  async create(data: { index: number, badge: string, label?: string }): Promise<void> {
    return this.writeAdaptor.create(data /*index, badge, label*/);
  }

  // ============================================================================
  // Delete Operations (via Tauri)
  // ============================================================================
  async delete(id: number): Promise<boolean> {
    return this.writeAdaptor.delete(id);
  }

  // ============================================================================
  // Passthrough Operations (implementation-specific)
  // ============================================================================
}
